## Setup

In [1]:
import numpy as np
import pandas as pd
from tqdm.notebook import tqdm
from torch.utils.data import Dataset, DataLoader
import copy
import pickle
import sys
import os

import pytorch_lightning as pl

import logging

sys.path.insert(0, 'C:\\Users\\peter\\anaconda3\\envs\\cv\\Scripts\\ptls-glove')

from functools import partial
from ptls.nn import RnnSeqEncoder, TrxEncoder
from ptls.nn.trx_encoder.trx_encoder_glove import TrxEncoderGlove, TrxEncoderCat, TrxEncoderTrans
from ptls.nn.trx_encoder import GloveEmbedding
from ptls.preprocessing.baseline_discretizer import KDiscretizer, SingleTreeDiscretizer
from ptls.preprocessing.deeptlf.src import DeepTLF
from ptls.frames.coles import CoLESModule
from ptls.data_load.datasets import MemoryMapDataset
from ptls.data_load.iterable_processing import SeqLenFilter
from ptls.frames.coles import ColesDataset
from ptls.frames.coles.split_strategy import SampleSlices
from ptls.frames import PtlsDataModule, TestModule
from ptls.frames.coles.metric import BatchRecallTopK
from ptls.preprocessing.deeptlf import DeepTLFDisc

import ptls
import torch
from torch import nn
from ptls.preprocessing import PandasDataPreprocessor
from sklearn.model_selection import train_test_split
from ptls.data_load.datasets import inference_data_loader
from pytorch_lightning.callbacks.early_stopping import EarlyStopping

C:\Users\peter\anaconda3\envs\cv\lib\site-packages\torchaudio\backend\utils.py:62: UserWarning: No audio backend is available.
  warnings.warn("No audio backend is available.")

In [3]:
# import os

# if not os.path.exists('data/transactions_train.csv'):
#     ! mkdir -p data
#     ! curl -OL https://storage.yandexcloud.net/ptls-datasets/age-prediction-nti-sbebank-2019.zip
#     ! unzip -j -o age-prediction-nti-sbebank-2019.zip 'data/*.csv' -d data
#     ! mv age-prediction-nti-sbebank-2019.zip data/

## Preprocessing rosbank

In [2]:
def get_df_trx(df_train, df_test):
    COL_EVENT_TIME = 'TRDATETIME'
    df_train = df_train.drop(['PERIOD', 'target_flag', 'target_sum'], axis=1)
    df_test = df_test.drop(['PERIOD'], axis=1)

    df = pd.concat([df_train, df_test], ignore_index=True)

    # event_time mapping
    df['_et_day'] = pd.to_datetime(df[COL_EVENT_TIME].str[:7], format='%d%b%y').astype(np.int64) // 10**9
    df['_et_time'] = (pd.to_datetime(df[COL_EVENT_TIME].str[8:], format='%H:%M:%S').astype(np.int64) // 10**9)

    df['event_time'] = df['_et_day'] + df['_et_time']
    df = df.drop(['_et_day', '_et_time', COL_EVENT_TIME], axis=1)

    df.columns = df.columns.str.lower()
    df['amount'] = df['amount'].astype(float)

    return df

def get_df_target(df_train):
    df_target = df_train.groupby("cl_id")["target_flag"].first().astype({"target_flag": 'int'})

    return pd.DataFrame(df_target)

def split_target(df):
    df['seq_len'] =  np.ceil(np.log(df['seq_len'] / np.log(4))).astype('string')
    df['hash'] = (pd.Series(df.index.astype(str) + "42").apply(hash) / (2 ** 32) + 0.5).values
    df['fold_id'] = df.groupby(["target_flag", 'seq_len'])['hash'].rank(method='first', ascending=True) % 6
    
    df = df.drop(columns = ['hash', 'seq_len'])
    return df

def split_fold(fold_id, df_target, df_trx):
    folds_path = Path(conf_pp.folds_path)
    preproc = PysparkDataPreprocessor(
        col_id=conf_pp.col_client_id,
        col_event_time='event_time',
        event_time_transformation='none',
        cols_category=["mcc", "channel_type", "currency", "trx_category"],
        cols_numerical=['amount'],
        cols_last_item=[conf_pp.col_target],
    )
    df_train_trx = df_trx.merge(df_target, how='left', on=conf_pp.col_client_id).loc[lambda x: x['fold_id'].fillna(-1) != fold_id].drop('fold_id', axis=1)
    df_test_trx = df_trx.merge(df_target.loc[lambda x: x['fold_id'] == fold_id].drop('fold_id', axis=1), how='inner', on=conf_pp.col_client_id)
    df_train_data = preproc.fit_transform(df_train_trx)
    df_test_data = preproc.transform(df_test_trx)
    file_name_train = get_file_name_train(fold_id)
    file_name_test = get_file_name_test(fold_id)
    df_train_data.to_parquet(folds_path / file_name_train, mode='overwrite')
    df_test_data.to_parquet(folds_path / file_name_test, mode='overwrite')
    with open(folds_path / f'preproc_{fold_id}.p', 'wb') as f:
        pickle.dump(preproc, f)
    logger.info(f'Preprocessor[{fold_id}].category_dictionary_sizes={preproc.get_category_dictionary_sizes()}')

    for df_name in [file_name_train, file_name_test]:
        df = pd.read_parquet(folds_path / df_name)
        logger.info(f'{df_name:30} {df.shape}')

    for df_name in [file_name_train, file_name_test]:
        df = pd.read_parquet(folds_path / df_name)
        r_counts = df[conf_pp.col_target].value_counts(dropna=False).to_dict()
        cnt_str = ', '.join([f'{r_counts.get(0, 0):5d} - 0 class', f'{r_counts.get(1, 0):5d} - 1 class'])
        logger.info(f'{df_name:30} {cnt_str}')

In [2]:
import os
import pandas as pd

data_path = 'data/rosbank'

train = pd.read_csv(os.path.join(data_path, 'train.csv'))
test = pd.read_csv(os.path.join(data_path, 'test.csv'))

FileNotFoundError: [Errno 2] No such file or directory: 'data/rosbank/train.csv'

In [2]:
df_trx = get_df_trx(train, test)
df_trx = df_trx.fillna("unknown_type")
df_target = get_df_target(train)

NameError: name 'get_df_trx' is not defined

In [6]:
df_trx = df_trx.sort_values(by=["cl_id", "event_time"], ascending=True)

In [7]:
source_data = df_trx.rename({"cl_id" : "client_id", "event_time" : "tr_datetime"})

In [8]:
source_data.rename(columns = {"cl_id" : "client_id", "event_time" : "tr_datatime"}, inplace=True)

In [9]:
source_data

,client_id,mcc,channel_type,currency,amount,trx_category,tr_datatime
1,0,6011,unknown_type,810,20000.00,DEPOSIT,-701177753
0,0,5200,unknown_type,810,5023.00,POS,-700444800
3,0,5411,unknown_type,810,2031.00,POS,-700444800
4,0,6012,unknown_type,810,36562.00,C2C_OUT,-700137936
2,0,5921,unknown_type,810,767.00,POS,-696556800
...,...,...,...,...,...,...,...
1008299,10216,5411,type1,810,132.13,POS,-712886400
1008293,10216,5691,type1,810,2090.00,POS,-712540800
1008296,10216,5411,type1,810,1259.31,POS,-712540800
1008285,10216,5691,type1,810,1185.00,POS,-712454400
1008290,10216,7922,type1,810,1500.00,POS,-712454400

## Preprocessing kaggle card-trans

In [5]:
data_path = 'data/kaggle_nir_card_trans'

data = pd.read_csv(os.path.join(data_path, 'credit_card_transactions.csv'))

## Data preproccessing

In [2]:
def prepare_data_age_bins_scenario():
    data_path = '../data/age_bins'

    source_data = pd.read_csv(os.path.join(data_path, 'transactions_train.csv'))

    df_params = {
        "numeric_cols" : ["amount_rur"],
        "cat_cols" : ["small_group"],
        "date_col" : "trans_date",
        "cat_unique" : [],
        "id_col" : "client_id"
    }

    for f in df_params["cat_cols"] + [df_params["date_col"]]:
        df_params["cat_unique"].append(source_data[f].unique().shape[0])

    return source_data, df_params

def prepare_data_gender_scenario():
    data_path = 'data/gender'

    source_data = pd.read_csv(os.path.join(data_path, 'transactions.csv'))
    source_data = source_data.drop(columns=["term_id"])

    source_data.tr_datetime = [int(i.split()[0]) for i in source_data.tr_datetime.values]

    df_params = {
        "numeric_cols" : ["amount"],
        "cat_cols" : ["mcc_code", "tr_type"],
        "cat_unique" : [],
        "date_col" : "tr_datetime",
        "id_col" : "customer_id"
    }

    for f in df_params["cat_cols"] + [df_params["date_col"]]:
        df_params["cat_unique"].append(source_data[f].unique().shape[0])
    
    return source_data, df_params

In [3]:
source_data, df_params = prepare_data_age_bins_scenario()
targets = pd.read_csv(os.path.join('../data/age_bins', 'train_target.csv'))
source_data.head(2)

   client_id  trans_date  small_group  amount_rur
0      33172           6            4      71.463
1      33172           6           35      45.017

In [30]:
source_data.shape, targets.shape

((26450577, 4), (30000, 2))

In [7]:
#primary encoding of bin features with bin categories

data = simple_bin_numeric(source_data, {"amount" : 20})

In [4]:
EMBED_SIZE = 16

df_params = {'numeric_cols': ['amount_rur'],
     'cat_cols': ['small_group'],
     'date_col': 'trans_date',
     'cat_unique': [202, 730],
     'id_col': 'client_id'}

#best discretizers

disc_quant100 = KDiscretizer(
    f_names = ['amount_rur'],
    k_bins = 100,
    d_type = 'quantile'
)

deeptlf_params9 = DeepTLFDisc({"n_est" : 9,
                  "min_freq" : 2,
                  "features" : df_params['numeric_cols'] + df_params['cat_cols'],
                  "features_to_split" : df_params['numeric_cols'],
                  })

disc_st20 = SingleTreeDiscretizer(
    f_names = ['amount_rur'], 
    target_name = 'bins', 
    target_type = 'classification', 
    k_bins = [20],
)

glove_config1= {"alpha" : 0.75, 
                "x_max" : 100, 
                "embedding_size" : EMBED_SIZE, 
                "num_epochs_train" : 50}

glove_config2= {"alpha" : 0.75, 
                "x_max" : 15000, 
                "embedding_size" : EMBED_SIZE, 
                "num_epochs_train" : 50}

glove_config3= {"alpha" : 1.0, 
                "x_max" : 20000, 
                "embedding_size" : EMBED_SIZE, 
                "num_epochs_train" : 50}

experiments = [
    {
        'name' : 'glove_emb_cfg1_no_num',
        'glove_config' : glove_config1,
        'disc' : None
    },
    {
        'name' : 'glove_emb_cfg2_no_num',
        'glove_config' : glove_config2,
        'disc' : None
    },
    {
        'name' : 'glove_emb_cfg3_no_num',
        'glove_config' : glove_config3,
        'disc' : None
    },
    {
        'name' : 'glove_emb_cfg1_ST20',
        'glove_config' : glove_config1,
        'disc' : disc_st20
    },
    {
        'name' : 'glove_emb_cfg2_quant100',
        'glove_config' : glove_config2,
        'disc' : disc_quant100
    },
    {
        'name' : 'glove_emb_cfg3_quant100',
        'glove_config' : glove_config3,
        'disc' : disc_quant100
    },
    {
        'name' : 'glove_emb_cfg2_deeptlf9',
        'glove_config' : glove_config2,
        'disc' : deeptlf_params9
    },
]

In [5]:
for exp in experiments:
    print(exp['name'])
    data = copy.deepcopy(source_data)
    disc = exp['disc']
    if disc is not None:
        if "ST" not in exp['name']:
            disc.fit_transform(data)
            data = disc.transform(data, to_embeds=False)
        else:
            disc.fit_transform(data.sample(int(1e+5), random_state=42).merge(targets, on=df_params['id_col'], how='left'))
            data = disc.transform(data, to_embeds=False)
        print(f"{exp['name']}: DATA DISCRETIZED")
        
        embedded_feats = df_params['numeric_cols'] + df_params['cat_cols'] + [df_params["date_col"]]
    else:
        embedded_feats = df_params['cat_cols'] + [df_params["date_col"]]
        
    print(embedded_feats)
    glove_embedding = GloveEmbedding(
            feature_names=embedded_feats,
            calculate_cooccur=True,
            embedding_folder=f'../glove_embeddings/{exp["name"]}',
            glove_params=exp['glove_config']
        )
    glove_embedding.fit(data)
    print(f"{exp['name']}: GLOVE EMB CALCULATED")

glove_emb_cfg1_no_num
['small_group', 'trans_date']
train started

  2%|█▋                                                                                 | 1/50 [00:04<03:44,  4.59s/it]

Epoch 0: loss = 27211.30380628349

  4%|███▎                                                                               | 2/50 [00:09<03:37,  4.53s/it]

Epoch 1: loss = 9885.22926825349

  6%|████▉                                                                              | 3/50 [00:13<03:30,  4.49s/it]

Epoch 2: loss = 5232.67445511348

  8%|██████▋                                                                            | 4/50 [00:17<03:25,  4.48s/it]

Epoch 3: loss = 3184.698350348734

 10%|████████▎                                                                          | 5/50 [00:22<03:21,  4.47s/it]

Epoch 4: loss = 2124.3721146066955

 12%|█████████▉                                                                         | 6/50 [00:26<03:16,  4.47s/it]

Epoch 5: loss = 1512.7160505794216

 14%|███████████▌                                                                       | 7/50 [00:31<03:12,  4.47s/it]

Epoch 6: loss = 1131.8027236138646

 16%|█████████████▎                                                                     | 8/50 [00:35<03:07,  4.46s/it]

Epoch 7: loss = 881.299344304634

 18%|██████████████▉                                                                    | 9/50 [00:40<03:04,  4.49s/it]

Epoch 8: loss = 709.7950364768874

 20%|████████████████▍                                                                 | 10/50 [00:44<02:58,  4.47s/it]

Epoch 9: loss = 588.8250727049992

 22%|██████████████████                                                                | 11/50 [00:49<02:55,  4.50s/it]

Epoch 10: loss = 501.3600888796066

 24%|███████████████████▋                                                              | 12/50 [00:53<02:50,  4.49s/it]

Epoch 11: loss = 436.82903779294446

 26%|█████████████████████▎                                                            | 13/50 [00:58<02:45,  4.48s/it]

Epoch 12: loss = 388.3115665464043

 28%|██████████████████████▉                                                           | 14/50 [01:02<02:40,  4.46s/it]

Epoch 13: loss = 351.221482380189

 30%|████████████████████████▌                                                         | 15/50 [01:07<02:36,  4.46s/it]

Epoch 14: loss = 322.4404678672621

 32%|██████████████████████████▏                                                       | 16/50 [01:11<02:32,  4.47s/it]

Epoch 15: loss = 299.77206652964384

 34%|███████████████████████████▉                                                      | 17/50 [01:16<02:28,  4.49s/it]

Epoch 16: loss = 281.6767579784838

 36%|█████████████████████████████▌                                                    | 18/50 [01:20<02:25,  4.54s/it]

Epoch 17: loss = 267.05631907147176

 38%|███████████████████████████████▏                                                  | 19/50 [01:25<02:22,  4.59s/it]

Epoch 18: loss = 255.0865959146019

 40%|████████████████████████████████▊                                                 | 20/50 [01:30<02:18,  4.60s/it]

Epoch 19: loss = 245.18751509128234

 42%|██████████████████████████████████▍                                               | 21/50 [01:34<02:13,  4.59s/it]

Epoch 20: loss = 236.9030065859622

 44%|████████████████████████████████████                                              | 22/50 [01:39<02:08,  4.59s/it]

Epoch 21: loss = 229.90271264672478

 46%|█████████████████████████████████████▋                                            | 23/50 [01:44<02:05,  4.65s/it]

Epoch 22: loss = 223.94353129705448

 48%|███████████████████████████████████████▎                                          | 24/50 [01:48<02:01,  4.69s/it]

Epoch 23: loss = 218.82239476337853

 50%|█████████████████████████████████████████                                         | 25/50 [01:53<01:57,  4.68s/it]

Epoch 24: loss = 214.3839996350787

 52%|██████████████████████████████████████████▋                                       | 26/50 [01:58<01:51,  4.66s/it]

Epoch 25: loss = 210.51668023669075

 54%|████████████████████████████████████████████▎                                     | 27/50 [02:02<01:46,  4.63s/it]

Epoch 26: loss = 207.10923359174666

 56%|█████████████████████████████████████████████▉                                    | 28/50 [02:07<01:41,  4.60s/it]

Epoch 27: loss = 204.1026463946736

 58%|███████████████████████████████████████████████▌                                  | 29/50 [02:11<01:36,  4.60s/it]

Epoch 28: loss = 201.4266969620922

 60%|█████████████████████████████████████████████████▏                                | 30/50 [02:16<01:31,  4.58s/it]

Epoch 29: loss = 199.04069117670295

 62%|██████████████████████████████████████████████████▊                               | 31/50 [02:21<01:27,  4.62s/it]

Epoch 30: loss = 196.89644376247315

 64%|████████████████████████████████████████████████████▍                             | 32/50 [02:25<01:22,  4.60s/it]

Epoch 31: loss = 194.95459247301832

 66%|██████████████████████████████████████████████████████                            | 33/50 [02:30<01:18,  4.60s/it]

Epoch 32: loss = 193.1905186575154

 68%|███████████████████████████████████████████████████████▊                          | 34/50 [02:34<01:13,  4.60s/it]

Epoch 33: loss = 191.59420186541962

 70%|█████████████████████████████████████████████████████████▍                        | 35/50 [02:39<01:08,  4.59s/it]

Epoch 34: loss = 190.13439592580397

 72%|███████████████████████████████████████████████████████████                       | 36/50 [02:44<01:04,  4.59s/it]

Epoch 35: loss = 188.78866074359965

 74%|████████████████████████████████████████████████████████████▋                     | 37/50 [02:48<00:59,  4.58s/it]

Epoch 36: loss = 187.55713217384246

 76%|██████████████████████████████████████████████████████████████▎                   | 38/50 [02:53<00:55,  4.64s/it]

Epoch 37: loss = 186.4128698839904

 78%|███████████████████████████████████████████████████████████████▉                  | 39/50 [02:58<00:51,  4.69s/it]

Epoch 38: loss = 185.35484460386525

 80%|█████████████████████████████████████████████████████████████████▌                | 40/50 [03:03<00:49,  4.97s/it]

Epoch 39: loss = 184.37053633923728

 82%|███████████████████████████████████████████████████████████████████▏              | 41/50 [03:08<00:44,  4.89s/it]

Epoch 40: loss = 183.4558049177453

 84%|████████████████████████████████████████████████████████████████████▉             | 42/50 [03:13<00:38,  4.85s/it]

Epoch 41: loss = 182.59812332975108

 86%|██████████████████████████████████████████████████████████████████████▌           | 43/50 [03:17<00:33,  4.80s/it]

Epoch 42: loss = 181.79528176648478

 88%|████████████████████████████████████████████████████████████████████████▏         | 44/50 [03:22<00:28,  4.73s/it]

Epoch 43: loss = 181.03552876778897

 90%|█████████████████████████████████████████████████████████████████████████▊        | 45/50 [03:27<00:23,  4.75s/it]

Epoch 44: loss = 180.32991139166978

 92%|███████████████████████████████████████████████████████████████████████████▍      | 46/50 [03:32<00:19,  4.77s/it]

Epoch 45: loss = 179.65215527756885

 94%|█████████████████████████████████████████████████████████████████████████████     | 47/50 [03:36<00:14,  4.77s/it]

Epoch 46: loss = 179.0138842529007

 96%|██████████████████████████████████████████████████████████████████████████████▋   | 48/50 [03:41<00:09,  4.73s/it]

Epoch 47: loss = 178.41154450782534

 98%|████████████████████████████████████████████████████████████████████████████████▎ | 49/50 [03:46<00:04,  4.75s/it]

Epoch 48: loss = 177.83801136627753

100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [03:51<00:00,  4.62s/it]

Epoch 49: loss = 177.28694355191416
glove_emb_cfg1_no_num: GLOVE EMB CALCULATED
glove_emb_cfg2_no_num

['small_group', 'trans_date']
train started

  2%|█▋                                                                                 | 1/50 [00:04<03:48,  4.66s/it]

Epoch 0: loss = 3702.538378712325

  4%|███▎                                                                               | 2/50 [00:09<03:42,  4.63s/it]

Epoch 1: loss = 1692.9694255437898

  6%|████▉                                                                              | 3/50 [00:14<03:41,  4.71s/it]

Epoch 2: loss = 1005.7277422730516

  8%|██████▋                                                                            | 4/50 [00:18<03:35,  4.69s/it]

Epoch 3: loss = 649.023013162668

 10%|████████▎                                                                          | 5/50 [00:23<03:27,  4.61s/it]

Epoch 4: loss = 444.74481423358117

 12%|█████████▉                                                                         | 6/50 [00:27<03:22,  4.59s/it]

Epoch 5: loss = 319.8932605854272

 14%|███████████▌                                                                       | 7/50 [00:32<03:18,  4.61s/it]

Epoch 6: loss = 239.2744660762325

 16%|█████████████▎                                                                     | 8/50 [00:36<03:13,  4.60s/it]

Epoch 7: loss = 184.55819360788016

 18%|██████████████▉                                                                    | 9/50 [00:41<03:09,  4.63s/it]

Epoch 8: loss = 145.90863128717262

 20%|████████████████▍                                                                 | 10/50 [00:46<03:04,  4.62s/it]

Epoch 9: loss = 117.6690906345195

 22%|██████████████████                                                                | 11/50 [00:50<03:00,  4.63s/it]

Epoch 10: loss = 96.49445322671923

 24%|███████████████████▋                                                              | 12/50 [00:55<02:55,  4.63s/it]

Epoch 11: loss = 80.26962025930906

 26%|█████████████████████▎                                                            | 13/50 [01:00<02:52,  4.66s/it]

Epoch 12: loss = 67.61482841059629

 28%|██████████████████████▉                                                           | 14/50 [01:04<02:48,  4.67s/it]

Epoch 13: loss = 57.59321423354324

 30%|████████████████████████▌                                                         | 15/50 [01:09<02:43,  4.68s/it]

Epoch 14: loss = 49.5723550276114

 32%|██████████████████████████▏                                                       | 16/50 [01:14<02:39,  4.70s/it]

Epoch 15: loss = 43.08297002096707

 34%|███████████████████████████▉                                                      | 17/50 [01:19<02:34,  4.68s/it]

Epoch 16: loss = 37.7863876763763

 36%|█████████████████████████████▌                                                    | 18/50 [01:23<02:30,  4.69s/it]

Epoch 17: loss = 33.426648246224424

 38%|███████████████████████████████▏                                                  | 19/50 [01:28<02:24,  4.66s/it]

Epoch 18: loss = 29.815182232635937

 40%|████████████████████████████████▊                                                 | 20/50 [01:33<02:19,  4.66s/it]

Epoch 19: loss = 26.802086889819325

 42%|██████████████████████████████████▍                                               | 21/50 [01:37<02:14,  4.63s/it]

Epoch 20: loss = 24.27585013653624

 44%|████████████████████████████████████                                              | 22/50 [01:42<02:09,  4.63s/it]

Epoch 21: loss = 22.14385109895962

 46%|█████████████████████████████████████▋                                            | 23/50 [01:46<02:05,  4.66s/it]

Epoch 22: loss = 20.337584880387123

 48%|███████████████████████████████████████▎                                          | 24/50 [01:51<02:02,  4.70s/it]

Epoch 23: loss = 18.79663796094827

 50%|█████████████████████████████████████████                                         | 25/50 [01:56<01:57,  4.72s/it]

Epoch 24: loss = 17.47860941121887

 52%|██████████████████████████████████████████▋                                       | 26/50 [02:01<01:54,  4.79s/it]

Epoch 25: loss = 16.344127736045547

 54%|████████████████████████████████████████████▎                                     | 27/50 [02:06<01:50,  4.80s/it]

Epoch 26: loss = 15.364546805086855

 56%|█████████████████████████████████████████████▉                                    | 28/50 [02:11<01:45,  4.79s/it]

Epoch 27: loss = 14.514522449366824

 58%|███████████████████████████████████████████████▌                                  | 29/50 [02:15<01:39,  4.75s/it]

Epoch 28: loss = 13.77392734841777

 60%|█████████████████████████████████████████████████▏                                | 30/50 [02:20<01:34,  4.75s/it]

Epoch 29: loss = 13.124961669640356

 62%|██████████████████████████████████████████████████▊                               | 31/50 [02:25<01:30,  4.75s/it]

Epoch 30: loss = 12.555133018608206

 64%|████████████████████████████████████████████████████▍                             | 32/50 [02:29<01:25,  4.76s/it]

Epoch 31: loss = 12.051608187078338

 66%|██████████████████████████████████████████████████████                            | 33/50 [02:34<01:21,  4.82s/it]

Epoch 32: loss = 11.606171635576114

 68%|███████████████████████████████████████████████████████▊                          | 34/50 [02:39<01:17,  4.85s/it]

Epoch 33: loss = 11.20972430343178

 70%|█████████████████████████████████████████████████████████▍                        | 35/50 [02:44<01:13,  4.92s/it]

Epoch 34: loss = 10.855925089885261

 72%|███████████████████████████████████████████████████████████                       | 36/50 [02:49<01:08,  4.89s/it]

Epoch 35: loss = 10.53859114803278

 74%|████████████████████████████████████████████████████████████▋                     | 37/50 [02:54<01:04,  4.94s/it]

Epoch 36: loss = 10.25314408360644

 76%|██████████████████████████████████████████████████████████████▎                   | 38/50 [02:59<00:59,  4.93s/it]

Epoch 37: loss = 9.99539797915985

 78%|███████████████████████████████████████████████████████████████▉                  | 39/50 [03:04<00:53,  4.90s/it]

Epoch 38: loss = 9.761933783786853

 80%|█████████████████████████████████████████████████████████████████▌                | 40/50 [03:09<00:49,  4.91s/it]

Epoch 39: loss = 9.549744266609222

 82%|███████████████████████████████████████████████████████████████████▏              | 41/50 [03:14<00:44,  4.93s/it]

Epoch 40: loss = 9.356022536124694

 84%|████████████████████████████████████████████████████████████████████▉             | 42/50 [03:19<00:39,  4.91s/it]

Epoch 41: loss = 9.178818678824602

 86%|██████████████████████████████████████████████████████████████████████▌           | 43/50 [03:24<00:34,  4.94s/it]

Epoch 42: loss = 9.016372306324332

 88%|████████████████████████████████████████████████████████████████████████▏         | 44/50 [03:29<00:29,  4.87s/it]

Epoch 43: loss = 8.866631268167199

 90%|█████████████████████████████████████████████████████████████████████████▊        | 45/50 [03:34<00:24,  4.90s/it]

Epoch 44: loss = 8.728535737306842

 92%|███████████████████████████████████████████████████████████████████████████▍      | 46/50 [03:38<00:19,  4.89s/it]

Epoch 45: loss = 8.600915477508725

 94%|█████████████████████████████████████████████████████████████████████████████     | 47/50 [03:43<00:14,  4.89s/it]

Epoch 46: loss = 8.482548811912524

 96%|██████████████████████████████████████████████████████████████████████████████▋   | 48/50 [03:48<00:09,  4.91s/it]

Epoch 47: loss = 8.372343194580573

 98%|████████████████████████████████████████████████████████████████████████████████▎ | 49/50 [03:53<00:04,  4.87s/it]

Epoch 48: loss = 8.26950675399669

100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [03:58<00:00,  4.77s/it]

Epoch 49: loss = 8.17380741704763
glove_emb_cfg2_no_num: GLOVE EMB CALCULATED
glove_emb_cfg3_no_num

['small_group', 'trans_date']
train started

  2%|█▋                                                                                 | 1/50 [00:04<03:49,  4.69s/it]

Epoch 0: loss = 2213.594501153988

  4%|███▎                                                                               | 2/50 [00:09<03:49,  4.79s/it]

Epoch 1: loss = 1072.4435854060298

  6%|████▉                                                                              | 3/50 [00:14<03:42,  4.74s/it]

Epoch 2: loss = 652.3463868754554

  8%|██████▋                                                                            | 4/50 [00:18<03:35,  4.69s/it]

Epoch 3: loss = 430.8775076695363

 10%|████████▎                                                                          | 5/50 [00:23<03:31,  4.69s/it]

Epoch 4: loss = 301.22638158179996

 12%|█████████▉                                                                         | 6/50 [00:28<03:27,  4.72s/it]

Epoch 5: loss = 219.82047028363021

 14%|███████████▌                                                                       | 7/50 [00:33<03:23,  4.74s/it]

Epoch 6: loss = 165.80578862817595

 16%|█████████████▎                                                                     | 8/50 [00:37<03:19,  4.75s/it]

Epoch 7: loss = 128.47624791036867

 18%|██████████████▉                                                                    | 9/50 [00:42<03:15,  4.76s/it]

Epoch 8: loss = 101.73870579409447

 20%|████████████████▍                                                                 | 10/50 [00:47<03:10,  4.76s/it]

Epoch 9: loss = 82.08402654796548

 22%|██████████████████                                                                | 11/50 [00:52<03:06,  4.79s/it]

Epoch 10: loss = 67.2873697557078

 24%|███████████████████▋                                                              | 12/50 [00:57<03:02,  4.80s/it]

Epoch 11: loss = 55.942600815407104

 26%|█████████████████████▎                                                            | 13/50 [01:01<02:57,  4.79s/it]

Epoch 12: loss = 47.09814314708277

 28%|██████████████████████▉                                                           | 14/50 [01:06<02:54,  4.84s/it]

Epoch 13: loss = 40.09777574747612

 30%|████████████████████████▌                                                         | 15/50 [01:11<02:50,  4.87s/it]

Epoch 14: loss = 34.49542969631073

 32%|██████████████████████████▏                                                       | 16/50 [01:16<02:44,  4.85s/it]

Epoch 15: loss = 29.96250265833836

 34%|███████████████████████████▉                                                      | 17/50 [01:21<02:39,  4.84s/it]

Epoch 16: loss = 26.262108393204702

 36%|█████████████████████████████▌                                                    | 18/50 [01:26<02:33,  4.81s/it]

Epoch 17: loss = 23.206027780380047

 38%|███████████████████████████████▏                                                  | 19/50 [01:30<02:28,  4.80s/it]

Epoch 18: loss = 20.66887636456105

 40%|████████████████████████████████▊                                                 | 20/50 [01:35<02:23,  4.77s/it]

Epoch 19: loss = 18.548420631047897

 42%|██████████████████████████████████▍                                               | 21/50 [01:40<02:17,  4.74s/it]

Epoch 20: loss = 16.762071362826873

 44%|████████████████████████████████████                                              | 22/50 [01:45<02:13,  4.77s/it]

Epoch 21: loss = 15.248965399335923

 46%|█████████████████████████████████████▋                                            | 23/50 [01:49<02:08,  4.76s/it]

Epoch 22: loss = 13.95824223366051

 48%|███████████████████████████████████████▎                                          | 24/50 [01:54<02:03,  4.77s/it]

Epoch 23: loss = 12.853500784615319

 50%|█████████████████████████████████████████                                         | 25/50 [01:59<01:58,  4.74s/it]

Epoch 24: loss = 11.90086762846075

 52%|██████████████████████████████████████████▋                                       | 26/50 [02:04<01:53,  4.74s/it]

Epoch 25: loss = 11.076627474659508

 54%|████████████████████████████████████████████▎                                     | 27/50 [02:08<01:49,  4.75s/it]

Epoch 26: loss = 10.360111123124794

 56%|█████████████████████████████████████████████▉                                    | 28/50 [02:13<01:45,  4.80s/it]

Epoch 27: loss = 9.73397130893505

 58%|███████████████████████████████████████████████▌                                  | 29/50 [02:18<01:40,  4.79s/it]

Epoch 28: loss = 9.184455227839758

 60%|█████████████████████████████████████████████████▏                                | 30/50 [02:23<01:36,  4.81s/it]

Epoch 29: loss = 8.700581222605566

 62%|██████████████████████████████████████████████████▊                               | 31/50 [02:28<01:32,  4.86s/it]

Epoch 30: loss = 8.272728395274973

 64%|████████████████████████████████████████████████████▍                             | 32/50 [02:33<01:28,  4.89s/it]

Epoch 31: loss = 7.891385389551469

 66%|██████████████████████████████████████████████████████                            | 33/50 [02:38<01:22,  4.88s/it]

Epoch 32: loss = 7.5525151172842255

 68%|███████████████████████████████████████████████████████▊                          | 34/50 [02:42<01:17,  4.85s/it]

Epoch 33: loss = 7.2486490958577745

 70%|█████████████████████████████████████████████████████████▍                        | 35/50 [02:47<01:12,  4.85s/it]

Epoch 34: loss = 6.974198749215753

 72%|███████████████████████████████████████████████████████████                       | 36/50 [02:52<01:07,  4.84s/it]

Epoch 35: loss = 6.728712337945568

 74%|████████████████████████████████████████████████████████████▋                     | 37/50 [02:57<01:03,  4.92s/it]

Epoch 36: loss = 6.505512261395029

 76%|██████████████████████████████████████████████████████████████▎                   | 38/50 [03:02<00:59,  4.94s/it]

Epoch 37: loss = 6.3016517643299155

 78%|███████████████████████████████████████████████████████████████▉                  | 39/50 [03:07<00:54,  4.94s/it]

Epoch 38: loss = 6.116300548056817

 80%|█████████████████████████████████████████████████████████████████▌                | 40/50 [03:12<00:49,  4.91s/it]

Epoch 39: loss = 5.946498888588312

 82%|███████████████████████████████████████████████████████████████████▏              | 41/50 [03:17<00:44,  4.91s/it]

Epoch 40: loss = 5.790937182618744

 84%|████████████████████████████████████████████████████████████████████▉             | 42/50 [03:22<00:38,  4.87s/it]

Epoch 41: loss = 5.64773498875352

 86%|██████████████████████████████████████████████████████████████████████▌           | 43/50 [03:26<00:34,  4.86s/it]

Epoch 42: loss = 5.515535441164545

 88%|████████████████████████████████████████████████████████████████████████▏         | 44/50 [03:31<00:28,  4.83s/it]

Epoch 43: loss = 5.3919838071686925

 90%|█████████████████████████████████████████████████████████████████████████▊        | 45/50 [03:36<00:24,  4.83s/it]

Epoch 44: loss = 5.277827870174667

 92%|███████████████████████████████████████████████████████████████████████████▍      | 46/50 [03:42<00:20,  5.01s/it]

Epoch 45: loss = 5.171436537982925

 94%|█████████████████████████████████████████████████████████████████████████████     | 47/50 [03:47<00:15,  5.06s/it]

Epoch 46: loss = 5.071429626317531

 96%|██████████████████████████████████████████████████████████████████████████████▋   | 48/50 [03:52<00:10,  5.05s/it]

Epoch 47: loss = 4.978076646101954

 98%|████████████████████████████████████████████████████████████████████████████████▎ | 49/50 [03:56<00:04,  4.94s/it]

Epoch 48: loss = 4.890090732771452

100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [04:01<00:00,  4.83s/it]

Epoch 49: loss = 4.807880980827712
glove_emb_cfg3_no_num: GLOVE EMB CALCULATED
glove_emb_cfg1_ST20

amount_rur:   0%|          | 0/15 [00:00<?, ?it/s]

glove_emb_cfg1_ST20: DATA DISCRETIZED
['amount_rur', 'small_group', 'trans_date']
train started

  2%|█▋                                                                                 | 1/50 [00:05<04:22,  5.35s/it]

Epoch 0: loss = 44458.22008981273

  4%|███▎                                                                               | 2/50 [00:10<04:16,  5.34s/it]

Epoch 1: loss = 16320.671852429427

  6%|████▉                                                                              | 3/50 [00:15<04:09,  5.32s/it]

Epoch 2: loss = 8373.345580579384

  8%|██████▋                                                                            | 4/50 [00:21<04:06,  5.36s/it]

Epoch 3: loss = 4880.170595066894

 10%|████████▎                                                                          | 5/50 [00:27<04:06,  5.47s/it]

Epoch 4: loss = 3130.740319244319

 12%|█████████▉                                                                         | 6/50 [00:32<04:04,  5.55s/it]

Epoch 5: loss = 2166.837835191566

 14%|███████████▌                                                                       | 7/50 [00:38<03:59,  5.57s/it]

Epoch 6: loss = 1593.092315562407

 16%|█████████████▎                                                                     | 8/50 [00:44<03:57,  5.65s/it]

Epoch 7: loss = 1230.0678286168045

 18%|██████████████▉                                                                    | 9/50 [00:50<03:54,  5.73s/it]

Epoch 8: loss = 989.0658657483173

 20%|████████████████▍                                                                 | 10/50 [00:55<03:48,  5.70s/it]

Epoch 9: loss = 822.8116342314829

 22%|██████████████████                                                                | 11/50 [01:01<03:41,  5.69s/it]

Epoch 10: loss = 704.2627842733666

 24%|███████████████████▋                                                              | 12/50 [01:07<03:38,  5.76s/it]

Epoch 11: loss = 617.3290045181886

 26%|█████████████████████▎                                                            | 13/50 [01:13<03:32,  5.74s/it]

Epoch 12: loss = 551.9230869206496

 28%|██████████████████████▉                                                           | 14/50 [01:18<03:26,  5.75s/it]

Epoch 13: loss = 501.6851675469813

 30%|████████████████████████▌                                                         | 15/50 [01:24<03:21,  5.75s/it]

Epoch 14: loss = 462.33643700927877

 32%|██████████████████████████▏                                                       | 16/50 [01:30<03:15,  5.74s/it]

Epoch 15: loss = 430.99575635520137

 34%|███████████████████████████▉                                                      | 17/50 [01:35<03:09,  5.73s/it]

Epoch 16: loss = 405.6706194943205

 36%|█████████████████████████████▌                                                    | 18/50 [01:41<03:02,  5.72s/it]

Epoch 17: loss = 384.9149191497306

 38%|███████████████████████████████▏                                                  | 19/50 [01:47<03:00,  5.83s/it]

Epoch 18: loss = 367.7044976094272

 40%|████████████████████████████████▊                                                 | 20/50 [01:53<02:52,  5.76s/it]

Epoch 19: loss = 353.28185166587366

 42%|██████████████████████████████████▍                                               | 21/50 [01:58<02:46,  5.73s/it]

Epoch 20: loss = 341.0822354600868

 44%|████████████████████████████████████                                              | 22/50 [02:04<02:38,  5.66s/it]

Epoch 21: loss = 330.6705624440661

 46%|█████████████████████████████████████▋                                            | 23/50 [02:10<02:32,  5.64s/it]

Epoch 22: loss = 321.72657802931934

 48%|███████████████████████████████████████▎                                          | 24/50 [02:15<02:25,  5.60s/it]

Epoch 23: loss = 313.95687734517367

 50%|█████████████████████████████████████████                                         | 25/50 [02:21<02:20,  5.60s/it]

Epoch 24: loss = 307.19211012640795

 52%|██████████████████████████████████████████▋                                       | 26/50 [02:26<02:14,  5.59s/it]

Epoch 25: loss = 301.2604777048548

 54%|████████████████████████████████████████████▎                                     | 27/50 [02:32<02:07,  5.56s/it]

Epoch 26: loss = 296.00734300839576

 56%|█████████████████████████████████████████████▉                                    | 28/50 [02:37<02:01,  5.53s/it]

Epoch 27: loss = 291.34063501956683

 58%|███████████████████████████████████████████████▌                                  | 29/50 [02:43<01:57,  5.59s/it]

Epoch 28: loss = 287.17601708848855

 60%|█████████████████████████████████████████████████▏                                | 30/50 [02:49<01:52,  5.62s/it]

Epoch 29: loss = 283.4390711988484

 62%|██████████████████████████████████████████████████▊                               | 31/50 [02:55<01:50,  5.80s/it]

Epoch 30: loss = 280.070472868758

 64%|████████████████████████████████████████████████████▍                             | 32/50 [03:01<01:45,  5.87s/it]

Epoch 31: loss = 277.0196742243288

 66%|██████████████████████████████████████████████████████                            | 33/50 [03:07<01:40,  5.90s/it]

Epoch 32: loss = 274.2351481120032

 68%|███████████████████████████████████████████████████████▊                          | 34/50 [03:13<01:33,  5.82s/it]

Epoch 33: loss = 271.71101995749564

 70%|█████████████████████████████████████████████████████████▍                        | 35/50 [03:18<01:27,  5.82s/it]

Epoch 34: loss = 269.3811711245332

 72%|███████████████████████████████████████████████████████████                       | 36/50 [03:24<01:19,  5.71s/it]

Epoch 35: loss = 267.24548416493667

 74%|████████████████████████████████████████████████████████████▋                     | 37/50 [03:29<01:13,  5.62s/it]

Epoch 36: loss = 265.2731723065847

 76%|██████████████████████████████████████████████████████████████▎                   | 38/50 [03:35<01:06,  5.55s/it]

Epoch 37: loss = 263.4449758987562

 78%|███████████████████████████████████████████████████████████████▉                  | 39/50 [03:40<01:00,  5.52s/it]

Epoch 38: loss = 261.7379742238577

 80%|█████████████████████████████████████████████████████████████████▌                | 40/50 [03:46<00:55,  5.55s/it]

Epoch 39: loss = 260.1577936423369

 82%|███████████████████████████████████████████████████████████████████▏              | 41/50 [03:51<00:49,  5.55s/it]

Epoch 40: loss = 258.66441580129253

 84%|████████████████████████████████████████████████████████████████████▉             | 42/50 [03:57<00:43,  5.49s/it]

Epoch 41: loss = 257.2691088482919

 86%|██████████████████████████████████████████████████████████████████████▌           | 43/50 [04:02<00:38,  5.46s/it]

Epoch 42: loss = 255.96264211409002

 88%|████████████████████████████████████████████████████████████████████████▏         | 44/50 [04:07<00:32,  5.45s/it]

Epoch 43: loss = 254.7253872132461

 90%|█████████████████████████████████████████████████████████████████████████▊        | 45/50 [04:13<00:27,  5.45s/it]

Epoch 44: loss = 253.55349061255595

 92%|███████████████████████████████████████████████████████████████████████████▍      | 46/50 [04:18<00:21,  5.45s/it]

Epoch 45: loss = 252.44601757998097

 94%|█████████████████████████████████████████████████████████████████████████████     | 47/50 [04:24<00:16,  5.42s/it]

Epoch 46: loss = 251.39766611333482

 96%|██████████████████████████████████████████████████████████████████████████████▋   | 48/50 [04:29<00:10,  5.45s/it]

Epoch 47: loss = 250.39423240524505

 98%|████████████████████████████████████████████████████████████████████████████████▎ | 49/50 [04:35<00:05,  5.58s/it]

Epoch 48: loss = 249.44222474789152

100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [04:41<00:00,  5.62s/it]

Epoch 49: loss = 248.53231380059626
glove_emb_cfg1_ST20: GLOVE EMB CALCULATED
glove_emb_cfg2_quant100

glove_emb_cfg2_quant100: DATA DISCRETIZED
['amount_rur', 'small_group', 'trans_date']
train started

  2%|█▋                                                                                 | 1/50 [00:07<06:05,  7.47s/it]

Epoch 0: loss = 8803.779165444847

  4%|███▎                                                                               | 2/50 [00:14<05:43,  7.16s/it]

Epoch 1: loss = 4132.193509238736

  6%|████▉                                                                              | 3/50 [00:21<05:33,  7.11s/it]

Epoch 2: loss = 2442.645677641209

  8%|██████▋                                                                            | 4/50 [00:28<05:29,  7.17s/it]

Epoch 3: loss = 1554.894809493102

 10%|████████▎                                                                          | 5/50 [00:35<05:20,  7.12s/it]

Epoch 4: loss = 1051.5658121739823

 12%|█████████▉                                                                         | 6/50 [00:43<05:17,  7.21s/it]

Epoch 5: loss = 749.3780188004965

 14%|███████████▌                                                                       | 7/50 [00:50<05:15,  7.34s/it]

Epoch 6: loss = 557.8515179004612

 16%|█████████████▎                                                                     | 8/50 [00:58<05:11,  7.41s/it]

Epoch 7: loss = 430.89224546290427

 18%|██████████████▉                                                                    | 9/50 [01:05<04:59,  7.30s/it]

Epoch 8: loss = 343.2431901932915

 20%|████████████████▍                                                                 | 10/50 [01:12<04:50,  7.27s/it]

Epoch 9: loss = 280.6406932500763

 22%|██████████████████                                                                | 11/50 [01:19<04:41,  7.21s/it]

Epoch 10: loss = 234.6503742893439

 24%|███████████████████▋                                                              | 12/50 [01:26<04:35,  7.24s/it]

Epoch 11: loss = 199.99934897961492

 26%|█████████████████████▎                                                            | 13/50 [01:34<04:28,  7.26s/it]

Epoch 12: loss = 173.27047611709392

 28%|██████████████████████▉                                                           | 14/50 [01:41<04:21,  7.26s/it]

Epoch 13: loss = 152.23635733907952

 30%|████████████████████████▌                                                         | 15/50 [01:48<04:12,  7.21s/it]

Epoch 14: loss = 135.39484573131608

 32%|██████████████████████████▏                                                       | 16/50 [01:55<04:06,  7.26s/it]

Epoch 15: loss = 121.69014935418183

 34%|███████████████████████████▉                                                      | 17/50 [02:03<03:59,  7.27s/it]

Epoch 16: loss = 110.375729253061

 36%|█████████████████████████████▌                                                    | 18/50 [02:10<03:50,  7.20s/it]

Epoch 17: loss = 100.92112846549314

 38%|███████████████████████████████▏                                                  | 19/50 [02:17<03:42,  7.19s/it]

Epoch 18: loss = 92.92711942794304

 40%|████████████████████████████████▊                                                 | 20/50 [02:24<03:34,  7.15s/it]

Epoch 19: loss = 86.09350313577367

 42%|██████████████████████████████████▍                                               | 21/50 [02:31<03:26,  7.11s/it]

Epoch 20: loss = 80.21158425639462

 44%|████████████████████████████████████                                              | 22/50 [02:38<03:18,  7.11s/it]

Epoch 21: loss = 75.10355252743811

 46%|█████████████████████████████████████▋                                            | 23/50 [02:45<03:10,  7.07s/it]

Epoch 22: loss = 70.637888190313

 48%|███████████████████████████████████████▎                                          | 24/50 [02:52<03:04,  7.08s/it]

Epoch 23: loss = 66.70858947061917

 50%|█████████████████████████████████████████                                         | 25/50 [03:00<02:58,  7.16s/it]

Epoch 24: loss = 63.228804542038084

 52%|██████████████████████████████████████████▋                                       | 26/50 [03:07<02:51,  7.16s/it]

Epoch 25: loss = 60.133047717175266

 54%|████████████████████████████████████████████▎                                     | 27/50 [03:14<02:44,  7.16s/it]

Epoch 26: loss = 57.36370253831654

 56%|█████████████████████████████████████████████▉                                    | 28/50 [03:21<02:37,  7.16s/it]

Epoch 27: loss = 54.8793122344215

 58%|███████████████████████████████████████████████▌                                  | 29/50 [03:28<02:30,  7.16s/it]

Epoch 28: loss = 52.63813461293373

 60%|█████████████████████████████████████████████████▏                                | 30/50 [03:36<02:23,  7.19s/it]

Epoch 29: loss = 50.610354272318965

 62%|██████████████████████████████████████████████████▊                               | 31/50 [03:43<02:16,  7.19s/it]

Epoch 30: loss = 48.76901016762949

 64%|████████████████████████████████████████████████████▍                             | 32/50 [03:50<02:08,  7.15s/it]

Epoch 31: loss = 47.09451640121692

 66%|██████████████████████████████████████████████████████                            | 33/50 [03:57<02:00,  7.11s/it]

Epoch 32: loss = 45.564370391878754

 68%|███████████████████████████████████████████████████████▊                          | 34/50 [04:04<01:53,  7.11s/it]

Epoch 33: loss = 44.15806867128151

 70%|█████████████████████████████████████████████████████████▍                        | 35/50 [04:11<01:47,  7.18s/it]

Epoch 34: loss = 42.869675242343874

 72%|███████████████████████████████████████████████████████████                       | 36/50 [04:19<01:42,  7.29s/it]

Epoch 35: loss = 41.68418882501023

 74%|████████████████████████████████████████████████████████████▋                     | 37/50 [04:26<01:36,  7.42s/it]

Epoch 36: loss = 40.590307067670736

 76%|██████████████████████████████████████████████████████████████▎                   | 38/50 [04:34<01:31,  7.59s/it]

Epoch 37: loss = 39.57812190224689

 78%|███████████████████████████████████████████████████████████████▉                  | 39/50 [04:42<01:22,  7.50s/it]

Epoch 38: loss = 38.64233088358612

 80%|█████████████████████████████████████████████████████████████████▌                | 40/50 [04:49<01:13,  7.37s/it]

Epoch 39: loss = 37.772410325647776

 82%|███████████████████████████████████████████████████████████████████▏              | 41/50 [04:56<01:05,  7.26s/it]

Epoch 40: loss = 36.963959152711176

 84%|████████████████████████████████████████████████████████████████████▉             | 42/50 [05:03<00:58,  7.25s/it]

Epoch 41: loss = 36.210246562816714

 86%|██████████████████████████████████████████████████████████████████████▌           | 43/50 [05:10<00:50,  7.21s/it]

Epoch 42: loss = 35.50668742954192

 88%|████████████████████████████████████████████████████████████████████████▏         | 44/50 [05:17<00:43,  7.22s/it]

Epoch 43: loss = 34.84841765336683

 90%|█████████████████████████████████████████████████████████████████████████▊        | 45/50 [05:25<00:36,  7.26s/it]

Epoch 44: loss = 34.23491742992648

 92%|███████████████████████████████████████████████████████████████████████████▍      | 46/50 [05:32<00:29,  7.26s/it]

Epoch 45: loss = 33.65636305930475

 94%|█████████████████████████████████████████████████████████████████████████████     | 47/50 [05:39<00:21,  7.24s/it]

Epoch 46: loss = 33.116079378664494

 96%|██████████████████████████████████████████████████████████████████████████████▋   | 48/50 [05:47<00:14,  7.28s/it]

Epoch 47: loss = 32.604976157339195

 98%|████████████████████████████████████████████████████████████████████████████████▎ | 49/50 [05:54<00:07,  7.32s/it]

Epoch 48: loss = 32.12543574795644

100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [06:01<00:00,  7.24s/it]

Epoch 49: loss = 31.676171782024362
glove_emb_cfg2_quant100: GLOVE EMB CALCULATED
glove_emb_cfg3_quant100

glove_emb_cfg3_quant100: DATA DISCRETIZED
['amount_rur', 'small_group', 'trans_date']
train started

  2%|█▋                                                                                 | 1/50 [00:06<05:41,  6.97s/it]

Epoch 0: loss = 4832.890940534716

  4%|███▎                                                                               | 2/50 [00:13<05:32,  6.92s/it]

Epoch 1: loss = 2671.6111575709606

  6%|████▉                                                                              | 3/50 [00:21<05:35,  7.14s/it]

Epoch 2: loss = 1798.5629731688937

  8%|██████▋                                                                            | 4/50 [00:28<05:22,  7.02s/it]

Epoch 3: loss = 1275.0497253761819

 10%|████████▎                                                                          | 5/50 [00:35<05:23,  7.18s/it]

Epoch 4: loss = 937.0012472401623

 12%|█████████▉                                                                         | 6/50 [00:42<05:18,  7.23s/it]

Epoch 5: loss = 710.1067391327342

 14%|███████████▌                                                                       | 7/50 [00:49<05:08,  7.17s/it]

Epoch 6: loss = 553.009269196101

 16%|█████████████▎                                                                     | 8/50 [00:56<04:58,  7.12s/it]

Epoch 7: loss = 441.3097964041299

 18%|██████████████▉                                                                    | 9/50 [01:03<04:48,  7.05s/it]

Epoch 8: loss = 359.9872042501453

 20%|████████████████▍                                                                 | 10/50 [01:10<04:40,  7.01s/it]

Epoch 9: loss = 299.5812672375256

 22%|██████████████████                                                                | 11/50 [01:18<04:36,  7.10s/it]

Epoch 10: loss = 253.69712313484462

 24%|███████████████████▋                                                              | 12/50 [01:25<04:33,  7.20s/it]

Epoch 11: loss = 218.23282887431074

 26%|█████████████████████▎                                                            | 13/50 [01:32<04:26,  7.20s/it]

Epoch 12: loss = 190.30988309597112

 28%|██████████████████████▉                                                           | 14/50 [01:39<04:17,  7.16s/it]

Epoch 13: loss = 167.94807193479738

 30%|████████████████████████▌                                                         | 15/50 [01:46<04:07,  7.07s/it]

Epoch 14: loss = 149.76572287089826

 32%|██████████████████████████▏                                                       | 16/50 [01:53<04:02,  7.14s/it]

Epoch 15: loss = 134.8029634812402

 34%|███████████████████████████▉                                                      | 17/50 [02:01<03:55,  7.15s/it]

Epoch 16: loss = 122.32300709163165

 36%|█████████████████████████████▌                                                    | 18/50 [02:09<03:57,  7.41s/it]

Epoch 17: loss = 111.78538806933572

 38%|███████████████████████████████▏                                                  | 19/50 [02:17<03:54,  7.57s/it]

Epoch 18: loss = 102.7926951760369

 40%|████████████████████████████████▊                                                 | 20/50 [02:24<03:46,  7.55s/it]

Epoch 19: loss = 95.04880502926662

 42%|██████████████████████████████████▍                                               | 21/50 [02:32<03:40,  7.60s/it]

Epoch 20: loss = 88.32300813743237

 44%|████████████████████████████████████                                              | 22/50 [02:39<03:31,  7.57s/it]

Epoch 21: loss = 82.42806043495294

 46%|█████████████████████████████████████▋                                            | 23/50 [02:47<03:24,  7.56s/it]

Epoch 22: loss = 77.23093371151705

 48%|███████████████████████████████████████▎                                          | 24/50 [02:54<03:14,  7.48s/it]

Epoch 23: loss = 72.61361760684164

 50%|█████████████████████████████████████████                                         | 25/50 [03:01<03:05,  7.43s/it]

Epoch 24: loss = 68.48528865494785

 52%|██████████████████████████████████████████▋                                       | 26/50 [03:09<02:57,  7.38s/it]

Epoch 25: loss = 64.78039855482147

 54%|████████████████████████████████████████████▎                                     | 27/50 [03:16<02:49,  7.38s/it]

Epoch 26: loss = 61.43302683300083

 56%|█████████████████████████████████████████████▉                                    | 28/50 [03:23<02:40,  7.27s/it]

Epoch 27: loss = 58.396967409330436

 58%|███████████████████████████████████████████████▌                                  | 29/50 [03:30<02:31,  7.22s/it]

Epoch 28: loss = 55.634507105410705

 60%|█████████████████████████████████████████████████▏                                | 30/50 [03:37<02:24,  7.22s/it]

Epoch 29: loss = 53.10895724386073

 62%|██████████████████████████████████████████████████▊                               | 31/50 [03:45<02:16,  7.20s/it]

Epoch 30: loss = 50.79111266173496

 64%|████████████████████████████████████████████████████▍                             | 32/50 [03:52<02:10,  7.27s/it]

Epoch 31: loss = 48.656520904881965

 66%|██████████████████████████████████████████████████████                            | 33/50 [03:59<02:03,  7.28s/it]

Epoch 32: loss = 46.68673018178318

 68%|███████████████████████████████████████████████████████▊                          | 34/50 [04:07<01:56,  7.28s/it]

Epoch 33: loss = 44.862211484247595

 70%|█████████████████████████████████████████████████████████▍                        | 35/50 [04:14<01:47,  7.18s/it]

Epoch 34: loss = 43.17288680437535

 72%|███████████████████████████████████████████████████████████                       | 36/50 [04:21<01:41,  7.24s/it]

Epoch 35: loss = 41.601892999792625

 74%|████████████████████████████████████████████████████████████▋                     | 37/50 [04:28<01:34,  7.30s/it]

Epoch 36: loss = 40.13711929427047

 76%|██████████████████████████████████████████████████████████████▎                   | 38/50 [04:36<01:27,  7.27s/it]

Epoch 37: loss = 38.76744408424795

 78%|███████████████████████████████████████████████████████████████▉                  | 39/50 [04:43<01:18,  7.18s/it]

Epoch 38: loss = 37.48687198936877

 80%|█████████████████████████████████████████████████████████████████▌                | 40/50 [04:50<01:12,  7.23s/it]

Epoch 39: loss = 36.28594435421819

 82%|███████████████████████████████████████████████████████████████████▏              | 41/50 [04:57<01:06,  7.34s/it]

Epoch 40: loss = 35.1603660416706

 84%|████████████████████████████████████████████████████████████████████▉             | 42/50 [05:05<00:58,  7.33s/it]

Epoch 41: loss = 34.100402566048466

 86%|██████████████████████████████████████████████████████████████████████▌           | 43/50 [05:12<00:50,  7.25s/it]

Epoch 42: loss = 33.10055891633562

 88%|████████████████████████████████████████████████████████████████████████▏         | 44/50 [05:19<00:43,  7.23s/it]

Epoch 43: loss = 32.16024618428197

 90%|█████████████████████████████████████████████████████████████████████████▊        | 45/50 [05:26<00:36,  7.24s/it]

Epoch 44: loss = 31.271066357798293

 92%|███████████████████████████████████████████████████████████████████████████▍      | 46/50 [05:33<00:28,  7.22s/it]

Epoch 45: loss = 30.42985236161666

 94%|█████████████████████████████████████████████████████████████████████████████     | 47/50 [05:41<00:21,  7.20s/it]

Epoch 46: loss = 29.63366026875979

 96%|██████████████████████████████████████████████████████████████████████████████▋   | 48/50 [05:48<00:14,  7.23s/it]

Epoch 47: loss = 28.88061144207722

 98%|████████████████████████████████████████████████████████████████████████████████▎ | 49/50 [05:55<00:07,  7.28s/it]

Epoch 48: loss = 28.16411387665407

100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [06:02<00:00,  7.26s/it]

Epoch 49: loss = 27.483235386743104
glove_emb_cfg3_quant100: GLOVE EMB CALCULATED
glove_emb_cfg2_deeptlf9

Counter({'small_group': 153, 'amount_rur': 62})
glove_emb_cfg2_deeptlf9: DATA DISCRETIZED
['amount_rur', 'small_group', 'trans_date']
train started

  2%|█▋                                                                                 | 1/50 [00:06<04:55,  6.02s/it]

Epoch 0: loss = 8874.665745044562

  4%|███▎                                                                               | 2/50 [00:12<04:49,  6.03s/it]

Epoch 1: loss = 4219.116084718003

  6%|████▉                                                                              | 3/50 [00:18<04:45,  6.06s/it]

Epoch 2: loss = 2520.219624727917

  8%|██████▋                                                                            | 4/50 [00:24<04:40,  6.09s/it]

Epoch 3: loss = 1624.6113208249587

 10%|████████▎                                                                          | 5/50 [00:30<04:32,  6.06s/it]

Epoch 4: loss = 1111.4770484074013

 12%|█████████▉                                                                         | 6/50 [00:36<04:24,  6.01s/it]

Epoch 5: loss = 798.3401790460972

 14%|███████████▌                                                                       | 7/50 [00:42<04:18,  6.00s/it]

Epoch 6: loss = 596.0779913926998

 16%|█████████████▎                                                                     | 8/50 [00:48<04:12,  6.00s/it]

Epoch 7: loss = 458.6807096955746

 18%|██████████████▉                                                                    | 9/50 [00:54<04:05,  5.99s/it]

Epoch 8: loss = 361.8757400160492

 20%|████████████████▍                                                                 | 10/50 [01:00<04:02,  6.05s/it]

Epoch 9: loss = 291.6041363879876

 22%|██████████████████                                                                | 11/50 [01:06<03:57,  6.08s/it]

Epoch 10: loss = 239.38086097355875

 24%|███████████████████▋                                                              | 12/50 [01:12<03:51,  6.10s/it]

Epoch 11: loss = 199.7576460053637

 26%|█████████████████████▎                                                            | 13/50 [01:18<03:46,  6.13s/it]

Epoch 12: loss = 169.2264332727975

 28%|██████████████████████▉                                                           | 14/50 [01:24<03:39,  6.11s/it]

Epoch 13: loss = 145.35024931286392

 30%|████████████████████████▌                                                         | 15/50 [01:31<03:34,  6.12s/it]

Epoch 14: loss = 126.43641951781503

 32%|██████████████████████████▏                                                       | 16/50 [01:37<03:27,  6.10s/it]

Epoch 15: loss = 111.28215436050876

 34%|███████████████████████████▉                                                      | 17/50 [01:43<03:21,  6.12s/it]

Epoch 16: loss = 99.00227275999299

 36%|█████████████████████████████▌                                                    | 18/50 [01:49<03:16,  6.13s/it]

Epoch 17: loss = 88.95173154128172

 38%|███████████████████████████████▏                                                  | 19/50 [01:55<03:10,  6.13s/it]

Epoch 18: loss = 80.6576047224855

 40%|████████████████████████████████▊                                                 | 20/50 [02:01<03:05,  6.18s/it]

Epoch 19: loss = 73.74496837857747

 42%|██████████████████████████████████▍                                               | 21/50 [02:07<02:58,  6.15s/it]

Epoch 20: loss = 67.94567225430963

 44%|████████████████████████████████████                                              | 22/50 [02:14<02:52,  6.16s/it]

Epoch 21: loss = 63.03307061624819

 46%|█████████████████████████████████████▋                                            | 23/50 [02:20<02:46,  6.16s/it]

Epoch 22: loss = 58.853606855901425

 48%|███████████████████████████████████████▎                                          | 24/50 [02:26<02:39,  6.12s/it]

Epoch 23: loss = 55.26736200646132

 50%|█████████████████████████████████████████                                         | 25/50 [02:32<02:33,  6.12s/it]

Epoch 24: loss = 52.17157035920506

 52%|██████████████████████████████████████████▋                                       | 26/50 [02:38<02:26,  6.10s/it]

Epoch 25: loss = 49.4825726408061

 54%|████████████████████████████████████████████▎                                     | 27/50 [02:44<02:21,  6.14s/it]

Epoch 26: loss = 47.13510847933204

 56%|█████████████████████████████████████████████▉                                    | 28/50 [02:50<02:15,  6.14s/it]

Epoch 27: loss = 45.076226262524

 58%|███████████████████████████████████████████████▌                                  | 29/50 [02:57<02:09,  6.17s/it]

Epoch 28: loss = 43.25919698344228

 60%|█████████████████████████████████████████████████▏                                | 30/50 [03:03<02:03,  6.16s/it]

Epoch 29: loss = 41.65096305191819

 62%|██████████████████████████████████████████████████▊                               | 31/50 [03:09<01:56,  6.14s/it]

Epoch 30: loss = 40.217989364728375

 64%|████████████████████████████████████████████████████▍                             | 32/50 [03:15<01:50,  6.16s/it]

Epoch 31: loss = 38.93833504762732

 66%|██████████████████████████████████████████████████████                            | 33/50 [03:21<01:46,  6.25s/it]

Epoch 32: loss = 37.7861368636884

 68%|███████████████████████████████████████████████████████▊                          | 34/50 [03:28<01:43,  6.45s/it]

Epoch 33: loss = 36.750013653779156

 70%|█████████████████████████████████████████████████████████▍                        | 35/50 [03:35<01:36,  6.46s/it]

Epoch 34: loss = 35.81182061168888

 72%|███████████████████████████████████████████████████████████                       | 36/50 [03:41<01:30,  6.45s/it]

Epoch 35: loss = 34.96027880573844

 74%|████████████████████████████████████████████████████████████▋                     | 37/50 [03:48<01:24,  6.48s/it]

Epoch 36: loss = 34.18458076652041

 76%|██████████████████████████████████████████████████████████████▎                   | 38/50 [03:54<01:16,  6.39s/it]

Epoch 37: loss = 33.47386711077673

 78%|███████████████████████████████████████████████████████████████▉                  | 39/50 [04:00<01:09,  6.31s/it]

Epoch 38: loss = 32.823337645409495

 80%|█████████████████████████████████████████████████████████████████▌                | 40/50 [04:07<01:03,  6.38s/it]

Epoch 39: loss = 32.22544386039267

 82%|███████████████████████████████████████████████████████████████████▏              | 41/50 [04:13<00:57,  6.41s/it]

Epoch 40: loss = 31.672968208246882

 84%|████████████████████████████████████████████████████████████████████▉             | 42/50 [04:19<00:50,  6.36s/it]

Epoch 41: loss = 31.16215798998935

 86%|██████████████████████████████████████████████████████████████████████▌           | 43/50 [04:26<00:44,  6.40s/it]

Epoch 42: loss = 30.687919136940884

 88%|████████████████████████████████████████████████████████████████████████▏         | 44/50 [04:32<00:38,  6.39s/it]

Epoch 43: loss = 30.247169284936398

 90%|█████████████████████████████████████████████████████████████████████████▊        | 45/50 [04:39<00:31,  6.38s/it]

Epoch 44: loss = 29.83628292603187

 92%|███████████████████████████████████████████████████████████████████████████▍      | 46/50 [04:45<00:25,  6.39s/it]

Epoch 45: loss = 29.45155182085302

 94%|█████████████████████████████████████████████████████████████████████████████     | 47/50 [04:52<00:19,  6.43s/it]

Epoch 46: loss = 29.094300559436242

 96%|██████████████████████████████████████████████████████████████████████████████▋   | 48/50 [04:58<00:12,  6.43s/it]

Epoch 47: loss = 28.755994844257184

 98%|████████████████████████████████████████████████████████████████████████████████▎ | 49/50 [05:05<00:06,  6.49s/it]

Epoch 48: loss = 28.43980582491683

100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [05:11<00:00,  6.23s/it]

Epoch 49: loss = 28.138898523117835
glove_emb_cfg2_deeptlf9: GLOVE EMB CALCULATED

In [15]:
glove_embedding.load()

In [9]:
data = glove_embedding.tokenize_data(data)

In [4]:
EMBED_SIZE = 16
disc_quant100 = KDiscretizer(
    f_names = ['amount_rur'],
    k_bins = 100,
    d_type = 'quantile'
)

disc_uni100 = KDiscretizer(
    f_names = ['amount_rur'],
    k_bins = 100,
    d_type = 'uniform'
)

disc_kmeans100 = KDiscretizer(
    f_names = ['amount_rur'],
    k_bins = 100,
    d_type = 'kmeans'
)

disc_st100 = SingleTreeDiscretizer(
    f_names = ['amount_rur'], 
    target_name = 'bins', 
    target_type = 'classification', 
    k_bins = [100],
)

disc_quant30 = KDiscretizer(
    f_names = ['amount_rur'],
    k_bins = 30,
    d_type = 'quantile',
    emb_sz = EMBED_SIZE
)

disc_uni30 = KDiscretizer(
    f_names = ['amount_rur'],
    k_bins = 30,
    d_type = 'uniform',
    emb_sz = EMBED_SIZE
)

disc_kmeans30 = KDiscretizer(
    f_names = ['amount_rur'],
    k_bins = 30,
    d_type = 'kmeans',
    emb_sz = EMBED_SIZE
)

disc_st30 = SingleTreeDiscretizer(
    f_names = ['amount_rur'], 
    target_name = 'bins', 
    target_type = 'classification', 
    k_bins = [30],
    emb_sz = EMBED_SIZE
)

In [5]:
experiments = [
    {'name' : 'quant_num_emb_dist_common_emb_cat', 
     'agg_type' : 'cat', 
     'disc' : disc_quant30,
     'nemb' : True
    },
    {'name' : 'quant_num_emb_dist_common_emb_sum', 
     'agg_type' : 'sum', 
     'disc' : disc_quant30,
     'nemb' : True
    },
    {'name' : 'quant_num_emb_dist_common_emb_mean', 
     'agg_type' : 'mean', 
     'disc' : disc_quant30,
     'nemb' : True
    },
    {'name' : 'uni_num_emb_dist_common_emb_cat', 
     'agg_type' : 'cat', 
     'disc' : disc_uni30,
     'nemb' : True
    },
    {'name' : 'uni_num_emb_dist_common_emb_sum', 
     'agg_type' : 'sum', 
     'disc' : disc_uni30,
     'nemb' : True
    },
    {'name' : 'uni_num_emb_dist_common_emb_mean', 
     'agg_type' : 'mean', 
     'disc' : disc_uni30,
     'nemb' : True
    },
    {'name' : 'kmeans_num_emb_dist_common_emb_cat', 
     'agg_type' : 'cat', 
     'disc' : disc_kmeans30,
     'nemb' : True
    },
    {'name' : 'kmeans_num_emb_dist_common_emb_sum', 
     'agg_type' : 'sum', 
     'disc' : disc_kmeans30,
     'nemb' : True
    },
    {'name' : 'kmeans_num_emb_dist_common_emb_mean', 
     'agg_type' : 'mean', 
     'disc' : disc_kmeans30,
     'nemb' : True
    },
    {'name' : 'st_num_emb_dist_common_emb_cat', 
     'agg_type' : 'cat', 
     'disc' : disc_st30,
     'nemb' : True
    },
    {'name' : 'st_num_emb_dist_common_emb_sum', 
     'agg_type' : 'sum', 
     'disc' : disc_st30,
     'nemb' : True
    },
    {'name' : 'st_num_emb_dist_common_emb_mean', 
     'agg_type' : 'mean', 
     'disc' : disc_st30,
     'nemb' : True
    },
    {'name' : 'st_100_dist_common_emb_cat', 
     'agg_type' : 'cat', 
     'disc' : disc_st100,
     'nemb' : False
    },
    {'name' : 'st_100_dist_common_emb_sum', 
     'agg_type' : 'sum', 
     'disc' : disc_st100,
     'nemb' : False
    },
    {'name' : 'st_100_dist_common_emb_mean', 
     'agg_type' : 'mean', 
     'disc' : disc_st100,
     'nemb' : False
    },
    {'name' : 'quant_100_dist_common_emb_cat', 
     'agg_type' : 'cat', 
     'disc' : disc_quant100,
     'nemb' : False
    },
    {'name' : 'quant_100_dist_common_emb_sum', 
     'agg_type' : 'sum', 
     'disc' : disc_quant100,
     'nemb' : False
    },
    {'name' : 'quant_100_dist_common_emb_mean', 
     'agg_type' : 'mean', 
     'disc' : disc_quant100,
     'nemb' : False
    },
    {'name' : 'uni_100_dist_common_emb_cat', 
     'agg_type' : 'cat', 
     'disc' : disc_uni100,
     'nemb' : False
    },
    {'name' : 'uni_100_dist_common_emb_sum', 
     'agg_type' : 'sum', 
     'disc' : disc_uni100,
     'nemb' : False
    },
    {'name' : 'uni_100_dist_common_emb_mean', 
     'agg_type' : 'mean', 
     'disc' : disc_uni100,
     'nemb' : False
    },
    {'name' : 'kmeans_100_dist_common_emb_cat', 
     'agg_type' : 'cat', 
     'disc' : disc_kmeans100,
     'nemb' : False
    },
    {'name' : 'kmeans_100_dist_common_emb_sum', 
     'agg_type' : 'sum', 
     'disc' : disc_kmeans100,
     'nemb' : False
    },
    {'name' : 'kmeans_100_dist_common_emb_mean', 
     'agg_type' : 'mean', 
     'disc' : disc_kmeans100,
     'nemb' : False
    },
]

In [ ]:
#Deeptfl only disc
EMBED_SIZE = 16
df_params = {'numeric_cols': ['amount_rur'],
     'cat_cols': ['small_group'],
     'date_col': 'trans_date',
     'cat_unique': [202, 730],
     'id_col': 'client_id'}

deeptlf_params3 = DeepTLFDisc({"n_est" : 3,
                  "min_freq" : 2,
                  "features" : df_params['numeric_cols'] + df_params['cat_cols'],
                  "features_to_split" : df_params['numeric_cols']
                  })
deeptlf_params6 = DeepTLFDisc({"n_est" : 6,
                  "min_freq" : 2,
                  "features" : df_params['numeric_cols'] + df_params['cat_cols'],
                  "features_to_split" : df_params['numeric_cols'],
                  })
deeptlf_params9 = DeepTLFDisc({"n_est" : 9,
                  "min_freq" : 2,
                  "features" : df_params['numeric_cols'] + df_params['cat_cols'],
                  "features_to_split" : df_params['numeric_cols'],
                  })

deeptlf_params3_ne = DeepTLFDisc({"n_est" : 3,
                  "min_freq" : 2,
                  "features" : df_params['numeric_cols'] + df_params['cat_cols'],
                  "features_to_split" : df_params['numeric_cols'],
                  "emb_size" : EMBED_SIZE})
deeptlf_params6_ne = DeepTLFDisc({"n_est" : 6,
                  "min_freq" : 2,
                  "features" : df_params['numeric_cols'] + df_params['cat_cols'],
                  "features_to_split" : df_params['numeric_cols'],
                  "emb_size" : EMBED_SIZE})
deeptlf_params9_ne = DeepTLFDisc({"n_est" : 9,
                  "min_freq" : 2,
                  "features" : df_params['numeric_cols'] + df_params['cat_cols'],
                  "features_to_split" : df_params['numeric_cols'],
                  "emb_size" : EMBED_SIZE})

experiments = [
    {'name' : 'deeptlf3_disc_common_emb_cat',
     'agg_type' : 'cat',
     'disc' : deeptlf_params3,
     'nemb' : False
    },
    {'name' : 'deeptlf6_disc_common_emb_sum',
     'agg_type' : 'sum',
     'disc' : deeptlf_params6,
     'nemb' : False
    },
    {'name' : 'deeptlf9_disc_common_emb_mean',
     'agg_type' : 'mean',
     'disc' : deeptlf_params9,
     'nemb' : False
    },
    {'name' : 'deeptlf3_num_emb_disc_common_emb_cat',
     'agg_type' : 'cat',
     'disc' : deeptlf_params3_ne,
     'nemb' : True
    },
    {'name' : 'deeptlf6_num_emb_disc_common_emb_sum',
     'agg_type' : 'sum',
     'disc' : deeptlf_params6_ne,
     'nemb' : True
    },
    {'name' : 'deeptlf9_num_emb_disc_common_emb_mean',
     'agg_type' : 'mean',
     'disc' : deeptlf_params9_ne,
     'nemb' : True
    },
]

### Experiments with sole numeric features discretization and common embeds

In [5]:
EMBED_SIZE = 16
HIDDEN_SIZE = 256

def get_cat_encoder(df_params, agg_type, num_emb_flag=False):
    embeddings=dict()
    for i, f in enumerate(df_params["cat_cols"] + [df_params["date_col"]]):
        embeddings[f] = {'in' : df_params["cat_unique"][i], 'out' : EMBED_SIZE}

    trx_encoder_params = dict(
        embeddings=embeddings,
        embeddings_noise=0.003,
        agg_type=agg_type,
        numeric_separate=num_emb_flag,
        numeric_features=df_params['numeric_cols']
    )
    
    seq_encoder = RnnSeqEncoder(
        trx_encoder=TrxEncoderCat(**trx_encoder_params),
        hidden_size=HIDDEN_SIZE,
        type='gru',
    )
    return seq_encoder

def get_trans_encoder(df_params, agg_type, numeric_separate=False):
    embeddings=dict()

    trx_encoder_params = dict(
        feature_names=df_params['cat_cols'] + [df_params["date_col"]], 
        cat_emb_sizes=df_params["cat_unique"],
        out_emb_size=EMBED_SIZE,
        agg_type=agg_type,
        numeric_separate=numeric_separate,
        numeric_features=df_params['numeric_cols']
    )
    
    seq_encoder = RnnSeqEncoder(
        trx_encoder=TrxEncoderTrans(**trx_encoder_params),
        hidden_size=HIDDEN_SIZE,
        type='gru',
    )
    return seq_encoder

def get_glove_encoder(df_params, exp, glove_embedding):
    seq_encoder = RnnSeqEncoder(
        trx_encoder=TrxEncoderGlove(glove_embedding, agg_type=exp['agg_type'], numeric_separate=exp['nsep']),
        hidden_size=256,
        type='gru',
    )
    return seq_encoder

In [5]:
experiments = [
    {
     'name' : 'trx_tran_no_num_emb_cat',
     'agg_type' : 'cat',
     'nsep' : True
    }
]

In [7]:
e

{'name': 'glove_emb_cfg1_no_num',
 'glove_config': {'alpha': 0.75,
  'x_max': 100,
  'embedding_size': 16,
  'num_epochs_train': 50},
 'disc': None}

In [6]:
experiments_glove = []
for e in experiments:
    for agg_t in ['cat', 'sum', 'mean']:
        if agg_t != 'cat' and e['disc'] is None:
            continue
        experiments_glove.append(copy.deepcopy(e))
        experiments_glove[-1]['agg_type'] = agg_t
        experiments_glove[-1]['nsep'] = (experiments_glove[-1]['disc'] is None)
        experiments_glove[-1]['name'] += f'_{agg_t}'

In [15]:
experiments_glove

[{'name': 'glove_emb_cfg1_no_num_cat',
  'glove_config': {'alpha': 0.75,
   'x_max': 100,
   'embedding_size': 16,
   'num_epochs_train': 50},
  'disc': None,
  'agg_type': 'cat',
  'nsep': True},
 {'name': 'glove_emb_cfg2_no_num_cat',
  'glove_config': {'alpha': 0.75,
   'x_max': 15000,
   'embedding_size': 16,
   'num_epochs_train': 50},
  'disc': None,
  'agg_type': 'cat',
  'nsep': True},
 {'name': 'glove_emb_cfg3_no_num_cat',
  'glove_config': {'alpha': 1.0,
   'x_max': 20000,
   'embedding_size': 16,
   'num_epochs_train': 50},
  'disc': None,
  'agg_type': 'cat',
  'nsep': True},
 {'name': 'glove_emb_cfg1_ST20_cat',
  'glove_config': {'alpha': 0.75,
   'x_max': 100,
   'embedding_size': 16,
   'num_epochs_train': 50},
  'disc': <ptls.preprocessing.baseline_discretizer.single_tree_discretizer.SingleTreeDiscretizer at 0x24d14912d70>,
  'agg_type': 'cat',
  'nsep': False},
 {'name': 'glove_emb_cfg1_ST20_sum',
  'glove_config': {'alpha': 0.75,
   'x_max': 100,
   'embedding_size': 16,
   'num_epochs_train': 50},
  'disc': <ptls.preprocessing.baseline_discretizer.single_tree_discretizer.SingleTreeDiscretizer at 0x24c8bba1450>,
  'agg_type': 'sum',
  'nsep': False},
 {'name': 'glove_emb_cfg1_ST20_mean',
  'glove_config': {'alpha': 0.75,
   'x_max': 100,
   'embedding_size': 16,
   'num_epochs_train': 50},
  'disc': <ptls.preprocessing.baseline_discretizer.single_tree_discretizer.SingleTreeDiscretizer at 0x24c8bba2140>,
  'agg_type': 'mean',
  'nsep': False},
 {'name': 'glove_emb_cfg2_quant100_cat',
  'glove_config': {'alpha': 0.75,
   'x_max': 15000,
   'embedding_size': 16,
   'num_epochs_train': 50},
  'disc': <ptls.preprocessing.baseline_discretizer.k_discretizer.KDiscretizer at 0x24c8bba1660>,
  'agg_type': 'cat',
  'nsep': False},
 {'name': 'glove_emb_cfg2_quant100_sum',
  'glove_config': {'alpha': 0.75,
   'x_max': 15000,
   'embedding_size': 16,
   'num_epochs_train': 50},
  'disc': <ptls.preprocessing.baseline_discretizer.k_discretizer.KDiscretizer at 0x24c8bba1c90>,
  'agg_type': 'sum',
  'nsep': False},
 {'name': 'glove_emb_cfg2_quant100_mean',
  'glove_config': {'alpha': 0.75,
   'x_max': 15000,
   'embedding_size': 16,
   'num_epochs_train': 50},
  'disc': <ptls.preprocessing.baseline_discretizer.k_discretizer.KDiscretizer at 0x24c8bba20b0>,
  'agg_type': 'mean',
  'nsep': False},
 {'name': 'glove_emb_cfg3_quant100_cat',
  'glove_config': {'alpha': 1.0,
   'x_max': 20000,
   'embedding_size': 16,
   'num_epochs_train': 50},
  'disc': <ptls.preprocessing.baseline_discretizer.k_discretizer.KDiscretizer at 0x24c8bba1ae0>,
  'agg_type': 'cat',
  'nsep': False},
 {'name': 'glove_emb_cfg3_quant100_sum',
  'glove_config': {'alpha': 1.0,
   'x_max': 20000,
   'embedding_size': 16,
   'num_epochs_train': 50},
  'disc': <ptls.preprocessing.baseline_discretizer.k_discretizer.KDiscretizer at 0x24c8bba1390>,
  'agg_type': 'sum',
  'nsep': False},
 {'name': 'glove_emb_cfg3_quant100_mean',
  'glove_config': {'alpha': 1.0,
   'x_max': 20000,
   'embedding_size': 16,
   'num_epochs_train': 50},
  'disc': <ptls.preprocessing.baseline_discretizer.k_discretizer.KDiscretizer at 0x24c8bba13c0>,
  'agg_type': 'mean',
  'nsep': False},
 {'name': 'glove_emb_cfg2_deeptlf9_cat',
  'glove_config': {'alpha': 0.75,
   'x_max': 15000,
   'embedding_size': 16,
   'num_epochs_train': 50},
  'disc': <ptls.preprocessing.deeptlf.deeptlf_discretizer.DeepTLFDisc at 0x24c8bba2a10>,
  'agg_type': 'cat',
  'nsep': False},
 {'name': 'glove_emb_cfg2_deeptlf9_sum',
  'glove_config': {'alpha': 0.75,
   'x_max': 15000,
   'embedding_size': 16,
   'num_epochs_train': 50},
  'disc': <ptls.preprocessing.deeptlf.deeptlf_discretizer.DeepTLFDisc at 0x24c8bba3490>,
  'agg_type': 'sum',
  'nsep': False},
 {'name': 'glove_emb_cfg2_deeptlf9_mean',
  'glove_config': {'alpha': 0.75,
   'x_max': 15000,
   'embedding_size': 16,
   'num_epochs_train': 50},
  'disc': <ptls.preprocessing.deeptlf.deeptlf_discretizer.DeepTLFDisc at 0x24c8bba1840>,
  'agg_type': 'mean',
  'nsep': False}]

In [ ]:
for exp in experiments_glove:
    df_params = {'numeric_cols': ['amount_rur'],
     'cat_cols': ['small_group'],
     'date_col': 'trans_date',
     'cat_unique': [202, 730],
     'id_col': 'client_id'}
    data = copy.deepcopy(source_data)
    if 'disc' in exp:
        disc = exp['disc']
        if exp['name'][:2] != "st" and ('ST' not in exp['name']) and (disc is not None):
            disc.fit_transform(data)
            data = disc.transform(data, to_embeds=exp['nemb'] if 'nemb' in exp else False)
        elif (disc is not None):
            disc.fit_transform(data.sample(int(1e+5), random_state=42).merge(targets, on=df_params['id_col'], how='left'))
            data = disc.transform(data, to_embeds=exp['nemb'] if 'nemb' in exp else False)
        print(f"{exp['name']}: DATA DISCRETIZED")

    if 'nemb' in exp and not exp['nemb']:
        df_params['cat_cols'] =  df_params['numeric_cols'] + df_params['cat_cols']
        df_params["cat_unique"] = (exp['disc'].k_bins if (type(exp['disc'].k_bins) is list) else [exp['disc'].k_bins] * len(df_params['numeric_cols'])) + df_params["cat_unique"]

    if 'glove_config' in exp:
        if not exp['nsep']:
            embedded_feats = df_params['numeric_cols'] + df_params['cat_cols'] + [df_params["date_col"]]
        else:
            embedded_feats = df_params['cat_cols'] + [df_params["date_col"]]
        glove_embedding = GloveEmbedding(
            feature_names=embedded_feats,
            calculate_cooccur=False,
            embedding_folder=f'../glove_embeddings/{exp["name"]}'[:-4],
            glove_params=exp['glove_config']
        )
        glove_embedding.load()
        data = glove_embedding.tokenize_data(data)

    preprocessor = PandasDataPreprocessor(
        col_id=df_params['id_col'],
        col_event_time=df_params['date_col'],
        event_time_transformation='none',
        cols_category=df_params['cat_cols'],
        cols_numerical=df_params['numeric_cols'] if ('nsep' in exp and 'nsep') else [],
        return_records=True,
    )
    
    dataset = preprocessor.fit_transform(data)

    dataset = sorted(dataset, key=lambda x: x[df_params['id_col']])

    with open(f"../coles_prep_datasets/{exp['name']}_dataset.pkl", "wb") as fl:
        pickle.dump(dataset , fl)

    with open(f"../coles_prep_datasets/{exp['name']}_dataset.pkl", "rb") as fl:
        dataset = pickle.load(fl)
    
    train, test = train_test_split(dataset, test_size=0.2, random_state=42)

    train, val = train_test_split(dataset, test_size=0.1, random_state=42)


    print(f"{exp['name']}: DATA PREPROCESSED AND SAVED")

    del dataset, data

    train_dl = PtlsDataModule(
        train_data = ColesDataset(
                MemoryMapDataset(
                    data=train,
                    i_filters=[
                        SeqLenFilter(min_seq_len=25),
                    ],
                ),
                splitter=SampleSlices(
                    split_count=5,
                    cnt_min=25,
                    cnt_max=200,
                ),
            ),
        train_num_workers=1,
        train_batch_size=256,
        valid_data = ColesDataset(
                MemoryMapDataset(
                    data=val,
                    i_filters=[
                        SeqLenFilter(min_seq_len=25),
                    ],
                ),
                splitter=SampleSlices(
                    split_count=5,
                    cnt_min=25,
                    cnt_max=200,
                ),
            ),
        valid_num_workers=1,
        valid_batch_size=256,
    )

    #seq_encoder = get_cat_encoder(df_params, agg_type=exp['agg_type'], num_emb_flag=exp['nemb'])
    #seq_encoder = get_trans_encoder(df_params, agg_type=exp['agg_type'], numeric_separate=exp['nsep'])
    seq_encoder = get_glove_encoder(df_params, exp, glove_embedding)

    model = CoLESModule(
        seq_encoder=seq_encoder,
        optimizer_partial=partial(torch.optim.Adam, lr=0.001),
        lr_scheduler_partial=partial(torch.optim.lr_scheduler.StepLR, step_size=30, gamma=0.9),
    )

    early_stopping = EarlyStopping(f'valid/{model.metric_name}', mode='max', patience=2, min_delta=0.01)
    
    trainer = pl.Trainer(
        max_epochs=25,
        accelerator="gpu",
        callbacks = [early_stopping],
        enable_progress_bar=True,
        enable_model_summary=False,
        logger=False
    )

    print(f"{exp['name']}: TRAIN STARTS")

    trainer.fit(model, train_dl)
    print(trainer.logged_metrics)

    torch.save(seq_encoder.state_dict(), f"../models_coles/{exp['name']}_emb.pt")

    print(f"{exp['name']}: TRAIN ENDS, MODEL SAVED")

    del train, test

glove_emb_cfg1_no_num_cat: DATA DISCRETIZED

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs

glove_emb_cfg1_no_num_cat: DATA PREPROCESSED AND SAVED
glove_emb_cfg1_no_num_cat: TRAIN STARTS

C:\Users\peter\anaconda3\envs\cv\lib\site-packages\pytorch_lightning\callbacks\model_checkpoint.py:613: UserWarning: Checkpoint directory C:\Users\peter\anaconda3\envs\cv\Scripts\ptls-glove\checkpoints exists and is not empty.
  rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Sanity Checking: 0it [00:00, ?it/s]

C:\Users\peter\anaconda3\envs\cv\lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:224: PossibleUserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 12 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
C:\Users\peter\anaconda3\envs\cv\lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:224: PossibleUserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 12 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(

Training: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

In [12]:
te = seq_encoder.trx_encoder.cat_embeddings
support = {col: te.emb_dict[col](df[col]) for col in te.features}

{'training': False,
 '_parameters': {},
 '_buffers': {},
 '_non_persistent_buffers_set': set(),
 '_backward_pre_hooks': OrderedDict(),
 '_backward_hooks': OrderedDict(),
 '_is_full_backward_hook': None,
 '_forward_hooks': OrderedDict(),
 '_forward_hooks_with_kwargs': OrderedDict(),
 '_forward_hooks_always_called': OrderedDict(),
 '_forward_pre_hooks': OrderedDict(),
 '_forward_pre_hooks_with_kwargs': OrderedDict(),
 '_state_dict_hooks': OrderedDict(),
 '_state_dict_pre_hooks': OrderedDict(),
 '_load_state_dict_pre_hooks': OrderedDict(),
 '_load_state_dict_post_hooks': OrderedDict(),
 '_modules': {'cat_table': ModuleDict(
    (small_group): Embedding(203, 16)
    (trans_date): Embedding(731, 16)
  ),
  'forward_mlp': ModuleList(
    (0-1): 2 x Linear(in_features=16, out_features=16, bias=True)
  ),
  'dropout': Dropout(p=0.2, inplace=False),
  'emb_dict': ModuleDict(
    (small_group): Embedding(203, 16)
    (trans_date): Embedding(731, 16)
  )},
 'features': ['small_group', 'trans_date']}

In [17]:
{'a' : 1, 'b' : 2, 'c' : 3} and {'a', 'b'}

{'a', 'b'}

### Get cosine-dist metric values on train/test datasets

In [5]:
df_params = {'numeric_cols': ['amount_rur'],
     'cat_cols': ['small_group'],
     'date_col': 'trans_date',
     'cat_unique': [202, 730],
     'id_col': 'client_id'}

In [20]:
weights['trx_encoder.embeddings.amount_rur.weight'].shape

torch.Size([20, 16])

In [ ]:
from lightgbm import LGBMClassifier
from sklearn.ensemble import RandomForestClassifier
res_metrics = []
N_TRIALS = 5

tasks = {'boosting' : LGBMClassifier(), 'r_forest' : RandomForestClassifier()}

def get_train_test_age_bins_scenario(df_params, embeds, ds_type):
    data_path = "../data/age_bins"
    
    df_target = pd.read_csv(os.path.join(data_path, 'train_target.csv'))
    df_target = df_target.set_index(df_params["id_col"])
    df_target.rename(columns={"bins": "target"}, inplace=True)
    
    train_df = pd.DataFrame(data=train_embeds, columns=[f'embed_{i}' for i in range(train_embeds.shape[1])])
    train_df[df_params["id_col"]] = [x[df_params["id_col"]] for x in train]
    train_df = train_df.merge(df_target, how='left', on=df_params["id_col"])
    
    test_df = pd.DataFrame(data=test_embeds, columns=[f'embed_{i}' for i in range(test_embeds.shape[1])])
    test_df[df_params["id_col"]] = [x[df_params["id_col"]] for x in test]
    test_df = test_df.merge(df_target, how='left', on=df_params["id_col"])
    return train_df, test_df

for exp in glove_experiments:
    df_params = {'numeric_cols': ['amount_rur'],
     'cat_cols': ['small_group'],
     'date_col': 'trans_date',
     'cat_unique': [202, 730],
     'id_col': 'client_id'}
    if not exp['nemb']:
        df_params['cat_cols'] =  df_params['numeric_cols'] + df_params['cat_cols']
        df_params["cat_unique"] = (exp['disc'].k_bins if (type(exp['disc'].k_bins) is list) else [exp['disc'].k_bins] * len(df_params['numeric_cols'])) + df_params["cat_unique"]

    with open(f"../coles_prep_datasets/{exp['name']}_dataset.pkl", "rb") as fl:
        dataset = pickle.load(fl)

    train, test = train_test_split(dataset, test_size=0.2, random_state=42)

    if 'glove_config' in exp:
        if not exp['nsep']:
            embedded_feats = df_params['numeric_cols'] + df_params['cat_cols'] + [df_params["date_col"]]
        else:
            embedded_feats = df_params['cat_cols'] + [df_params["date_col"]]
        glove_embedding = GloveEmbedding(
            feature_names=embedded_feats,
            calculate_cooccur=False,
            embedding_folder=f'../glove_embeddings/{exp["name"]}'[:-4],
            glove_params=exp['glove_config']
        )
        glove_embedding.load()
    
    #seq_encoder = get_cat_encoder(df_params, agg_type=exp['agg_type'], num_emb_flag=exp['nemb'])
    seq_encoder = get_cat_encoder(df_params, exp=exp, glove_embedding)
    seq_encoder.load_state_dict(torch.load(f"../models_coles/{exp['name']}_emb.pt"))

    metric = BatchRecallTopK(4)

    train_embeds = None
    test_embeds = None

    for ds_name, ds in [('test', test), ('train', train)]:
        dl = PtlsDataModule(
            test_data = ColesDataset(
                    MemoryMapDataset(
                        data=ds,
                        i_filters=[
                            SeqLenFilter(min_seq_len=25),
                        ],
                    ),
                    splitter=SampleSlices(
                        split_count=5,
                        cnt_min=25,
                        cnt_max=200,
                    ),
                ),
            train_num_workers=1,
            train_batch_size=256,
        )

        module = TestModule(
            model = seq_encoder,
            metrics = {"recall_top_k" : metric}
        )
    
        predictor = pl.Trainer(
                accelerator="gpu",
                enable_model_summary=False,
                logger=False
        )

        predictor.predict(module, dl)

        ds_metrics = module.get_metrics()

        for m in ds_metrics:
            res_metrics.append([exp['name'], ds_name, m, ds_metrics[m]])

    coles_model = CoLESModule(
            seq_encoder=seq_encoder,
    )

    inference_runner = pl.Trainer(
        accelerator="gpu",
        enable_progress_bar=True,
        enable_model_summary=False,
        logger=False
    )
    
    train_dl = inference_data_loader(train, num_workers=0, batch_size=256)
    train_embeds = torch.vstack(inference_runner.predict(coles_model, train_dl))
    
    test_dl = inference_data_loader(test, num_workers=0, batch_size=256)
    test_embeds = torch.vstack(inference_runner.predict(coles_model, test_dl))

    train_df, test_df = get_train_test_age_bins_scenario(df_params, train_embeds, test_embeds)

    for task_name, clf in tasks.items():
        sc_test = 0
        sc_train = 0
        num = 0
        for i in tqdm(range(N_TRIALS)):
            embed_columns = [x for x in train_df.columns if x.startswith('embed')]
            x_train, y_train = train_df[embed_columns], train_df['target']
            x_test, y_test = test_df[embed_columns], test_df['target']
            
            clf.fit(x_train, y_train)
            sc_test += clf.score(x_test, y_test)
            sc_train += clf.score(x_train, y_train)
            num += 1

        res_metrics.append([exp['name'], 'train', f"acc_{task_name}", sc_train/num])
        res_metrics.append([exp['name'], 'test', f"acc_{task_name}", sc_test/num])

    report = pd.DataFrame(res_metrics, columns = ['exp_name', 'dataset', 'metric', 'value'])
    report.to_csv('../coles_report/experiments/report_glove1.csv')

In [10]:
del train_df, test_df, train_embeds, test_embeds, train, test

In [10]:
%%time

dataset = preprocessor.fit_transform(data)

CPU times: total: 14.7 s
Wall time: 15.9 s

In [11]:
import pickle

with open('preprocessor.p', 'wb') as f:
    pickle.dump(preprocessor, f)

In [12]:
dataset = sorted(dataset, key=lambda x: x[df_params['id_col']])

In [13]:
from sklearn.model_selection import train_test_split

train, test = train_test_split(dataset, test_size=0.2, random_state=42)

len(train), len(test)

(12000, 3000)

In [14]:
del dataset

## Embedding training

Model training in our framework organised via pytorch-lightning (pl) framework.
The key parts of neural networks training in pl are: 

    * model (`pytorch_lightning.LightningModule`)
    * data loader (`torch.utils.data.DataLoader`)
    * trainer (`pytorch_lightning.Trainer`)
    
For futher details check https://pytorchlightning.ai/

### Model definition

In [23]:
df_params

{'numeric_cols': ['amount'],
 'cat_cols': ['mcc_code', 'tr_type'],
 'cat_unique': [184, 77, 457],
 'date_col': 'tr_datetime',
 'id_col': 'customer_id'}

In [22]:
from functools import partial
from ptls.nn import RnnSeqEncoder, TrxEncoder
from ptls.nn.trx_encoder.trx_encoder_glove import TrxEncoderGlove
from ptls.frames.coles import CoLESModule
import ptls
import torch

def get_basic_model_encoder(df_params):
    embeddings=dict()
    for i, f in enumerate(df_params["cat_cols"] + [df_params["date_col"]]):
        embeddings[f] = {'in' : df_params["cat_unique"][i], 'out' : 16}
    
    trx_encoder_params = dict(
        embeddings_noise=0.003,
        numeric_values=dict([(fe, 'identity') for fe in df_params['numeric_cols']]),
        embeddings=embeddings
    )
    
    seq_encoder = RnnSeqEncoder(
        trx_encoder=TrxEncoder(**trx_encoder_params),
        hidden_size=256,
        type='gru',
    )
    
    return seq_encoder

def get_glove_model_encoder(agg_type):
    seq_encoder = RnnSeqEncoder(
        trx_encoder=TrxEncoderGlove(glove_embedding, agg_type=agg_type),
        hidden_size=256,
        type='gru',
    )
    return seq_encoder


#seq_encoder = get_basic_model_encoder(df_params)
seq_encoder = get_glove_model_encoder(agg_type="sum")

model = CoLESModule(
    seq_encoder=seq_encoder,
    optimizer_partial=partial(torch.optim.Adam, lr=0.001),
    lr_scheduler_partial=partial(torch.optim.lr_scheduler.StepLR, step_size=30, gamma=0.9),
)

### Data loader

In [23]:
from ptls.data_load.datasets import MemoryMapDataset
from ptls.data_load.iterable_processing import SeqLenFilter
from ptls.frames.coles import ColesDataset
from ptls.frames.coles.split_strategy import SampleSlices
from ptls.frames import PtlsDataModule

train_dl = PtlsDataModule(
    train_data=ColesDataset(
        MemoryMapDataset(
            data=train,
            i_filters=[
                SeqLenFilter(min_seq_len=25),
            ],
        ),
        splitter=SampleSlices(
            split_count=5,
            cnt_min=25,
            cnt_max=200,
        ),
    ),
    train_num_workers=1,
    train_batch_size=256,
)

### Trainer

In [24]:
import torch
import pytorch_lightning as pl

import logging

trainer = pl.Trainer(
    max_epochs=15,
    accelerator="gpu",
    #devices=1,
    enable_progress_bar=True,
)

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs

### Training

In [25]:
%%time
print(f'logger.version = {trainer.logger.version}')
trainer.fit(model, train_dl)
print(trainer.logged_metrics)

C:\Users\peter\anaconda3\envs\cv\lib\site-packages\pytorch_lightning\trainer\configuration_validator.py:108: PossibleUserWarning: You defined a `validation_step` but have no `val_dataloader`. Skipping val loop.
  rank_zero_warn(
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name               | Type            | Params
-------------------------------------------------------
0 | _loss              | ContrastiveLoss | 0
1 | _seq_encoder       | RnnSeqEncoder   | 270 K
2 | _validation_metric | BatchRecallTopK | 0
3 | _head              | Head            | 0
-------------------------------------------------------
210 K     Trainable params
60.0 K    Non-trainable params
270 K     Total params
1.083     Total estimated model params size (MB)

logger.version = 175

C:\Users\peter\anaconda3\envs\cv\lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:224: PossibleUserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 12 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
C:\Users\peter\anaconda3\envs\cv\lib\site-packages\pytorch_lightning\trainer\trainer.py:1609: PossibleUserWarning: The number of training batches (46) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.
  rank_zero_warn(

Training: 0it [00:00, ?it/s]

`Trainer.fit` stopped: `max_epochs=15` reached.

{'loss': tensor(257.4940), 'seq_len': tensor(97.3034)}
CPU times: total: 1min 58s
Wall time: 7min 6s

### Save sequence encoder for other experiments

In [53]:
torch.save(seq_encoder.state_dict(), "coles-emb.pt")

## Inference

In [26]:
# embedding inference

train_dl = inference_data_loader(train, num_workers=0, batch_size=256)
train_embeds = torch.vstack(trainer.predict(model, train_dl, ))

test_dl = inference_data_loader(test, num_workers=0, batch_size=256)
test_embeds = torch.vstack(trainer.predict(model, test_dl))

train_embeds.shape, test_embeds.shape

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
C:\Users\peter\anaconda3\envs\cv\lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:224: PossibleUserWarning: The dataloader, predict_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 12 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(

Predicting: 46it [00:00, ?it/s]

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: 46it [00:00, ?it/s]

(torch.Size([12000, 256]), torch.Size([3000, 256]))

In [20]:
def get_train_test_age_bins_scenario(df_params, train_embeds, test_embeds):
    data_path = "data/age_bins"
    
    df_target = pd.read_csv(os.path.join(data_path, 'train_target.csv'))
    df_target = df_target.set_index(df_params["id_col"])
    df_target.rename(columns={"bins": "target"}, inplace=True)
    
    train_df = pd.DataFrame(data=train_embeds, columns=[f'embed_{i}' for i in range(train_embeds.shape[1])])
    train_df[df_params["id_col"]] = [x[df_params["id_col"]] for x in train]
    train_df = train_df.merge(df_target, how='left', on=df_params["id_col"])
    
    test_df = pd.DataFrame(data=test_embeds, columns=[f'embed_{i}' for i in range(test_embeds.shape[1])])
    test_df[df_params["id_col"]] = [x[df_params["id_col"]] for x in test]
    test_df = test_df.merge(df_target, how='left', on=df_params["id_col"])
    return train_df, test_df

def get_train_test_gender_scenario(df_params, train_embeds, test_embeds):
    data_path = "data/gender"
    
    df_target = pd.read_csv(os.path.join(data_path, 'gender_train.csv'))
    df_target = df_target.set_index(df_params["id_col"])
    df_target.rename(columns={"gender": "target"}, inplace=True)
    
    train_df = pd.DataFrame(data=train_embeds, columns=[f'embed_{i}' for i in range(train_embeds.shape[1])])
    train_df[df_params["id_col"]] = [x[df_params["id_col"]] for x in train]
    train_df = train_df.merge(df_target, how='left', on=df_params["id_col"])
    
    test_df = pd.DataFrame(data=test_embeds, columns=[f'embed_{i}' for i in range(test_embeds.shape[1])])
    test_df[df_params["id_col"]] = [x[df_params["id_col"]] for x in test]
    test_df = test_df.merge(df_target, how='left', on=df_params["id_col"])
    train_df = train_df.fillna(2)
    test_df = test_df.fillna(2)
    return train_df, test_df

In [10]:
import os
import pandas as pd

data_path = 'data/rosbank'

data_train = pd.read_csv(os.path.join(data_path, 'train.csv'))
data_test = pd.read_csv(os.path.join(data_path, 'test.csv'))

df_trx = get_df_trx(data_train, data_test)
df_trx = df_trx.fillna("unknown_type")
df_target = get_df_target(data_train)

In [56]:
# join target and embeddings

#df_target = pd.read_csv(os.path.join(data_path, 'train_target.csv'))
#df_target = pd.read_csv(os.path.join(data_path, 'gender_train.csv'))
#df_target = df_target.rename(columns={"customer_id" : "client_id"})
#df_target = df_target.set_index('client_id')
#df_target.rename(columns={"bins": "target"}, inplace=True)
df_target.rename(columns={"target_flag": "target"}, inplace=True)

train_df = pd.DataFrame(data=train_embeds, columns=[f'embed_{i}' for i in range(train_embeds.shape[1])])
train_df['client_id'] = [x['client_id'] for x in train]
#train_df = train_df.merge(df_target, how='left', on='client_id')

test_df = pd.DataFrame(data=test_embeds, columns=[f'embed_{i}' for i in range(test_embeds.shape[1])])
test_df['client_id'] = [x['client_id'] for x in test]
#test_df = test_df.merge(df_target, how='left', on='client_id')

print(train_df.shape, test_df.shape)

(8173, 257) (2044, 257)

In [57]:
df_target["client_id"] = df_target.index

In [58]:
train_df = train_df.merge(df_target, how='left', on='client_id')

In [59]:
test_df = test_df.merge(df_target, how='left', on='client_id')

Obtained embeddings can be used as features for model training

For example:

In [27]:
from sklearn.ensemble import RandomForestClassifier

metrics_on_tasks = []

for exp in experiments:

    train_dl = inference_data_loader(train, num_workers=0, batch_size=256)
    train_embeds = torch.vstack(trainer.predict(model, train_dl, ))
    
    test_dl = inference_data_loader(test, num_workers=0, batch_size=256)
    test_embeds = torch.vstack(trainer.predict(model, test_dl))


    train_df, test_df = get_train_test_gender_scenario(df_params, train_embeds, test_embeds)
    
    sc = 0
    num = 0
    for i in range(10):
        embed_columns = [x for x in train_df.columns if x.startswith('embed')]
        x_train, y_train = train_df[embed_columns], train_df['target']
        x_test, y_test = test_df[embed_columns], test_df['target']
        
        clf = RandomForestClassifier()
        clf.fit(x_train, y_train)
        sc += clf.score(x_test, y_test)
        num += 1
    sc/num

0.4342

In [ ]:
#glove_cat 0.75 100 tree_binning 3t
cat 0.5846666666666667
mean 0.5629666666666667
sum 0.5711

#glove_cat 0.75 5000 tree_binning 6t
cat 0.5912666666666666
mean 0.5697333333333333
sum 0.5792666666666667

#glove_cat 0.75 15000 tree_binning 9t
cat 0.5797666666666668
mean 0.5720000000000001
sum 0.5781666666666667

###gender

#glove_cat 0.75 100 tree_binning 3t
cat 0.438
mean 0.4342
sum 0.5711

#glove_cat 0.75 5000 tree_binning 6t
cat 0.4500333333333333
mean 0.4312666666666667
sum 0.4416333333333333

#glove_cat 0.75 15000 tree_binning 9t
cat 0.4503666666666667
mean 0.433
sum 0.44053333333333333

In [ ]:
#normal
0.48356164383561645

#glove_mean 0.75 1000 100 bins
mean 0.4900195694716243
sum 0.49735812133072405
cat 0.4990215264187867

#glove_mean 0.75 5000 150 bins
mean 0.49549902152641884
sum 0.4918786692759296
cat 0.5001956947162427