## Setup

In [1]:
import numpy as np
import pandas as pd
from tqdm.notebook import tqdm
from torch.utils.data import Dataset, DataLoader
import copy
import pickle
import sys
import os

import pytorch_lightning as pl

import logging

sys.path.insert(0, 'C:\\Users\\peter\\anaconda3\\envs\\cv\\Scripts\\ptls-glove')

from functools import partial
from ptls.nn import RnnSeqEncoder, TrxEncoder
from ptls.nn.trx_encoder.trx_encoder_glove import TrxEncoderGlove, TrxEncoderCat, TrxEncoderTrans
from ptls.nn.trx_encoder import GloveEmbedding
from ptls.preprocessing.baseline_discretizer import KDiscretizer, SingleTreeDiscretizer
from ptls.preprocessing.deeptlf.src import DeepTLF
from ptls.frames.coles import CoLESModule
from ptls.data_load.datasets import MemoryMapDataset
from ptls.data_load.iterable_processing import SeqLenFilter
from ptls.frames.coles import ColesDataset
from ptls.frames.coles.split_strategy import SampleSlices
from ptls.frames import PtlsDataModule, TestModule
from ptls.frames.coles.metric import BatchRecallTopK
from ptls.preprocessing.deeptlf import DeepTLFDisc

import ptls
import torch
from torch import nn
from ptls.preprocessing import PandasDataPreprocessor
from sklearn.model_selection import train_test_split
from ptls.data_load.datasets import inference_data_loader
from pytorch_lightning.callbacks.early_stopping import EarlyStopping

C:\Users\peter\anaconda3\envs\cv\lib\site-packages\torchaudio\backend\utils.py:62: UserWarning: No audio backend is available.
  warnings.warn("No audio backend is available.")

In [3]:
# import os

# if not os.path.exists('data/transactions_train.csv'):
#     ! mkdir -p data
#     ! curl -OL https://storage.yandexcloud.net/ptls-datasets/age-prediction-nti-sbebank-2019.zip
#     ! unzip -j -o age-prediction-nti-sbebank-2019.zip 'data/*.csv' -d data
#     ! mv age-prediction-nti-sbebank-2019.zip data/

## Preprocessing rosbank

In [2]:
def get_df_trx(df_train, df_test):
    COL_EVENT_TIME = 'TRDATETIME'
    df_train = df_train.drop(['PERIOD', 'target_flag', 'target_sum'], axis=1)
    df_test = df_test.drop(['PERIOD'], axis=1)

    df = pd.concat([df_train, df_test], ignore_index=True)

    # event_time mapping
    df['_et_day'] = pd.to_datetime(df[COL_EVENT_TIME].str[:7], format='%d%b%y').astype(np.int64) // 10**9
    df['_et_time'] = (pd.to_datetime(df[COL_EVENT_TIME].str[8:], format='%H:%M:%S').astype(np.int64) // 10**9)

    df['event_time'] = df['_et_day'] + df['_et_time']
    df = df.drop(['_et_day', '_et_time', COL_EVENT_TIME], axis=1)

    df.columns = df.columns.str.lower()
    df['amount'] = df['amount'].astype(float)

    return df

def get_df_target(df_train):
    df_target = df_train.groupby("cl_id")["target_flag"].first().astype({"target_flag": 'int'})

    return pd.DataFrame(df_target)

def split_target(df):
    df['seq_len'] =  np.ceil(np.log(df['seq_len'] / np.log(4))).astype('string')
    df['hash'] = (pd.Series(df.index.astype(str) + "42").apply(hash) / (2 ** 32) + 0.5).values
    df['fold_id'] = df.groupby(["target_flag", 'seq_len'])['hash'].rank(method='first', ascending=True) % 6
    
    df = df.drop(columns = ['hash', 'seq_len'])
    return df

def split_fold(fold_id, df_target, df_trx):
    folds_path = Path(conf_pp.folds_path)
    preproc = PysparkDataPreprocessor(
        col_id=conf_pp.col_client_id,
        col_event_time='event_time',
        event_time_transformation='none',
        cols_category=["mcc", "channel_type", "currency", "trx_category"],
        cols_numerical=['amount'],
        cols_last_item=[conf_pp.col_target],
    )
    df_train_trx = df_trx.merge(df_target, how='left', on=conf_pp.col_client_id).loc[lambda x: x['fold_id'].fillna(-1) != fold_id].drop('fold_id', axis=1)
    df_test_trx = df_trx.merge(df_target.loc[lambda x: x['fold_id'] == fold_id].drop('fold_id', axis=1), how='inner', on=conf_pp.col_client_id)
    df_train_data = preproc.fit_transform(df_train_trx)
    df_test_data = preproc.transform(df_test_trx)
    file_name_train = get_file_name_train(fold_id)
    file_name_test = get_file_name_test(fold_id)
    df_train_data.to_parquet(folds_path / file_name_train, mode='overwrite')
    df_test_data.to_parquet(folds_path / file_name_test, mode='overwrite')
    with open(folds_path / f'preproc_{fold_id}.p', 'wb') as f:
        pickle.dump(preproc, f)
    logger.info(f'Preprocessor[{fold_id}].category_dictionary_sizes={preproc.get_category_dictionary_sizes()}')

    for df_name in [file_name_train, file_name_test]:
        df = pd.read_parquet(folds_path / df_name)
        logger.info(f'{df_name:30} {df.shape}')

    for df_name in [file_name_train, file_name_test]:
        df = pd.read_parquet(folds_path / df_name)
        r_counts = df[conf_pp.col_target].value_counts(dropna=False).to_dict()
        cnt_str = ', '.join([f'{r_counts.get(0, 0):5d} - 0 class', f'{r_counts.get(1, 0):5d} - 1 class'])
        logger.info(f'{df_name:30} {cnt_str}')

In [2]:
import os
import pandas as pd

data_path = 'data/rosbank'

train = pd.read_csv(os.path.join(data_path, 'train.csv'))
test = pd.read_csv(os.path.join(data_path, 'test.csv'))

FileNotFoundError: [Errno 2] No such file or directory: 'data/rosbank/train.csv'

In [2]:
df_trx = get_df_trx(train, test)
df_trx = df_trx.fillna("unknown_type")
df_target = get_df_target(train)

NameError: name 'get_df_trx' is not defined

In [6]:
df_trx = df_trx.sort_values(by=["cl_id", "event_time"], ascending=True)

In [7]:
source_data = df_trx.rename({"cl_id" : "client_id", "event_time" : "tr_datetime"})

In [8]:
source_data.rename(columns = {"cl_id" : "client_id", "event_time" : "tr_datatime"}, inplace=True)

In [9]:
source_data

,client_id,mcc,channel_type,currency,amount,trx_category,tr_datatime
1,0,6011,unknown_type,810,20000.00,DEPOSIT,-701177753
0,0,5200,unknown_type,810,5023.00,POS,-700444800
3,0,5411,unknown_type,810,2031.00,POS,-700444800
4,0,6012,unknown_type,810,36562.00,C2C_OUT,-700137936
2,0,5921,unknown_type,810,767.00,POS,-696556800
...,...,...,...,...,...,...,...
1008299,10216,5411,type1,810,132.13,POS,-712886400
1008293,10216,5691,type1,810,2090.00,POS,-712540800
1008296,10216,5411,type1,810,1259.31,POS,-712540800
1008285,10216,5691,type1,810,1185.00,POS,-712454400
1008290,10216,7922,type1,810,1500.00,POS,-712454400

## Preprocessing kaggle card-trans

In [5]:
data_path = 'data/kaggle_nir_card_trans'

data = pd.read_csv(os.path.join(data_path, 'credit_card_transactions.csv'))

## Data preproccessing

In [3]:
def prepare_data_age_bins_scenario():
    data_path = '../data/age_bins'

    source_data = pd.read_csv(os.path.join(data_path, 'transactions_train.csv'))

    df_params = {
        "numeric_cols" : ["amount_rur"],
        "cat_cols" : ["small_group"],
        "date_col" : "trans_date",
        "cat_unique" : [],
        "id_col" : "client_id"
    }

    for f in df_params["cat_cols"] + [df_params["date_col"]]:
        df_params["cat_unique"].append(source_data[f].unique().shape[0])

    return source_data, df_params

def prepare_data_gender_scenario():
    data_path = 'data/gender'

    source_data = pd.read_csv(os.path.join(data_path, 'transactions.csv'))
    source_data = source_data.drop(columns=["term_id"])

    source_data.tr_datetime = [int(i.split()[0]) for i in source_data.tr_datetime.values]

    df_params = {
        "numeric_cols" : ["amount"],
        "cat_cols" : ["mcc_code", "tr_type"],
        "cat_unique" : [],
        "date_col" : "tr_datetime",
        "id_col" : "customer_id"
    }

    for f in df_params["cat_cols"] + [df_params["date_col"]]:
        df_params["cat_unique"].append(source_data[f].unique().shape[0])
    
    return source_data, df_params

In [4]:
source_data, df_params = prepare_data_age_bins_scenario()
targets = pd.read_csv(os.path.join('../data/age_bins', 'train_target.csv'))
source_data.head(2)

   client_id  trans_date  small_group  amount_rur
0      33172           6            4      71.463
1      33172           6           35      45.017

In [4]:
preprocessor = PandasDataPreprocessor(
        col_id=df_params['id_col'],
        col_event_time=df_params['date_col'],
        event_time_transformation='none',
        cols_category=df_params['cat_cols'],
        cols_numerical=df_params['numeric_cols'],
        return_records=True,
    )
    
dataset = preprocessor.fit_transform(source_data)

In [17]:
un = set()
for i in tqdm(dataset):
    un |= set(list(map(lambda x: x.item(), i['small_group'].unique())))

  0%|          | 0/30000 [00:00<?, ?it/s]

In [30]:
source_data.shape, targets.shape

((26450577, 4), (30000, 2))

In [7]:
#primary encoding of bin features with bin categories

data = simple_bin_numeric(source_data, {"amount" : 20})

In [2]:
EMBED_SIZE = 16

df_params = {'numeric_cols': ['amount_rur'],
     'cat_cols': ['small_group'],
     'date_col': 'trans_date',
     'cat_unique': [202, 730],
     'id_col': 'client_id'}

#best discretizers

disc_quant100 = KDiscretizer(
    f_names = ['amount_rur'],
    k_bins = 100,
    d_type = 'quantile'
)

deeptlf_params9 = DeepTLFDisc({"n_est" : 9,
                  "min_freq" : 2,
                  "features" : df_params['numeric_cols'] + df_params['cat_cols'],
                  "features_to_split" : df_params['numeric_cols'],
                  })

disc_st20 = SingleTreeDiscretizer(
    f_names = ['amount_rur'], 
    target_name = 'bins', 
    target_type = 'classification', 
    k_bins = [20],
)

glove_config1= {"alpha" : 0.75, 
                "x_max" : 100, 
                "embedding_size" : EMBED_SIZE, 
                "num_epochs_train" : 50}

glove_config2= {"alpha" : 0.75, 
                "x_max" : 15000, 
                "embedding_size" : EMBED_SIZE, 
                "num_epochs_train" : 50}

glove_config3= {"alpha" : 1.0, 
                "x_max" : 20000, 
                "embedding_size" : EMBED_SIZE, 
                "num_epochs_train" : 50}

# experiments = [
#     {
#         'name' : 'glove_emb_cfg1_no_num',
#         'glove_config' : glove_config1,
#         'disc' : None
#     },
#     {
#         'name' : 'glove_emb_cfg2_no_num',
#         'glove_config' : glove_config2,
#         'disc' : None
#     },
#     {
#         'name' : 'glove_emb_cfg3_no_num',
#         'glove_config' : glove_config3,
#         'disc' : None
#     },
#     {
#         'name' : 'glove_emb_cfg1_ST20',
#         'glove_config' : glove_config1,
#         'disc' : disc_st20
#     },
#     {
#         'name' : 'glove_emb_cfg2_quant100',
#         'glove_config' : glove_config2,
#         'disc' : disc_quant100
#     },
#     {
#         'name' : 'glove_emb_cfg3_quant100',
#         'glove_config' : glove_config3,
#         'disc' : disc_quant100
#     },
#     {
#         'name' : 'glove_emb_cfg2_deeptlf9',
#         'glove_config' : glove_config2,
#         'disc' : deeptlf_params9
#     },
# ]

glove_config2_8= {"alpha" : 0.75, 
                "x_max" : 15000, 
                "embedding_size" : 8, 
                "num_epochs_train" : 50}

glove_config2_40= {"alpha" : 0.75, 
                "x_max" : 15000, 
                "embedding_size" : 24, 
                "num_epochs_train" : 50}

glove_config2_52= {"alpha" : 0.75, 
                "x_max" : 15000, 
                "embedding_size" : 32, 
                "num_epochs_train" : 50}

experiments = [
    {
        'name' : 'glove_emb40_cfg2_deeptlf9',
        'glove_config' : glove_config2_40,
        'disc' : copy.deepcopy(deeptlf_params9)
    },
    {
        'name' : 'glove_emb52_cfg2_deeptlf9',
        'glove_config' : glove_config2_52,
        'disc' : copy.deepcopy(deeptlf_params9)
    },
    {
        'name' : 'glove_emb40_cfg2_quant100',
        'glove_config' : glove_config2_40,
        'disc' : copy.deepcopy(disc_quant100)
    },
    {
        'name' : 'glove_emb52_cfg2_quant100',
        'glove_config' : glove_config2_52,
        'disc' : copy.deepcopy(disc_quant100)
    },
]

In [5]:
for exp in experiments:
    print(exp['name'])
    data = copy.deepcopy(source_data)
    disc = exp['disc']
    if disc is not None:
        if "ST" not in exp['name']:
            disc.fit(data)
            data = disc.transform(data, to_embeds=False)
        else:
            disc.fit(data.sample(int(1e+5), random_state=42).merge(targets, on=df_params['id_col'], how='left'))
            data = disc.transform(data, to_embeds=False)
        print(f"{exp['name']}: DATA DISCRETIZED")
        
        embedded_feats = df_params['numeric_cols'] + df_params['cat_cols'] + [df_params["date_col"]]
    else:
        embedded_feats = df_params['cat_cols'] + [df_params["date_col"]]
        
    print(embedded_feats)
    glove_embedding = GloveEmbedding(
            feature_names=embedded_feats,
            calculate_cooccur=True,
            embedding_folder=f'../glove_embeddings/{exp["name"]}',
            glove_params=exp['glove_config']
        )
    glove_embedding.fit(data)
    print(f"{exp['name']}: GLOVE EMB CALCULATED")

glove_emb8_cfg2_deeptlf9
Counter({'small_group': 153, 'amount_rur': 62})
glove_emb8_cfg2_deeptlf9: DATA DISCRETIZED
['amount_rur', 'small_group', 'trans_date']
train started

  2%|█▋                                                                                 | 1/50 [00:05<04:11,  5.14s/it]

Epoch 0: loss = 7818.822632183935

  4%|███▎                                                                               | 2/50 [00:10<04:01,  5.03s/it]

Epoch 1: loss = 3708.2500713312966

  6%|████▉                                                                              | 3/50 [00:14<03:53,  4.96s/it]

Epoch 2: loss = 2123.5315105309696

  8%|██████▋                                                                            | 4/50 [00:19<03:48,  4.96s/it]

Epoch 3: loss = 1303.55757899806

 10%|████████▎                                                                          | 5/50 [00:25<03:52,  5.17s/it]

Epoch 4: loss = 846.1563107426044

 12%|█████████▉                                                                         | 6/50 [00:32<04:10,  5.70s/it]

Epoch 5: loss = 582.8562777474259

 14%|███████████▌                                                                       | 7/50 [00:38<04:18,  6.00s/it]

Epoch 6: loss = 420.3419696266953

 16%|█████████████▎                                                                     | 8/50 [00:45<04:18,  6.14s/it]

Epoch 7: loss = 314.6836743833295

 18%|██████████████▉                                                                    | 9/50 [00:51<04:17,  6.27s/it]

Epoch 8: loss = 243.54388299874097

 20%|████████████████▍                                                                 | 10/50 [00:58<04:14,  6.36s/it]

Epoch 9: loss = 193.37934968512317

 22%|██████████████████                                                                | 11/50 [01:04<04:08,  6.38s/it]

Epoch 10: loss = 157.63324444536866

 24%|███████████████████▋                                                              | 12/50 [01:11<04:04,  6.42s/it]

Epoch 11: loss = 131.46740584625016

 26%|█████████████████████▎                                                            | 13/50 [01:17<03:57,  6.42s/it]

Epoch 12: loss = 111.88350761333095

 28%|██████████████████████▉                                                           | 14/50 [01:24<03:52,  6.46s/it]

Epoch 13: loss = 96.96933669432529

 30%|████████████████████████▌                                                         | 15/50 [01:30<03:47,  6.50s/it]

Epoch 14: loss = 85.44227076312905

 32%|██████████████████████████▏                                                       | 16/50 [01:37<03:40,  6.49s/it]

Epoch 15: loss = 76.39913869649024

 34%|███████████████████████████▉                                                      | 17/50 [01:43<03:34,  6.49s/it]

Epoch 16: loss = 69.20740386551898

 36%|█████████████████████████████▌                                                    | 18/50 [01:50<03:28,  6.52s/it]

Epoch 17: loss = 63.40145298830111

 38%|███████████████████████████████▏                                                  | 19/50 [01:56<03:21,  6.50s/it]

Epoch 18: loss = 58.662837033327996

 40%|████████████████████████████████▊                                                 | 20/50 [02:03<03:15,  6.51s/it]

Epoch 19: loss = 54.761833256858786

 42%|██████████████████████████████████▍                                               | 21/50 [02:09<03:08,  6.49s/it]

Epoch 20: loss = 51.5070971261844

 44%|████████████████████████████████████                                              | 22/50 [02:16<03:01,  6.49s/it]

Epoch 21: loss = 48.82383349647214

 46%|█████████████████████████████████████▋                                            | 23/50 [02:22<02:55,  6.50s/it]

Epoch 22: loss = 46.439661324488775

 48%|███████████████████████████████████████▎                                          | 24/50 [02:29<02:48,  6.48s/it]

Epoch 23: loss = 44.440640314852345

 50%|█████████████████████████████████████████                                         | 25/50 [02:35<02:42,  6.51s/it]

Epoch 24: loss = 42.70898354060261

 52%|██████████████████████████████████████████▋                                       | 26/50 [02:42<02:36,  6.51s/it]

Epoch 25: loss = 41.21200103100324

 54%|████████████████████████████████████████████▎                                     | 27/50 [02:48<02:29,  6.49s/it]

Epoch 26: loss = 39.90401703630165

 56%|█████████████████████████████████████████████▉                                    | 28/50 [02:55<02:22,  6.49s/it]

Epoch 27: loss = 38.73069758961475

 58%|███████████████████████████████████████████████▌                                  | 29/50 [03:01<02:16,  6.49s/it]

Epoch 28: loss = 37.70054721637723

 60%|█████████████████████████████████████████████████▏                                | 30/50 [03:08<02:10,  6.53s/it]

Epoch 29: loss = 36.78306363938067

 62%|██████████████████████████████████████████████████▊                               | 31/50 [03:14<02:04,  6.53s/it]

Epoch 30: loss = 35.9529934724336

 64%|████████████████████████████████████████████████████▍                             | 32/50 [03:21<01:57,  6.51s/it]

Epoch 31: loss = 35.210407499825955

 66%|██████████████████████████████████████████████████████                            | 33/50 [03:27<01:50,  6.50s/it]

Epoch 32: loss = 34.551607468449085

 68%|███████████████████████████████████████████████████████▊                          | 34/50 [03:34<01:44,  6.55s/it]

Epoch 33: loss = 33.91271375314822

 70%|█████████████████████████████████████████████████████████▍                        | 35/50 [03:41<01:37,  6.52s/it]

Epoch 34: loss = 33.346297972290806

 72%|███████████████████████████████████████████████████████████                       | 36/50 [03:47<01:31,  6.52s/it]

Epoch 35: loss = 32.83835097113845

 74%|████████████████████████████████████████████████████████████▋                     | 37/50 [03:54<01:24,  6.53s/it]

Epoch 36: loss = 32.34968713284258

 76%|██████████████████████████████████████████████████████████████▎                   | 38/50 [04:00<01:17,  6.49s/it]

Epoch 37: loss = 31.917981646894997

 78%|███████████████████████████████████████████████████████████████▉                  | 39/50 [04:07<01:14,  6.75s/it]

Epoch 38: loss = 31.49588170011223

 80%|█████████████████████████████████████████████████████████████████▌                | 40/50 [04:14<01:06,  6.66s/it]

Epoch 39: loss = 31.11051111272836

 82%|███████████████████████████████████████████████████████████████████▏              | 41/50 [04:20<00:59,  6.60s/it]

Epoch 40: loss = 30.75308701507578

 84%|████████████████████████████████████████████████████████████████████▉             | 42/50 [04:27<00:52,  6.58s/it]

Epoch 41: loss = 30.413827585993133

 86%|██████████████████████████████████████████████████████████████████████▌           | 43/50 [04:33<00:46,  6.58s/it]

Epoch 42: loss = 30.09750770223658

 88%|████████████████████████████████████████████████████████████████████████▏         | 44/50 [04:40<00:39,  6.55s/it]

Epoch 43: loss = 29.797758179340235

 90%|█████████████████████████████████████████████████████████████████████████▊        | 45/50 [04:46<00:32,  6.55s/it]

Epoch 44: loss = 29.526664219042868

 92%|███████████████████████████████████████████████████████████████████████████▍      | 46/50 [04:53<00:26,  6.53s/it]

Epoch 45: loss = 29.24901167114406

 94%|█████████████████████████████████████████████████████████████████████████████     | 47/50 [04:59<00:19,  6.50s/it]

Epoch 46: loss = 28.99820390722518

 96%|██████████████████████████████████████████████████████████████████████████████▋   | 48/50 [05:05<00:12,  6.28s/it]

Epoch 47: loss = 28.760139509655453

 98%|████████████████████████████████████████████████████████████████████████████████▎ | 49/50 [05:10<00:05,  5.98s/it]

Epoch 48: loss = 28.528601450888655

100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [05:15<00:00,  6.32s/it]

Epoch 49: loss = 28.313431365216417
glove_emb8_cfg2_deeptlf9: GLOVE EMB CALCULATED
glove_emb24_cfg2_deeptlf9

Counter({'small_group': 153, 'amount_rur': 62})
glove_emb24_cfg2_deeptlf9: DATA DISCRETIZED
['amount_rur', 'small_group', 'trans_date']
train started

  2%|█▋                                                                                 | 1/50 [00:05<04:09,  5.09s/it]

Epoch 0: loss = 10297.132004377054

  4%|███▎                                                                               | 2/50 [00:10<04:00,  5.02s/it]

Epoch 1: loss = 4831.225726755173

  6%|████▉                                                                              | 3/50 [00:15<03:55,  5.00s/it]

Epoch 2: loss = 2875.3629163233663

  8%|██████▋                                                                            | 4/50 [00:20<03:49,  4.99s/it]

Epoch 3: loss = 1849.896497432624

 10%|████████▎                                                                          | 5/50 [00:24<03:44,  4.99s/it]

Epoch 4: loss = 1267.7924926515848

 12%|█████████▉                                                                         | 6/50 [00:30<03:39,  4.99s/it]

Epoch 5: loss = 913.8375472245809

 14%|███████████▌                                                                       | 7/50 [00:35<03:34,  5.00s/it]

Epoch 6: loss = 685.7024608461487

 16%|█████████████▎                                                                     | 8/50 [00:39<03:29,  4.99s/it]

Epoch 7: loss = 531.0601109748296

 18%|██████████████▉                                                                    | 9/50 [00:45<03:25,  5.02s/it]

Epoch 8: loss = 422.2368624692988

 20%|████████████████▍                                                                 | 10/50 [00:50<03:21,  5.04s/it]

Epoch 9: loss = 342.97802936098464

 22%|██████████████████                                                                | 11/50 [00:55<03:15,  5.02s/it]

Epoch 10: loss = 283.8535418036297

 24%|███████████████████▋                                                              | 12/50 [01:00<03:10,  5.01s/it]

Epoch 11: loss = 238.97694882711153

 26%|█████████████████████▎                                                            | 13/50 [01:05<03:05,  5.00s/it]

Epoch 12: loss = 204.16062460164858

 28%|██████████████████████▉                                                           | 14/50 [01:10<03:00,  5.01s/it]

Epoch 13: loss = 176.74678132017246

 30%|████████████████████████▌                                                         | 15/50 [01:15<02:54,  4.99s/it]

Epoch 14: loss = 154.83861271901517

 32%|██████████████████████████▏                                                       | 16/50 [01:20<02:49,  5.00s/it]

Epoch 15: loss = 137.11954430342018

 34%|███████████████████████████▉                                                      | 17/50 [01:25<02:44,  4.99s/it]

Epoch 16: loss = 122.54031779987122

 36%|█████████████████████████████▌                                                    | 18/50 [01:30<02:40,  5.01s/it]

Epoch 17: loss = 110.48935283425507

 38%|███████████████████████████████▏                                                  | 19/50 [01:35<02:34,  4.98s/it]

Epoch 18: loss = 100.38645370441978

 40%|████████████████████████████████▊                                                 | 20/50 [01:40<02:29,  5.00s/it]

Epoch 19: loss = 91.85200630613606

 42%|██████████████████████████████████▍                                               | 21/50 [01:45<02:24,  4.99s/it]

Epoch 20: loss = 84.57436165622238

 44%|████████████████████████████████████                                              | 22/50 [01:50<02:20,  5.00s/it]

Epoch 21: loss = 78.32116302283502

 46%|█████████████████████████████████████▋                                            | 23/50 [01:54<02:14,  4.98s/it]

Epoch 22: loss = 72.91742115529271

 48%|███████████████████████████████████████▎                                          | 24/50 [02:00<02:09,  4.99s/it]

Epoch 23: loss = 68.21036639147731

 50%|█████████████████████████████████████████                                         | 25/50 [02:04<02:04,  4.97s/it]

Epoch 24: loss = 64.0796274846258

 52%|██████████████████████████████████████████▋                                       | 26/50 [02:09<01:59,  4.98s/it]

Epoch 25: loss = 60.47666949057936

 54%|████████████████████████████████████████████▎                                     | 27/50 [02:14<01:54,  4.96s/it]

Epoch 26: loss = 57.23452179872066

 56%|█████████████████████████████████████████████▉                                    | 28/50 [02:19<01:49,  4.97s/it]

Epoch 27: loss = 54.35943953910576

 58%|███████████████████████████████████████████████▌                                  | 29/50 [02:24<01:44,  4.96s/it]

Epoch 28: loss = 51.800927620612036

 60%|█████████████████████████████████████████████████▏                                | 30/50 [02:29<01:39,  4.98s/it]

Epoch 29: loss = 49.50396966505715

 62%|██████████████████████████████████████████████████▊                               | 31/50 [02:34<01:34,  4.97s/it]

Epoch 30: loss = 47.43417700162995

 64%|████████████████████████████████████████████████████▍                             | 32/50 [02:39<01:29,  4.98s/it]

Epoch 31: loss = 45.556094053977695

 66%|██████████████████████████████████████████████████████                            | 33/50 [02:44<01:24,  4.97s/it]

Epoch 32: loss = 43.85559558292568

 68%|███████████████████████████████████████████████████████▊                          | 34/50 [02:49<01:19,  4.99s/it]

Epoch 33: loss = 42.31065306739988

 70%|█████████████████████████████████████████████████████████▍                        | 35/50 [02:54<01:14,  4.98s/it]

Epoch 34: loss = 40.887757883353395

 72%|███████████████████████████████████████████████████████████                       | 36/50 [02:59<01:09,  4.99s/it]

Epoch 35: loss = 39.60020873534703

 74%|████████████████████████████████████████████████████████████▋                     | 37/50 [03:04<01:04,  4.98s/it]

Epoch 36: loss = 38.398996588463525

 76%|██████████████████████████████████████████████████████████████▎                   | 38/50 [03:09<00:59,  4.99s/it]

Epoch 37: loss = 37.296900956180686

 78%|███████████████████████████████████████████████████████████████▉                  | 39/50 [03:14<00:54,  4.97s/it]

Epoch 38: loss = 36.287423270936614

 80%|█████████████████████████████████████████████████████████████████▌                | 40/50 [03:19<00:50,  5.00s/it]

Epoch 39: loss = 35.34676894080643

 82%|███████████████████████████████████████████████████████████████████▏              | 41/50 [03:24<00:45,  5.02s/it]

Epoch 40: loss = 34.47031021838548

 84%|████████████████████████████████████████████████████████████████████▉             | 42/50 [03:29<00:40,  5.07s/it]

Epoch 41: loss = 33.65947179871136

 86%|██████████████████████████████████████████████████████████████████████▌           | 43/50 [03:35<00:35,  5.08s/it]

Epoch 42: loss = 32.906056330665955

 88%|████████████████████████████████████████████████████████████████████████▏         | 44/50 [03:40<00:30,  5.11s/it]

Epoch 43: loss = 32.19644375009982

 90%|█████████████████████████████████████████████████████████████████████████▊        | 45/50 [03:45<00:25,  5.13s/it]

Epoch 44: loss = 31.53634718855312

 92%|███████████████████████████████████████████████████████████████████████████▍      | 46/50 [03:50<00:20,  5.16s/it]

Epoch 45: loss = 30.920568470836614

 94%|█████████████████████████████████████████████████████████████████████████████     | 47/50 [03:55<00:15,  5.17s/it]

Epoch 46: loss = 30.3385413477525

 96%|██████████████████████████████████████████████████████████████████████████████▋   | 48/50 [04:01<00:10,  5.21s/it]

Epoch 47: loss = 29.791423799655295

 98%|████████████████████████████████████████████████████████████████████████████████▎ | 49/50 [04:06<00:05,  5.22s/it]

Epoch 48: loss = 29.276262659945086

100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [04:11<00:00,  5.03s/it]

Epoch 49: loss = 28.790963152363744
glove_emb24_cfg2_deeptlf9: GLOVE EMB CALCULATED
glove_emb32_cfg2_deeptlf9

Counter({'small_group': 153, 'amount_rur': 62})
glove_emb32_cfg2_deeptlf9: DATA DISCRETIZED
['amount_rur', 'small_group', 'trans_date']
train started

  2%|█▋                                                                                 | 1/50 [00:05<04:10,  5.11s/it]

Epoch 0: loss = 10683.019264993845

  4%|███▎                                                                               | 2/50 [00:10<04:02,  5.06s/it]

Epoch 1: loss = 4813.101619892299

  6%|████▉                                                                              | 3/50 [00:15<03:56,  5.04s/it]

Epoch 2: loss = 2821.5193360331587

  8%|██████▋                                                                            | 4/50 [00:20<03:51,  5.03s/it]

Epoch 3: loss = 1799.6425909834904

 10%|████████▎                                                                          | 5/50 [00:25<03:46,  5.03s/it]

Epoch 4: loss = 1233.5103348863092

 12%|█████████▉                                                                         | 6/50 [00:30<03:41,  5.03s/it]

Epoch 5: loss = 893.3884633799731

 14%|███████████▌                                                                       | 7/50 [00:35<03:36,  5.03s/it]

Epoch 6: loss = 675.5631402806105

 16%|█████████████▎                                                                     | 8/50 [00:40<03:31,  5.03s/it]

Epoch 7: loss = 526.078190838767

 18%|██████████████▉                                                                    | 9/50 [00:45<03:25,  5.02s/it]

Epoch 8: loss = 422.33966023994293

 20%|████████████████▍                                                                 | 10/50 [00:50<03:20,  5.02s/it]

Epoch 9: loss = 346.9131982322622

 22%|██████████████████                                                                | 11/50 [00:55<03:15,  5.01s/it]

Epoch 10: loss = 290.54900706914464

 24%|███████████████████▋                                                              | 12/50 [01:00<03:10,  5.02s/it]

Epoch 11: loss = 247.3380686145708

 26%|█████████████████████▎                                                            | 13/50 [01:05<03:08,  5.11s/it]

Epoch 12: loss = 213.53759202266139

 28%|██████████████████████▉                                                           | 14/50 [01:10<03:05,  5.16s/it]

Epoch 13: loss = 186.61601195383452

 30%|████████████████████████▌                                                         | 15/50 [01:16<03:01,  5.20s/it]

Epoch 14: loss = 164.8194707666591

 32%|██████████████████████████▏                                                       | 16/50 [01:21<02:57,  5.22s/it]

Epoch 15: loss = 146.98763169872186

 34%|███████████████████████████▉                                                      | 17/50 [01:26<02:52,  5.24s/it]

Epoch 16: loss = 132.20011957376676

 36%|█████████████████████████████▌                                                    | 18/50 [01:32<02:48,  5.25s/it]

Epoch 17: loss = 120.04540833941178

 38%|███████████████████████████████▏                                                  | 19/50 [01:37<02:42,  5.25s/it]

Epoch 18: loss = 109.28643563744731

 40%|████████████████████████████████▊                                                 | 20/50 [01:42<02:38,  5.27s/it]

Epoch 19: loss = 100.3277267104353

 42%|██████████████████████████████████▍                                               | 21/50 [01:47<02:33,  5.28s/it]

Epoch 20: loss = 92.63019747523036

 44%|████████████████████████████████████                                              | 22/50 [01:53<02:27,  5.28s/it]

Epoch 21: loss = 85.96435211796492

 46%|█████████████████████████████████████▋                                            | 23/50 [01:58<02:22,  5.27s/it]

Epoch 22: loss = 80.14246259363583

 48%|███████████████████████████████████████▎                                          | 24/50 [02:03<02:17,  5.27s/it]

Epoch 23: loss = 75.0459993447584

 50%|█████████████████████████████████████████                                         | 25/50 [02:08<02:11,  5.27s/it]

Epoch 24: loss = 70.56047639260733

 52%|██████████████████████████████████████████▋                                       | 26/50 [02:14<02:06,  5.27s/it]

Epoch 25: loss = 66.58992057190416

 54%|████████████████████████████████████████████▎                                     | 27/50 [02:19<02:01,  5.27s/it]

Epoch 26: loss = 63.04124301928661

 56%|█████████████████████████████████████████████▉                                    | 28/50 [02:24<01:55,  5.26s/it]

Epoch 27: loss = 59.87567764610479

 58%|███████████████████████████████████████████████▌                                  | 29/50 [02:30<01:50,  5.29s/it]

Epoch 28: loss = 57.052294564948525

 60%|█████████████████████████████████████████████████▏                                | 30/50 [02:35<01:45,  5.28s/it]

Epoch 29: loss = 54.48011385639159

 62%|██████████████████████████████████████████████████▊                               | 31/50 [02:40<01:40,  5.30s/it]

Epoch 30: loss = 52.16738446678979

 64%|████████████████████████████████████████████████████▍                             | 32/50 [02:45<01:34,  5.27s/it]

Epoch 31: loss = 50.06734053203649

 66%|██████████████████████████████████████████████████████                            | 33/50 [02:51<01:29,  5.29s/it]

Epoch 32: loss = 48.15425833110529

 68%|███████████████████████████████████████████████████████▊                          | 34/50 [02:56<01:24,  5.27s/it]

Epoch 33: loss = 46.415930061051654

 70%|█████████████████████████████████████████████████████████▍                        | 35/50 [03:01<01:19,  5.28s/it]

Epoch 34: loss = 44.81140480648299

 72%|███████████████████████████████████████████████████████████                       | 36/50 [03:06<01:13,  5.26s/it]

Epoch 35: loss = 43.34768595472622

 74%|████████████████████████████████████████████████████████████▋                     | 37/50 [03:12<01:08,  5.28s/it]

Epoch 36: loss = 42.02760117644988

 76%|██████████████████████████████████████████████████████████████▎                   | 38/50 [03:17<01:03,  5.26s/it]

Epoch 37: loss = 40.74212143512766

 78%|███████████████████████████████████████████████████████████████▉                  | 39/50 [03:22<00:58,  5.33s/it]

Epoch 38: loss = 39.59863770525391

 80%|█████████████████████████████████████████████████████████████████▌                | 40/50 [03:28<00:53,  5.31s/it]

Epoch 39: loss = 38.508415381588975

 82%|███████████████████████████████████████████████████████████████████▏              | 41/50 [03:33<00:47,  5.32s/it]

Epoch 40: loss = 37.519559171961525

 84%|████████████████████████████████████████████████████████████████████▉             | 42/50 [03:38<00:42,  5.30s/it]

Epoch 41: loss = 36.585096950387936

 86%|██████████████████████████████████████████████████████████████████████▌           | 43/50 [03:44<00:37,  5.30s/it]

Epoch 42: loss = 35.71948851960699

 88%|████████████████████████████████████████████████████████████████████████▏         | 44/50 [03:49<00:31,  5.29s/it]

Epoch 43: loss = 34.92177319313094

 90%|█████████████████████████████████████████████████████████████████████████▊        | 45/50 [03:54<00:26,  5.28s/it]

Epoch 44: loss = 34.15105237922426

 92%|███████████████████████████████████████████████████████████████████████████▍      | 46/50 [04:00<00:21,  5.33s/it]

Epoch 45: loss = 33.41451642639162

 94%|█████████████████████████████████████████████████████████████████████████████     | 47/50 [04:05<00:15,  5.32s/it]

Epoch 46: loss = 32.75492371077482

 96%|██████████████████████████████████████████████████████████████████████████████▋   | 48/50 [04:10<00:10,  5.30s/it]

Epoch 47: loss = 32.096116755737775

 98%|████████████████████████████████████████████████████████████████████████████████▎ | 49/50 [04:15<00:05,  5.30s/it]

Epoch 48: loss = 31.49043312106839

100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [04:21<00:00,  5.23s/it]

Epoch 49: loss = 30.943993460345496
glove_emb32_cfg2_deeptlf9: GLOVE EMB CALCULATED
glove_emb8_cfg2_quant100

glove_emb8_cfg2_quant100: DATA DISCRETIZED
['amount_rur', 'small_group', 'trans_date']
train started

  2%|█▋                                                                                 | 1/50 [00:07<06:02,  7.40s/it]

Epoch 0: loss = 8692.12163182675

  4%|███▎                                                                               | 2/50 [00:14<05:50,  7.30s/it]

Epoch 1: loss = 4514.603696736413

  6%|████▉                                                                              | 3/50 [00:21<05:40,  7.25s/it]

Epoch 2: loss = 2865.2654094051854

  8%|██████▋                                                                            | 4/50 [00:29<05:32,  7.22s/it]

Epoch 3: loss = 1910.487115736771

 10%|████████▎                                                                          | 5/50 [00:36<05:25,  7.23s/it]

Epoch 4: loss = 1316.3759659858626

 12%|█████████▉                                                                         | 6/50 [00:43<05:18,  7.23s/it]

Epoch 5: loss = 934.8272507301552

 14%|███████████▌                                                                       | 7/50 [00:50<05:10,  7.23s/it]

Epoch 6: loss = 684.2394957695069

 16%|█████████████▎                                                                     | 8/50 [00:57<05:03,  7.22s/it]

Epoch 7: loss = 516.3675375163426

 18%|██████████████▉                                                                    | 9/50 [01:05<04:59,  7.32s/it]

Epoch 8: loss = 401.44847059351935

 20%|████████████████▍                                                                 | 10/50 [01:12<04:55,  7.38s/it]

Epoch 9: loss = 321.301225194928

 22%|██████████████████                                                                | 11/50 [01:20<04:49,  7.43s/it]

Epoch 10: loss = 264.19760526954644

 24%|███████████████████▋                                                              | 12/50 [01:28<04:43,  7.47s/it]

Epoch 11: loss = 222.53484717924022

 26%|█████████████████████▎                                                            | 13/50 [01:35<04:37,  7.50s/it]

Epoch 12: loss = 191.4572082785565

 28%|██████████████████████▉                                                           | 14/50 [01:43<04:30,  7.53s/it]

Epoch 13: loss = 167.73425342820406

 30%|████████████████████████▌                                                         | 15/50 [01:50<04:23,  7.53s/it]

Epoch 14: loss = 149.24449725993514

 32%|██████████████████████████▏                                                       | 16/50 [01:58<04:16,  7.55s/it]

Epoch 15: loss = 134.52959233980332

 34%|███████████████████████████▉                                                      | 17/50 [02:05<04:09,  7.56s/it]

Epoch 16: loss = 122.6115599147615

 36%|█████████████████████████████▌                                                    | 18/50 [02:13<04:01,  7.56s/it]

Epoch 17: loss = 112.84230981153914

 38%|███████████████████████████████▏                                                  | 19/50 [02:21<03:54,  7.56s/it]

Epoch 18: loss = 104.66839209937841

 40%|████████████████████████████████▊                                                 | 20/50 [02:28<03:47,  7.57s/it]

Epoch 19: loss = 97.61762609211384

 42%|██████████████████████████████████▍                                               | 21/50 [02:36<03:40,  7.59s/it]

Epoch 20: loss = 91.65080014200745

 44%|████████████████████████████████████                                              | 22/50 [02:43<03:32,  7.58s/it]

Epoch 21: loss = 86.50043922318038

 46%|█████████████████████████████████████▋                                            | 23/50 [02:51<03:24,  7.58s/it]

Epoch 22: loss = 81.94220354263844

 48%|███████████████████████████████████████▎                                          | 24/50 [02:59<03:17,  7.59s/it]

Epoch 23: loss = 77.96444241390702

 50%|█████████████████████████████████████████                                         | 25/50 [03:06<03:09,  7.58s/it]

Epoch 24: loss = 74.38701636830966

 52%|██████████████████████████████████████████▋                                       | 26/50 [03:14<03:01,  7.57s/it]

Epoch 25: loss = 71.21710896384059

 54%|████████████████████████████████████████████▎                                     | 27/50 [03:21<02:53,  7.56s/it]

Epoch 26: loss = 68.3575128515467

 56%|█████████████████████████████████████████████▉                                    | 28/50 [03:29<02:46,  7.58s/it]

Epoch 27: loss = 65.78230913683348

 58%|███████████████████████████████████████████████▌                                  | 29/50 [03:36<02:39,  7.57s/it]

Epoch 28: loss = 63.43658762861752

 60%|█████████████████████████████████████████████████▏                                | 30/50 [03:44<02:31,  7.59s/it]

Epoch 29: loss = 61.301597816955116

 62%|██████████████████████████████████████████████████▊                               | 31/50 [03:52<02:23,  7.58s/it]

Epoch 30: loss = 59.34617771224492

 64%|████████████████████████████████████████████████████▍                             | 32/50 [03:59<02:16,  7.58s/it]

Epoch 31: loss = 57.555389500024596

 66%|██████████████████████████████████████████████████████                            | 33/50 [04:07<02:08,  7.56s/it]

Epoch 32: loss = 55.94442123130039

 68%|███████████████████████████████████████████████████████▊                          | 34/50 [04:14<02:01,  7.56s/it]

Epoch 33: loss = 54.38327364695959

 70%|█████████████████████████████████████████████████████████▍                        | 35/50 [04:22<01:53,  7.55s/it]

Epoch 34: loss = 52.97868322151084

 72%|███████████████████████████████████████████████████████████                       | 36/50 [04:29<01:45,  7.56s/it]

Epoch 35: loss = 51.675493931130404

 74%|████████████████████████████████████████████████████████████▋                     | 37/50 [04:37<01:38,  7.57s/it]

Epoch 36: loss = 50.45813865762476

 76%|██████████████████████████████████████████████████████████████▎                   | 38/50 [04:45<01:31,  7.66s/it]

Epoch 37: loss = 49.34407528085755

 78%|███████████████████████████████████████████████████████████████▉                  | 39/50 [04:52<01:24,  7.67s/it]

Epoch 38: loss = 48.27943249478967

 80%|█████████████████████████████████████████████████████████████████▌                | 40/50 [05:00<01:16,  7.69s/it]

Epoch 39: loss = 47.294758348134884

 82%|███████████████████████████████████████████████████████████████████▏              | 41/50 [05:08<01:09,  7.68s/it]

Epoch 40: loss = 46.37285134058184

 84%|████████████████████████████████████████████████████████████████████▉             | 42/50 [05:16<01:01,  7.68s/it]

Epoch 41: loss = 45.50788564591436

 86%|██████████████████████████████████████████████████████████████████████▌           | 43/50 [05:23<00:53,  7.67s/it]

Epoch 42: loss = 44.69855689215354

 88%|████████████████████████████████████████████████████████████████████████▏         | 44/50 [05:31<00:46,  7.69s/it]

Epoch 43: loss = 43.92983610561316

 90%|█████████████████████████████████████████████████████████████████████████▊        | 45/50 [05:39<00:38,  7.68s/it]

Epoch 44: loss = 43.21893169091774

 92%|███████████████████████████████████████████████████████████████████████████▍      | 46/50 [05:46<00:30,  7.68s/it]

Epoch 45: loss = 42.53262000585576

 94%|█████████████████████████████████████████████████████████████████████████████     | 47/50 [05:54<00:23,  7.67s/it]

Epoch 46: loss = 41.891171921900856

 96%|██████████████████████████████████████████████████████████████████████████████▋   | 48/50 [06:02<00:15,  7.67s/it]

Epoch 47: loss = 41.28462534876947

 98%|████████████████████████████████████████████████████████████████████████████████▎ | 49/50 [06:09<00:07,  7.65s/it]

Epoch 48: loss = 40.717737070062114

100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [06:17<00:00,  7.55s/it]

Epoch 49: loss = 40.16375074392016
glove_emb8_cfg2_quant100: GLOVE EMB CALCULATED
glove_emb24_cfg2_quant100

glove_emb24_cfg2_quant100: DATA DISCRETIZED
['amount_rur', 'small_group', 'trans_date']
train started

  2%|█▋                                                                                 | 1/50 [00:07<06:02,  7.40s/it]

Epoch 0: loss = 10863.50620062906

  4%|███▎                                                                               | 2/50 [00:14<05:51,  7.32s/it]

Epoch 1: loss = 5024.053770890952

  6%|████▉                                                                              | 3/50 [00:21<05:43,  7.30s/it]

Epoch 2: loss = 2983.53067430026

  8%|██████▋                                                                            | 4/50 [00:29<05:33,  7.25s/it]

Epoch 3: loss = 1919.5544758438425

 10%|████████▎                                                                          | 5/50 [00:36<05:26,  7.26s/it]

Epoch 4: loss = 1320.8966423812767

 12%|█████████▉                                                                         | 6/50 [00:43<05:18,  7.25s/it]

Epoch 5: loss = 964.8133755070623

 14%|███████████▌                                                                       | 7/50 [00:50<05:11,  7.24s/it]

Epoch 6: loss = 740.717238773095

 16%|█████████████▎                                                                     | 8/50 [00:58<05:03,  7.23s/it]

Epoch 7: loss = 591.636378998611

 18%|██████████████▉                                                                    | 9/50 [01:05<05:01,  7.34s/it]

Epoch 8: loss = 487.4661414257915

 20%|████████████████▍                                                                 | 10/50 [01:13<04:57,  7.44s/it]

Epoch 9: loss = 411.4838027118903

 22%|██████████████████                                                                | 11/50 [01:20<04:52,  7.50s/it]

Epoch 10: loss = 353.9574145232054

 24%|███████████████████▋                                                              | 12/50 [01:28<04:45,  7.53s/it]

Epoch 11: loss = 309.12895003599283

 26%|█████████████████████▎                                                            | 13/50 [01:36<04:39,  7.56s/it]

Epoch 12: loss = 273.4238318019159

 28%|██████████████████████▉                                                           | 14/50 [01:43<04:33,  7.59s/it]

Epoch 13: loss = 244.18373806248482

 30%|████████████████████████▌                                                         | 15/50 [01:51<04:25,  7.58s/it]

Epoch 14: loss = 219.93091094617833

 32%|██████████████████████████▏                                                       | 16/50 [01:58<04:18,  7.59s/it]

Epoch 15: loss = 199.6859345472698

 34%|███████████████████████████▉                                                      | 17/50 [02:06<04:11,  7.61s/it]

Epoch 16: loss = 182.42162527631697

 36%|█████████████████████████████▌                                                    | 18/50 [02:14<04:03,  7.61s/it]

Epoch 17: loss = 167.65442275750544

 38%|███████████████████████████████▏                                                  | 19/50 [02:21<03:55,  7.61s/it]

Epoch 18: loss = 154.8942117583991

 40%|████████████████████████████████▊                                                 | 20/50 [02:29<03:48,  7.61s/it]

Epoch 19: loss = 143.82810977408937

 42%|██████████████████████████████████▍                                               | 21/50 [02:37<03:40,  7.62s/it]

Epoch 20: loss = 134.04054809396428

 44%|████████████████████████████████████                                              | 22/50 [02:45<03:36,  7.73s/it]

Epoch 21: loss = 125.4170430534353

 46%|█████████████████████████████████████▋                                            | 23/50 [02:52<03:27,  7.69s/it]

Epoch 22: loss = 117.79779746221968

 48%|███████████████████████████████████████▎                                          | 24/50 [03:00<03:19,  7.68s/it]

Epoch 23: loss = 111.00624988675908

 50%|█████████████████████████████████████████                                         | 25/50 [03:08<03:11,  7.67s/it]

Epoch 24: loss = 104.92922468036694

 52%|██████████████████████████████████████████▋                                       | 26/50 [03:15<03:03,  7.66s/it]

Epoch 25: loss = 99.47713646635937

 54%|████████████████████████████████████████████▎                                     | 27/50 [03:23<02:56,  7.66s/it]

Epoch 26: loss = 94.57331990769183

 56%|█████████████████████████████████████████████▉                                    | 28/50 [03:30<02:48,  7.64s/it]

Epoch 27: loss = 90.10402314073256

 58%|███████████████████████████████████████████████▌                                  | 29/50 [03:38<02:40,  7.63s/it]

Epoch 28: loss = 86.09287854221508

 60%|█████████████████████████████████████████████████▏                                | 30/50 [03:46<02:32,  7.64s/it]

Epoch 29: loss = 82.38670733423626

 62%|██████████████████████████████████████████████████▊                               | 31/50 [03:53<02:24,  7.62s/it]

Epoch 30: loss = 79.00530176960253

 64%|████████████████████████████████████████████████████▍                             | 32/50 [04:01<02:17,  7.62s/it]

Epoch 31: loss = 75.91915362937311

 66%|██████████████████████████████████████████████████████                            | 33/50 [04:09<02:09,  7.63s/it]

Epoch 32: loss = 73.32813751932193

 68%|███████████████████████████████████████████████████████▊                          | 34/50 [04:16<02:02,  7.64s/it]

Epoch 33: loss = 70.48094549401125

 70%|█████████████████████████████████████████████████████████▍                        | 35/50 [04:24<01:54,  7.64s/it]

Epoch 34: loss = 68.0660246725259

 72%|███████████████████████████████████████████████████████████                       | 36/50 [04:31<01:46,  7.64s/it]

Epoch 35: loss = 65.84681242310025

 74%|████████████████████████████████████████████████████████████▋                     | 37/50 [04:39<01:39,  7.68s/it]

Epoch 36: loss = 63.77298356119465

 76%|██████████████████████████████████████████████████████████████▎                   | 38/50 [04:47<01:32,  7.71s/it]

Epoch 37: loss = 61.85372490393276

 78%|███████████████████████████████████████████████████████████████▉                  | 39/50 [04:55<01:24,  7.72s/it]

Epoch 38: loss = 60.09545902958144

 80%|█████████████████████████████████████████████████████████████████▌                | 40/50 [05:02<01:17,  7.73s/it]

Epoch 39: loss = 58.41248726802698

 82%|███████████████████████████████████████████████████████████████████▏              | 41/50 [05:10<01:09,  7.71s/it]

Epoch 40: loss = 56.8514189754945

 84%|████████████████████████████████████████████████████████████████████▉             | 42/50 [05:18<01:02,  7.85s/it]

Epoch 41: loss = 55.39482886122786

 86%|██████████████████████████████████████████████████████████████████████▌           | 43/50 [05:27<00:55,  7.96s/it]

Epoch 42: loss = 54.02904329915021

 88%|████████████████████████████████████████████████████████████████████████▏         | 44/50 [05:34<00:47,  7.89s/it]

Epoch 43: loss = 52.752076536903964

 90%|█████████████████████████████████████████████████████████████████████████▊        | 45/50 [05:42<00:39,  7.83s/it]

Epoch 44: loss = 51.54623394828254

 92%|███████████████████████████████████████████████████████████████████████████▍      | 46/50 [05:50<00:31,  7.84s/it]

Epoch 45: loss = 50.40762163558036

 94%|█████████████████████████████████████████████████████████████████████████████     | 47/50 [05:58<00:23,  7.81s/it]

Epoch 46: loss = 49.33560812824643

 96%|██████████████████████████████████████████████████████████████████████████████▋   | 48/50 [06:05<00:15,  7.79s/it]

Epoch 47: loss = 48.325789577263

 98%|████████████████████████████████████████████████████████████████████████████████▎ | 49/50 [06:13<00:07,  7.77s/it]

Epoch 48: loss = 47.36690512481933

100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [06:21<00:00,  7.62s/it]

Epoch 49: loss = 46.45902138534087
glove_emb24_cfg2_quant100: GLOVE EMB CALCULATED
glove_emb32_cfg2_quant100

glove_emb32_cfg2_quant100: DATA DISCRETIZED
['amount_rur', 'small_group', 'trans_date']
train started

  2%|█▋                                                                                 | 1/50 [00:07<06:04,  7.44s/it]

Epoch 0: loss = 11815.267975520712

  4%|███▎                                                                               | 2/50 [00:14<05:53,  7.36s/it]

Epoch 1: loss = 5428.826777569521

  6%|████▉                                                                              | 3/50 [00:22<05:46,  7.37s/it]

Epoch 2: loss = 3230.1978632546384

  8%|██████▋                                                                            | 4/50 [00:29<05:37,  7.33s/it]

Epoch 3: loss = 2110.1136925971136

 10%|████████▎                                                                          | 5/50 [00:36<05:29,  7.31s/it]

Epoch 4: loss = 1490.99537318653

 12%|█████████▉                                                                         | 6/50 [00:43<05:20,  7.28s/it]

Epoch 5: loss = 1122.4388318983329

 14%|███████████▌                                                                       | 7/50 [00:51<05:12,  7.27s/it]

Epoch 6: loss = 886.6680615828733

 16%|█████████████▎                                                                     | 8/50 [00:58<05:05,  7.29s/it]

Epoch 7: loss = 725.8156078421218

 18%|██████████████▉                                                                    | 9/50 [01:06<05:03,  7.40s/it]

Epoch 8: loss = 610.0596145348134

 20%|████████████████▍                                                                 | 10/50 [01:13<04:58,  7.47s/it]

Epoch 9: loss = 523.0270563071824

 22%|██████████████████                                                                | 11/50 [01:21<04:53,  7.52s/it]

Epoch 10: loss = 455.396507767737

 24%|███████████████████▋                                                              | 12/50 [01:29<04:47,  7.57s/it]

Epoch 11: loss = 401.27894380770005

 26%|█████████████████████▎                                                            | 13/50 [01:36<04:40,  7.59s/it]

Epoch 12: loss = 357.16793552369023

 28%|██████████████████████▉                                                           | 14/50 [01:44<04:32,  7.58s/it]

Epoch 13: loss = 320.60269577825795

 30%|████████████████████████▌                                                         | 15/50 [01:51<04:26,  7.60s/it]

Epoch 14: loss = 289.7676699239722

 32%|██████████████████████████▏                                                       | 16/50 [01:59<04:18,  7.62s/it]

Epoch 15: loss = 263.5118161269318

 34%|███████████████████████████▉                                                      | 17/50 [02:07<04:11,  7.63s/it]

Epoch 16: loss = 240.91928892166908

 36%|█████████████████████████████▌                                                    | 18/50 [02:14<04:03,  7.61s/it]

Epoch 17: loss = 221.36402353523135

 38%|███████████████████████████████▏                                                  | 19/50 [02:22<03:56,  7.63s/it]

Epoch 18: loss = 204.29966273359585

 40%|████████████████████████████████▊                                                 | 20/50 [02:30<03:49,  7.64s/it]

Epoch 19: loss = 189.2624657195012

 42%|██████████████████████████████████▍                                               | 21/50 [02:37<03:41,  7.64s/it]

Epoch 20: loss = 176.08825583376884

 44%|████████████████████████████████████                                              | 22/50 [02:45<03:33,  7.62s/it]

Epoch 21: loss = 164.22465483078966

 46%|█████████████████████████████████████▋                                            | 23/50 [02:52<03:25,  7.62s/it]

Epoch 22: loss = 153.72759752255757

 48%|███████████████████████████████████████▎                                          | 24/50 [03:00<03:18,  7.63s/it]

Epoch 23: loss = 144.30649440129474

 50%|█████████████████████████████████████████                                         | 25/50 [03:08<03:11,  7.64s/it]

Epoch 24: loss = 135.83467005942038

 52%|██████████████████████████████████████████▋                                       | 26/50 [03:15<03:02,  7.62s/it]

Epoch 25: loss = 128.2340783987626

 54%|████████████████████████████████████████████▎                                     | 27/50 [03:23<02:55,  7.63s/it]

Epoch 26: loss = 121.2680564667494

 56%|█████████████████████████████████████████████▉                                    | 28/50 [03:31<02:48,  7.64s/it]

Epoch 27: loss = 114.97457757556884

 58%|███████████████████████████████████████████████▌                                  | 29/50 [03:38<02:40,  7.63s/it]

Epoch 28: loss = 109.24507781420148

 60%|█████████████████████████████████████████████████▏                                | 30/50 [03:46<02:32,  7.62s/it]

Epoch 29: loss = 104.01784037185548

 62%|██████████████████████████████████████████████████▊                               | 31/50 [03:53<02:24,  7.62s/it]

Epoch 30: loss = 99.21300065229673

 64%|████████████████████████████████████████████████████▍                             | 32/50 [04:01<02:17,  7.62s/it]

Epoch 31: loss = 94.81190770488709

 66%|██████████████████████████████████████████████████████                            | 33/50 [04:09<02:09,  7.63s/it]

Epoch 32: loss = 90.7510097583138

 68%|███████████████████████████████████████████████████████▊                          | 34/50 [04:16<02:02,  7.63s/it]

Epoch 33: loss = 87.02744009175224

 70%|█████████████████████████████████████████████████████████▍                        | 35/50 [04:24<01:54,  7.62s/it]

Epoch 34: loss = 83.56081761629657

 72%|███████████████████████████████████████████████████████████                       | 36/50 [04:32<01:46,  7.64s/it]

Epoch 35: loss = 80.38685575556265

 74%|████████████████████████████████████████████████████████████▋                     | 37/50 [04:39<01:39,  7.67s/it]

Epoch 36: loss = 77.3906480070797

 76%|██████████████████████████████████████████████████████████████▎                   | 38/50 [04:47<01:32,  7.67s/it]

Epoch 37: loss = 74.62839118476037

 78%|███████████████████████████████████████████████████████████████▉                  | 39/50 [04:55<01:24,  7.68s/it]

Epoch 38: loss = 72.06134225106317

 80%|█████████████████████████████████████████████████████████████████▌                | 40/50 [05:03<01:16,  7.69s/it]

Epoch 39: loss = 69.67792976902699

 82%|███████████████████████████████████████████████████████████████████▏              | 41/50 [05:10<01:09,  7.72s/it]

Epoch 40: loss = 67.44127911560508

 84%|████████████████████████████████████████████████████████████████████▉             | 42/50 [05:18<01:01,  7.72s/it]

Epoch 41: loss = 65.32691444445655

 86%|██████████████████████████████████████████████████████████████████████▌           | 43/50 [05:26<00:54,  7.72s/it]

Epoch 42: loss = 63.36681462736337

 88%|████████████████████████████████████████████████████████████████████████▏         | 44/50 [05:33<00:46,  7.72s/it]

Epoch 43: loss = 61.52897074336739

 90%|█████████████████████████████████████████████████████████████████████████▊        | 45/50 [05:41<00:38,  7.72s/it]

Epoch 44: loss = 59.79323082499543

 92%|███████████████████████████████████████████████████████████████████████████▍      | 46/50 [05:49<00:30,  7.71s/it]

Epoch 45: loss = 58.20613057007101

 94%|█████████████████████████████████████████████████████████████████████████████     | 47/50 [05:57<00:23,  7.71s/it]

Epoch 46: loss = 56.64901951088109

 96%|██████████████████████████████████████████████████████████████████████████████▋   | 48/50 [06:04<00:15,  7.72s/it]

Epoch 47: loss = 55.17712566725661

 98%|████████████████████████████████████████████████████████████████████████████████▎ | 49/50 [06:12<00:07,  7.74s/it]

Epoch 48: loss = 53.81499348589217

100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [06:20<00:00,  7.61s/it]

Epoch 49: loss = 52.52339835472317
glove_emb32_cfg2_quant100: GLOVE EMB CALCULATED

In [15]:
glove_embedding.load()

In [9]:
data = glove_embedding.tokenize_data(data)

In [4]:
EMBED_SIZE = 16
disc_quant100 = KDiscretizer(
    f_names = ['amount_rur'],
    k_bins = 100,
    d_type = 'quantile'
)

disc_uni100 = KDiscretizer(
    f_names = ['amount_rur'],
    k_bins = 100,
    d_type = 'uniform'
)

disc_kmeans100 = KDiscretizer(
    f_names = ['amount_rur'],
    k_bins = 100,
    d_type = 'kmeans'
)

disc_st100 = SingleTreeDiscretizer(
    f_names = ['amount_rur'], 
    target_name = 'bins', 
    target_type = 'classification', 
    k_bins = [100],
)

disc_quant30 = KDiscretizer(
    f_names = ['amount_rur'],
    k_bins = 30,
    d_type = 'quantile',
    emb_sz = EMBED_SIZE
)

disc_uni30 = KDiscretizer(
    f_names = ['amount_rur'],
    k_bins = 30,
    d_type = 'uniform',
    emb_sz = EMBED_SIZE
)

disc_kmeans30 = KDiscretizer(
    f_names = ['amount_rur'],
    k_bins = 30,
    d_type = 'kmeans',
    emb_sz = EMBED_SIZE
)

disc_st30 = SingleTreeDiscretizer(
    f_names = ['amount_rur'], 
    target_name = 'bins', 
    target_type = 'classification', 
    k_bins = [30],
    emb_sz = EMBED_SIZE
)

In [5]:
experiments = [
    {'name' : 'quant_num_emb_dist_common_emb_cat', 
     'agg_type' : 'cat', 
     'disc' : disc_quant30,
     'nemb' : True
    },
    {'name' : 'quant_num_emb_dist_common_emb_sum', 
     'agg_type' : 'sum', 
     'disc' : disc_quant30,
     'nemb' : True
    },
    {'name' : 'quant_num_emb_dist_common_emb_mean', 
     'agg_type' : 'mean', 
     'disc' : disc_quant30,
     'nemb' : True
    },
    {'name' : 'uni_num_emb_dist_common_emb_cat', 
     'agg_type' : 'cat', 
     'disc' : disc_uni30,
     'nemb' : True
    },
    {'name' : 'uni_num_emb_dist_common_emb_sum', 
     'agg_type' : 'sum', 
     'disc' : disc_uni30,
     'nemb' : True
    },
    {'name' : 'uni_num_emb_dist_common_emb_mean', 
     'agg_type' : 'mean', 
     'disc' : disc_uni30,
     'nemb' : True
    },
    {'name' : 'kmeans_num_emb_dist_common_emb_cat', 
     'agg_type' : 'cat', 
     'disc' : disc_kmeans30,
     'nemb' : True
    },
    {'name' : 'kmeans_num_emb_dist_common_emb_sum', 
     'agg_type' : 'sum', 
     'disc' : disc_kmeans30,
     'nemb' : True
    },
    {'name' : 'kmeans_num_emb_dist_common_emb_mean', 
     'agg_type' : 'mean', 
     'disc' : disc_kmeans30,
     'nemb' : True
    },
    {'name' : 'st_num_emb_dist_common_emb_cat', 
     'agg_type' : 'cat', 
     'disc' : disc_st30,
     'nemb' : True
    },
    {'name' : 'st_num_emb_dist_common_emb_sum', 
     'agg_type' : 'sum', 
     'disc' : disc_st30,
     'nemb' : True
    },
    {'name' : 'st_num_emb_dist_common_emb_mean', 
     'agg_type' : 'mean', 
     'disc' : disc_st30,
     'nemb' : True
    },
    {'name' : 'st_100_dist_common_emb_cat', 
     'agg_type' : 'cat', 
     'disc' : disc_st100,
     'nemb' : False
    },
    {'name' : 'st_100_dist_common_emb_sum', 
     'agg_type' : 'sum', 
     'disc' : disc_st100,
     'nemb' : False
    },
    {'name' : 'st_100_dist_common_emb_mean', 
     'agg_type' : 'mean', 
     'disc' : disc_st100,
     'nemb' : False
    },
    {'name' : 'quant_100_dist_common_emb_cat', 
     'agg_type' : 'cat', 
     'disc' : disc_quant100,
     'nemb' : False
    },
    {'name' : 'quant_100_dist_common_emb_sum', 
     'agg_type' : 'sum', 
     'disc' : disc_quant100,
     'nemb' : False
    },
    {'name' : 'quant_100_dist_common_emb_mean', 
     'agg_type' : 'mean', 
     'disc' : disc_quant100,
     'nemb' : False
    },
    {'name' : 'uni_100_dist_common_emb_cat', 
     'agg_type' : 'cat', 
     'disc' : disc_uni100,
     'nemb' : False
    },
    {'name' : 'uni_100_dist_common_emb_sum', 
     'agg_type' : 'sum', 
     'disc' : disc_uni100,
     'nemb' : False
    },
    {'name' : 'uni_100_dist_common_emb_mean', 
     'agg_type' : 'mean', 
     'disc' : disc_uni100,
     'nemb' : False
    },
    {'name' : 'kmeans_100_dist_common_emb_cat', 
     'agg_type' : 'cat', 
     'disc' : disc_kmeans100,
     'nemb' : False
    },
    {'name' : 'kmeans_100_dist_common_emb_sum', 
     'agg_type' : 'sum', 
     'disc' : disc_kmeans100,
     'nemb' : False
    },
    {'name' : 'kmeans_100_dist_common_emb_mean', 
     'agg_type' : 'mean', 
     'disc' : disc_kmeans100,
     'nemb' : False
    },
]

In [ ]:
#Deeptfl only disc
EMBED_SIZE = 16
df_params = {'numeric_cols': ['amount_rur'],
     'cat_cols': ['small_group'],
     'date_col': 'trans_date',
     'cat_unique': [202, 730],
     'id_col': 'client_id'}

deeptlf_params3 = DeepTLFDisc({"n_est" : 3,
                  "min_freq" : 2,
                  "features" : df_params['numeric_cols'] + df_params['cat_cols'],
                  "features_to_split" : df_params['numeric_cols']
                  })
deeptlf_params6 = DeepTLFDisc({"n_est" : 6,
                  "min_freq" : 2,
                  "features" : df_params['numeric_cols'] + df_params['cat_cols'],
                  "features_to_split" : df_params['numeric_cols'],
                  })
deeptlf_params9 = DeepTLFDisc({"n_est" : 9,
                  "min_freq" : 2,
                  "features" : df_params['numeric_cols'] + df_params['cat_cols'],
                  "features_to_split" : df_params['numeric_cols'],
                  })

deeptlf_params3_ne = DeepTLFDisc({"n_est" : 3,
                  "min_freq" : 2,
                  "features" : df_params['numeric_cols'] + df_params['cat_cols'],
                  "features_to_split" : df_params['numeric_cols'],
                  "emb_size" : EMBED_SIZE})
deeptlf_params6_ne = DeepTLFDisc({"n_est" : 6,
                  "min_freq" : 2,
                  "features" : df_params['numeric_cols'] + df_params['cat_cols'],
                  "features_to_split" : df_params['numeric_cols'],
                  "emb_size" : EMBED_SIZE})
deeptlf_params9_ne = DeepTLFDisc({"n_est" : 9,
                  "min_freq" : 2,
                  "features" : df_params['numeric_cols'] + df_params['cat_cols'],
                  "features_to_split" : df_params['numeric_cols'],
                  "emb_size" : EMBED_SIZE})

experiments = [
    {'name' : 'deeptlf3_disc_common_emb_cat',
     'agg_type' : 'cat',
     'disc' : deeptlf_params3,
     'nemb' : False
    },
    {'name' : 'deeptlf6_disc_common_emb_sum',
     'agg_type' : 'sum',
     'disc' : deeptlf_params6,
     'nemb' : False
    },
    {'name' : 'deeptlf9_disc_common_emb_mean',
     'agg_type' : 'mean',
     'disc' : deeptlf_params9,
     'nemb' : False
    },
    {'name' : 'deeptlf3_num_emb_disc_common_emb_cat',
     'agg_type' : 'cat',
     'disc' : deeptlf_params3_ne,
     'nemb' : True
    },
    {'name' : 'deeptlf6_num_emb_disc_common_emb_sum',
     'agg_type' : 'sum',
     'disc' : deeptlf_params6_ne,
     'nemb' : True
    },
    {'name' : 'deeptlf9_num_emb_disc_common_emb_mean',
     'agg_type' : 'mean',
     'disc' : deeptlf_params9_ne,
     'nemb' : True
    },
]

### Experiments with sole numeric features discretization and common embeds

In [5]:
EMBED_SIZE = 16
HIDDEN_SIZE = 256

def get_basic_model_encoder(df_params):
    embeddings=dict()
    for i, f in enumerate(df_params["cat_cols"] + [df_params["date_col"]]):
        embeddings[f] = {'in' : df_params["cat_unique"][i], 'out' : EMBED_SIZE}
    
    trx_encoder_params = dict(
        embeddings_noise=0.003,
        numeric_values=dict([(fe, 'identity') for fe in df_params['numeric_cols']]),
        embeddings=embeddings
    )
    
    seq_encoder = RnnSeqEncoder(
        trx_encoder=TrxEncoder(**trx_encoder_params),
        hidden_size=256,
        type='gru',
    )
    
    return seq_encoder

def get_cat_encoder(df_params, agg_type, num_emb_flag=False):
    embeddings=dict()
    for i, f in enumerate(df_params["cat_cols"] + [df_params["date_col"]]):
        embeddings[f] = {'in' : df_params["cat_unique"][i], 'out' : EMBED_SIZE}

    trx_encoder_params = dict(
        embeddings=embeddings,
        embeddings_noise=0.003,
        agg_type=agg_type,
        numeric_separate=num_emb_flag,
        numeric_features=df_params['numeric_cols']
    )
    
    seq_encoder = RnnSeqEncoder(
        trx_encoder=TrxEncoderCat(**trx_encoder_params),
        hidden_size=HIDDEN_SIZE,
        type='gru',
    )
    return seq_encoder

def get_trans_encoder(df_params, agg_type, algo, numeric_separate=False):
    embeddings=dict()

    trx_encoder_params = dict(
        feature_names=df_params['cat_cols'] + [df_params["date_col"]], 
        in_emb_sizes=df_params["cat_unique"],
        out_emb_size=EMBED_SIZE,
        agg_type=agg_type,
        numeric_separate=numeric_separate,
        numeric_features=df_params['numeric_cols']
    )
    
    seq_encoder = RnnSeqEncoder(
        trx_encoder=TrxEncoderTrans(**trx_encoder_params),
        hidden_size=HIDDEN_SIZE,
        type='gru',
    )
    return seq_encoder

def get_glove_encoder(df_params, exp, glove_embedding):
    seq_encoder = RnnSeqEncoder(
        trx_encoder=TrxEncoderGlove(glove_embedding, agg_type=exp['agg_type'], numeric_separate=exp['nsep']),
        hidden_size=256,
        type='gru',
    )
    return seq_encoder

In [6]:
disc_quant100 = KDiscretizer(
    f_names = ['amount_rur'],
    k_bins = 100,
    d_type = 'quantile'
)

deeptlf_params9 = DeepTLFDisc({"n_est" : 9,
                  "min_freq" : 2,
                  "features" : df_params['numeric_cols'] + df_params['cat_cols'],
                  "features_to_split" : df_params['numeric_cols'],
                  })

experiments = [
    {
     'name' : 'trx_tran_orig_no_disc',
     'algo' : 'orig',
     'agg_type' : None,
     'nsep' : False,
    },
    {
     'name' : 'trx_tran_orig_deeptlf9',
     'algo' : 'orig',
     'agg_type' : None,
     'nsep' : False,
     'disc' : copy.deepcopy(deeptlf_params9),
     'nemb' : False
    },
    {
     'name' : 'trx_tran_classic_deeptlf9_cat',
     'algo' : 'classic',
     'agg_type' : 'cat',
     'nsep' : False,
     'disc' : copy.deepcopy(deeptlf_params9),
     'nemb' : False
    },
    {
     'name' : 'trx_tran_classic_quant100_sum',
     'algo' : 'classic',
     'agg_type' : 'sum',
     'nsep' : False,
     'disc' : copy.deepcopy(disc_quant100),
     'nemb' : False
    },
    {
     'name' : 'trx_tran_orig_quant100',
     'algo' : 'orig',
     'agg_type' : None,
     'nsep' : False,
     'disc' : copy.deepcopy(disc_quant100),
     'nemb' : False
    },
    {
     'name' : 'trx_tran_classic_quant100_cat',
     'algo' : 'classic',
     'agg_type' : 'cat',
     'nsep' : False,
     'disc' : copy.deepcopy(disc_quant100),
     'nemb' : False
    },
      {
     'name' : 'trx_tran_classic_deeptlf9_sum',
     'algo' : 'classic',
     'agg_type' : 'sum',
     'nsep' : False,
     'disc' : copy.deepcopy(deeptlf_params9),
     'nemb' : False
    },
     {
     'name' : 'trx_tran_classic_deeptlf9_mean',
     'algo' : 'classic',
     'agg_type' : 'mean',
     'nsep' : False,
     'disc' : copy.deepcopy(deeptlf_params9),
     'nemb' : False
    },
    {
     'name' : 'trx_tran_classic_quant100_mean',
     'algo' : 'classic',
     'agg_type' : 'mean',
     'nsep' : False,
     'disc' : copy.deepcopy(disc_quant100),
     'nemb' : False
    },
    {
     'name' : 'trx_tran_classic_no_disc_cat',
     'algo' : 'classic',
     'agg_type' : 'cat',
     'nsep' : True,
    }
]

In [6]:
experiments_glove = []
for e in experiments:
    for agg_t in ['cat', 'sum', 'mean']:
        if agg_t != 'cat' and e['disc'] is None:
            continue
        experiments_glove.append(copy.deepcopy(e))
        experiments_glove[-1]['agg_type'] = agg_t
        experiments_glove[-1]['nsep'] = (experiments_glove[-1]['disc'] is None)
        experiments_glove[-1]['name'] += f'_{agg_t}'

In [7]:
experiments_glove

[{'name': 'glove_emb8_cfg2_deeptlf9_cat',
  'glove_config': {'alpha': 0.75,
   'x_max': 15000,
   'embedding_size': 8,
   'num_epochs_train': 50},
  'disc': <ptls.preprocessing.deeptlf.deeptlf_discretizer.DeepTLFDisc at 0x262ee0cab00>,
  'agg_type': 'cat',
  'nsep': False},
 {'name': 'glove_emb8_cfg2_deeptlf9_sum',
  'glove_config': {'alpha': 0.75,
   'x_max': 15000,
   'embedding_size': 8,
   'num_epochs_train': 50},
  'disc': <ptls.preprocessing.deeptlf.deeptlf_discretizer.DeepTLFDisc at 0x262ee0ca3b0>,
  'agg_type': 'sum',
  'nsep': False},
 {'name': 'glove_emb8_cfg2_deeptlf9_mean',
  'glove_config': {'alpha': 0.75,
   'x_max': 15000,
   'embedding_size': 8,
   'num_epochs_train': 50},
  'disc': <ptls.preprocessing.deeptlf.deeptlf_discretizer.DeepTLFDisc at 0x262ef125240>,
  'agg_type': 'mean',
  'nsep': False},
 {'name': 'glove_emb24_cfg2_deeptlf9_cat',
  'glove_config': {'alpha': 0.75,
   'x_max': 15000,
   'embedding_size': 24,
   'num_epochs_train': 50},
  'disc': <ptls.preprocessing.deeptlf.deeptlf_discretizer.DeepTLFDisc at 0x262ef1251e0>,
  'agg_type': 'cat',
  'nsep': False},
 {'name': 'glove_emb24_cfg2_deeptlf9_sum',
  'glove_config': {'alpha': 0.75,
   'x_max': 15000,
   'embedding_size': 24,
   'num_epochs_train': 50},
  'disc': <ptls.preprocessing.deeptlf.deeptlf_discretizer.DeepTLFDisc at 0x262ef127fa0>,
  'agg_type': 'sum',
  'nsep': False},
 {'name': 'glove_emb24_cfg2_deeptlf9_mean',
  'glove_config': {'alpha': 0.75,
   'x_max': 15000,
   'embedding_size': 24,
   'num_epochs_train': 50},
  'disc': <ptls.preprocessing.deeptlf.deeptlf_discretizer.DeepTLFDisc at 0x262ef127df0>,
  'agg_type': 'mean',
  'nsep': False},
 {'name': 'glove_emb32_cfg2_deeptlf9_cat',
  'glove_config': {'alpha': 0.75,
   'x_max': 15000,
   'embedding_size': 32,
   'num_epochs_train': 50},
  'disc': <ptls.preprocessing.deeptlf.deeptlf_discretizer.DeepTLFDisc at 0x262ef124d30>,
  'agg_type': 'cat',
  'nsep': False},
 {'name': 'glove_emb32_cfg2_deeptlf9_sum',
  'glove_config': {'alpha': 0.75,
   'x_max': 15000,
   'embedding_size': 32,
   'num_epochs_train': 50},
  'disc': <ptls.preprocessing.deeptlf.deeptlf_discretizer.DeepTLFDisc at 0x262ef124df0>,
  'agg_type': 'sum',
  'nsep': False},
 {'name': 'glove_emb32_cfg2_deeptlf9_mean',
  'glove_config': {'alpha': 0.75,
   'x_max': 15000,
   'embedding_size': 32,
   'num_epochs_train': 50},
  'disc': <ptls.preprocessing.deeptlf.deeptlf_discretizer.DeepTLFDisc at 0x262ef125360>,
  'agg_type': 'mean',
  'nsep': False},
 {'name': 'glove_emb8_cfg2_quant100_cat',
  'glove_config': {'alpha': 0.75,
   'x_max': 15000,
   'embedding_size': 8,
   'num_epochs_train': 50},
  'disc': <ptls.preprocessing.baseline_discretizer.k_discretizer.KDiscretizer at 0x262ef125390>,
  'agg_type': 'cat',
  'nsep': False},
 {'name': 'glove_emb8_cfg2_quant100_sum',
  'glove_config': {'alpha': 0.75,
   'x_max': 15000,
   'embedding_size': 8,
   'num_epochs_train': 50},
  'disc': <ptls.preprocessing.baseline_discretizer.k_discretizer.KDiscretizer at 0x262ef1261a0>,
  'agg_type': 'sum',
  'nsep': False},
 {'name': 'glove_emb8_cfg2_quant100_mean',
  'glove_config': {'alpha': 0.75,
   'x_max': 15000,
   'embedding_size': 8,
   'num_epochs_train': 50},
  'disc': <ptls.preprocessing.baseline_discretizer.k_discretizer.KDiscretizer at 0x262ef125210>,
  'agg_type': 'mean',
  'nsep': False},
 {'name': 'glove_emb24_cfg2_quant100_cat',
  'glove_config': {'alpha': 0.75,
   'x_max': 15000,
   'embedding_size': 24,
   'num_epochs_train': 50},
  'disc': <ptls.preprocessing.baseline_discretizer.k_discretizer.KDiscretizer at 0x262ef124610>,
  'agg_type': 'cat',
  'nsep': False},
 {'name': 'glove_emb24_cfg2_quant100_sum',
  'glove_config': {'alpha': 0.75,
   'x_max': 15000,
   'embedding_size': 24,
   'num_epochs_train': 50},
  'disc': <ptls.preprocessing.baseline_discretizer.k_discretizer.KDiscretizer at 0x262ef127ca0>,
  'agg_type': 'sum',
  'nsep': False},
 {'name': 'glove_emb24_cfg2_quant100_mean',
  'glove_config': {'alpha': 0.75,
   'x_max': 15000,
   'embedding_size': 24,
   'num_epochs_train': 50},
  'disc': <ptls.preprocessing.baseline_discretizer.k_discretizer.KDiscretizer at 0x262ef127ac0>,
  'agg_type': 'mean',
  'nsep': False},
 {'name': 'glove_emb32_cfg2_quant100_cat',
  'glove_config': {'alpha': 0.75,
   'x_max': 15000,
   'embedding_size': 32,
   'num_epochs_train': 50},
  'disc': <ptls.preprocessing.baseline_discretizer.k_discretizer.KDiscretizer at 0x262ef125810>,
  'agg_type': 'cat',
  'nsep': False},
 {'name': 'glove_emb32_cfg2_quant100_sum',
  'glove_config': {'alpha': 0.75,
   'x_max': 15000,
   'embedding_size': 32,
   'num_epochs_train': 50},
  'disc': <ptls.preprocessing.baseline_discretizer.k_discretizer.KDiscretizer at 0x262ef125720>,
  'agg_type': 'sum',
  'nsep': False},
 {'name': 'glove_emb32_cfg2_quant100_mean',
  'glove_config': {'alpha': 0.75,
   'x_max': 15000,
   'embedding_size': 32,
   'num_epochs_train': 50},
  'disc': <ptls.preprocessing.baseline_discretizer.k_discretizer.KDiscretizer at 0x262ef125a20>,
  'agg_type': 'mean',
  'nsep': False}]

In [56]:
experiments = [
    {
        'name' : 'basic_model_emb_16',
        'nsep' : True
    }
]

In [10]:
for exp in experiments[3:]:
    df_params = {'numeric_cols': ['amount_rur'],
     'cat_cols': ['small_group'],
     'date_col': 'trans_date',
     'cat_unique': [202, 730],
     'id_col': 'client_id'}
    data = copy.deepcopy(source_data)
    if 'disc' in exp:
        disc = exp['disc']
        if exp['name'][:2] != "st" and ('ST' not in exp['name']) and (disc is not None):
            disc.fit(data)
            data = disc.transform(data, to_embeds=exp['nemb'] if 'nemb' in exp else False)
        elif (disc is not None):
            disc.fit(data.sample(int(1e+5), random_state=42).merge(targets, on=df_params['id_col'], how='left'))
            data = disc.transform(data, to_embeds=exp['nemb'] if 'nemb' in exp else False)
        print(f"{exp['name']}: DATA DISCRETIZED")

    if 'nemb' in exp and not exp['nemb']:
        df_params['cat_cols'] =  df_params['numeric_cols'] + df_params['cat_cols']
        df_params["cat_unique"] = (exp['disc'].k_bins if (type(exp['disc'].k_bins) is list) else [exp['disc'].k_bins] * len(df_params['numeric_cols'])) + df_params["cat_unique"]
        df_params['numeric_cols'] = []
    
    if 'glove_config' in exp:
        if not exp['nsep']:
            embedded_feats = df_params['numeric_cols'] + df_params['cat_cols'] + [df_params["date_col"]]
        else:
            embedded_feats = df_params['cat_cols'] + [df_params["date_col"]]
        folder_nm = f'../glove_embeddings/{exp["name"]}'[:-4] if exp['agg_type'] != 'mean' else f'../glove_embeddings/{exp["name"]}'[:-5]
        glove_embedding = GloveEmbedding(
            feature_names=embedded_feats,
            calculate_cooccur=False,
            embedding_folder=folder_nm,
            glove_params=exp['glove_config']
        )
        glove_embedding.load()
        data = glove_embedding.tokenize_data(data)

    preprocessor = PandasDataPreprocessor(
        col_id=df_params['id_col'],
        col_event_time=df_params['date_col'],
        event_time_transformation='none',
        category_transformation = 'none' if ('glove_config' in exp) else 'frequency',
        cols_category=df_params['cat_cols'],
        cols_numerical=df_params['numeric_cols'],
        return_records=True,
    )
#+ (df_params['numeric_cols'] if ('glove_config' in exp) else [])
#if ('nsep' in exp and exp['nsep']) else []    
    dataset = preprocessor.fit_transform(data)

    dataset = sorted(dataset, key=lambda x: x[df_params['id_col']])

    with open(f"../coles_prep_datasets/{exp['name']}_dataset.pkl", "wb") as fl:
        pickle.dump(dataset , fl)

    # with open(f"../coles_prep_datasets/{exp['name']}_dataset.pkl", "rb") as fl:
    #     dataset = pickle.load(fl)
    
    train, test = train_test_split(dataset, test_size=0.2, random_state=42)

    train, val = train_test_split(dataset, test_size=0.1, random_state=42)


    print(f"{exp['name']}: DATA PREPROCESSED AND SAVED")

    del dataset, data

    train_dl = PtlsDataModule(
        train_data = ColesDataset(
                MemoryMapDataset(
                    data=train,
                    i_filters=[
                        SeqLenFilter(min_seq_len=25),
                    ],
                ),
                splitter=SampleSlices(
                    split_count=5,
                    cnt_min=25,
                    cnt_max=200,
                ),
            ),
        train_num_workers=1,
        train_batch_size=256,
        valid_data = ColesDataset(
                MemoryMapDataset(
                    data=val,
                    i_filters=[
                        SeqLenFilter(min_seq_len=25),
                    ],
                ),
                splitter=SampleSlices(
                    split_count=5,
                    cnt_min=25,
                    cnt_max=200,
                ),
            ),
        valid_num_workers=1,
        valid_batch_size=256,
    )

    #seq_encoder = get_cat_encoder(df_params, agg_type=exp['agg_type'], num_emb_flag=exp['nemb'])
    seq_encoder = get_trans_encoder(df_params, agg_type=exp['agg_type'], algo=exp['algo'], numeric_separate=exp['nsep'])
    #seq_encoder = get_glove_encoder(df_params, exp, glove_embedding)
    #seq_encoder = get_basic_model_encoder(df_params)

    model = CoLESModule(
        seq_encoder=seq_encoder,
        optimizer_partial=partial(torch.optim.Adam, lr=0.001),
        lr_scheduler_partial=partial(torch.optim.lr_scheduler.StepLR, step_size=30, gamma=0.9),
    )

    early_stopping = EarlyStopping(f'valid/{model.metric_name}', mode='max', patience=2, min_delta=0.01)
    
    trainer = pl.Trainer(
        max_epochs=25,
        accelerator="gpu",
        callbacks = [early_stopping],
        enable_progress_bar=True,
        enable_model_summary=False,
        logger=False
    )

    print(f"{exp['name']}: TRAIN STARTS")

    trainer.fit(model, train_dl)
    print(trainer.logged_metrics)

    torch.save(seq_encoder.state_dict(), f"../models_coles/{exp['name']}_emb.pt")

    print(f"{exp['name']}: TRAIN ENDS, MODEL SAVED")

    del train, test

trx_tran_classic_quant100_sum: DATA DISCRETIZED
trx_tran_classic_quant100_sum: DATA PREPROCESSED AND SAVED

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
C:\Users\peter\anaconda3\envs\cv\lib\site-packages\pytorch_lightning\callbacks\model_checkpoint.py:613: UserWarning: Checkpoint directory C:\Users\peter\anaconda3\envs\cv\Scripts\ptls-glove\checkpoints exists and is not empty.
  rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

trx_tran_classic_quant100_sum: TRAIN STARTS

Sanity Checking: 0it [00:00, ?it/s]

C:\Users\peter\anaconda3\envs\cv\lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:224: PossibleUserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 12 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
C:\Users\peter\anaconda3\envs\cv\lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:224: PossibleUserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 12 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(

Training: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

{'loss': tensor(254.5145), 'seq_len': tensor(111.9250), 'valid/recall_top_k': tensor(0.1350)}
trx_tran_classic_quant100_sum: TRAIN ENDS, MODEL SAVED
trx_tran_orig_quant100: DATA DISCRETIZED

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
C:\Users\peter\anaconda3\envs\cv\lib\site-packages\pytorch_lightning\callbacks\model_checkpoint.py:613: UserWarning: Checkpoint directory C:\Users\peter\anaconda3\envs\cv\Scripts\ptls-glove\checkpoints exists and is not empty.
  rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

trx_tran_orig_quant100: DATA PREPROCESSED AND SAVED
trx_tran_orig_quant100: TRAIN STARTS

Sanity Checking: 0it [00:00, ?it/s]

C:\Users\peter\anaconda3\envs\cv\lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:224: PossibleUserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 12 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
C:\Users\peter\anaconda3\envs\cv\lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:224: PossibleUserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 12 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(

Training: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

{'loss': tensor(251.5079), 'seq_len': tensor(111.2933), 'valid/recall_top_k': tensor(0.1420)}
trx_tran_orig_quant100: TRAIN ENDS, MODEL SAVED
trx_tran_classic_quant100_cat: DATA DISCRETIZED

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
C:\Users\peter\anaconda3\envs\cv\lib\site-packages\pytorch_lightning\callbacks\model_checkpoint.py:613: UserWarning: Checkpoint directory C:\Users\peter\anaconda3\envs\cv\Scripts\ptls-glove\checkpoints exists and is not empty.
  rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

trx_tran_classic_quant100_cat: DATA PREPROCESSED AND SAVED
trx_tran_classic_quant100_cat: TRAIN STARTS

Sanity Checking: 0it [00:00, ?it/s]

C:\Users\peter\anaconda3\envs\cv\lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:224: PossibleUserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 12 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
C:\Users\peter\anaconda3\envs\cv\lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:224: PossibleUserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 12 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(

Training: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

{'loss': tensor(249.8992), 'seq_len': tensor(114.8783), 'valid/recall_top_k': tensor(0.1259)}
trx_tran_classic_quant100_cat: TRAIN ENDS, MODEL SAVED
Counter({'small_group': 153, 'amount_rur': 62})
trx_tran_classic_deeptlf9_sum: DATA DISCRETIZED

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
C:\Users\peter\anaconda3\envs\cv\lib\site-packages\pytorch_lightning\callbacks\model_checkpoint.py:613: UserWarning: Checkpoint directory C:\Users\peter\anaconda3\envs\cv\Scripts\ptls-glove\checkpoints exists and is not empty.
  rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

trx_tran_classic_deeptlf9_sum: DATA PREPROCESSED AND SAVED
trx_tran_classic_deeptlf9_sum: TRAIN STARTS

Sanity Checking: 0it [00:00, ?it/s]

C:\Users\peter\anaconda3\envs\cv\lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:224: PossibleUserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 12 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
C:\Users\peter\anaconda3\envs\cv\lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:224: PossibleUserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 12 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(

Training: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

{'loss': tensor(226.3748), 'seq_len': tensor(113.0117), 'valid/recall_top_k': tensor(0.3189)}
trx_tran_classic_deeptlf9_sum: TRAIN ENDS, MODEL SAVED
Counter({'small_group': 153, 'amount_rur': 62})
trx_tran_classic_deeptlf9_mean: DATA DISCRETIZED
trx_tran_classic_deeptlf9_mean: DATA PREPROCESSED AND SAVED

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
C:\Users\peter\anaconda3\envs\cv\lib\site-packages\pytorch_lightning\callbacks\model_checkpoint.py:613: UserWarning: Checkpoint directory C:\Users\peter\anaconda3\envs\cv\Scripts\ptls-glove\checkpoints exists and is not empty.
  rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

trx_tran_classic_deeptlf9_mean: TRAIN STARTS

Sanity Checking: 0it [00:00, ?it/s]

C:\Users\peter\anaconda3\envs\cv\lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:224: PossibleUserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 12 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
C:\Users\peter\anaconda3\envs\cv\lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:224: PossibleUserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 12 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(

Training: 0it [00:00, ?it/s]

RuntimeError: CUDA error: unknown error
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

In [8]:
df_params

{'numeric_cols': [],
 'cat_cols': ['amount_rur', 'small_group'],
 'date_col': 'trans_date',
 'cat_unique': [202, 730],
 'id_col': 'client_id'}

In [13]:
for i in train_dl.train_dataloader():
    ddd = i
    break

In [7]:
seq_encoder.trx_encoder.__dict__

{'training': False,
 '_parameters': OrderedDict(),
 '_buffers': OrderedDict(),
 '_non_persistent_buffers_set': set(),
 '_backward_hooks': OrderedDict(),
 '_is_full_backward_hook': None,
 '_forward_hooks': OrderedDict(),
 '_forward_pre_hooks': OrderedDict(),
 '_state_dict_hooks': OrderedDict(),
 '_load_state_dict_pre_hooks': OrderedDict(),
 '_load_state_dict_post_hooks': OrderedDict(),
 '_modules': OrderedDict([('embeddings',
               TransEmbedding(
                 (cat_table): ModuleDict(
                   (small_group): Embedding(203, 3)
                   (trans_date): Embedding(731, 3)
                 )
                 (forward_mlp): ModuleList(
                   (0): Linear(in_features=3, out_features=3, bias=True)
                   (1): Linear(in_features=3, out_features=3, bias=True)
                 )
                 (dropout): Dropout(p=0.2, inplace=False)
                 (emb_dict): ModuleDict(
                   (small_group): Embedding(203, 3)
                   (trans_date): Embedding(731, 3)
                 )
               ))]),
 'numeric_separate': False,
 'numeric_features': [],
 'device': 'cpu',
 'algo': 'orig',
 'esz': 3,
 'agg_type': None,
 'feature_names': ['small_group', 'trans_date']}

### Get cosine-dist metric values on train/test datasets

In [5]:
df_params = {'numeric_cols': ['amount_rur'],
     'cat_cols': ['small_group'],
     'date_col': 'trans_date',
     'cat_unique': [202, 730],
     'id_col': 'client_id'}

In [20]:
weights['trx_encoder.embeddings.amount_rur.weight'].shape

torch.Size([20, 16])

In [ ]:
from lightgbm import LGBMClassifier
from sklearn.ensemble import RandomForestClassifier
res_metrics = []
N_TRIALS = 5

tasks = {'boosting' : LGBMClassifier(), 'r_forest' : RandomForestClassifier()}

def get_train_test_age_bins_scenario(df_params, embeds, ds_type):
    data_path = "../data/age_bins"
    
    df_target = pd.read_csv(os.path.join(data_path, 'train_target.csv'))
    df_target = df_target.set_index(df_params["id_col"])
    df_target.rename(columns={"bins": "target"}, inplace=True)
    
    train_df = pd.DataFrame(data=train_embeds, columns=[f'embed_{i}' for i in range(train_embeds.shape[1])])
    train_df[df_params["id_col"]] = [x[df_params["id_col"]] for x in train]
    train_df = train_df.merge(df_target, how='left', on=df_params["id_col"])
    
    test_df = pd.DataFrame(data=test_embeds, columns=[f'embed_{i}' for i in range(test_embeds.shape[1])])
    test_df[df_params["id_col"]] = [x[df_params["id_col"]] for x in test]
    test_df = test_df.merge(df_target, how='left', on=df_params["id_col"])
    return train_df, test_df

for exp in experiments:
    df_params = {'numeric_cols': ['amount_rur'],
     'cat_cols': ['small_group'],
     'date_col': 'trans_date',
     'cat_unique': [202, 730],
     'id_col': 'client_id'}
    if 'nemb' in exp and not exp['nemb']:
        df_params['cat_cols'] =  df_params['numeric_cols'] + df_params['cat_cols']
        df_params["cat_unique"] = (exp['disc'].k_bins if (type(exp['disc'].k_bins) is list) else [exp['disc'].k_bins] * len(df_params['numeric_cols'])) + df_params["cat_unique"]
        df_params['numeric_cols'] = []
    with open(f"../coles_prep_datasets/{exp['name']}_dataset.pkl", "rb") as fl:
        dataset = pickle.load(fl)

    train, test = train_test_split(dataset, test_size=0.2, random_state=42)

    if 'glove_config' in exp:
        if not exp['nsep']:
            embedded_feats = df_params['numeric_cols'] + df_params['cat_cols'] + [df_params["date_col"]]
        else:
            embedded_feats = df_params['cat_cols'] + [df_params["date_col"]]
        folder_nm = f'../glove_embeddings/{exp["name"]}'[:-4] if exp['agg_type'] != 'mean' else f'../glove_embeddings/{exp["name"]}'[:-5]
        glove_embedding = GloveEmbedding(
            feature_names=embedded_feats,
            calculate_cooccur=False,
            embedding_folder=folder_nm,
            glove_params=exp['glove_config']
        )
        glove_embedding.load()
    
    #seq_encoder = get_cat_encoder(df_params, agg_type=exp['agg_type'], num_emb_flag=exp['nemb'])
    seq_encoder = get_trans_encoder(df_params, agg_type=exp['agg_type'], algo=exp['algo'], numeric_separate=exp['nsep'])
    #seq_encoder = get_glove_encoder(df_params, exp, glove_embedding)
    #seq_encoder.load_state_dict(torch.load(f"../models_coles/{exp['name']}_emb.pt"))

    metric = BatchRecallTopK(4)

    train_embeds = None
    test_embeds = None
    #('train', train)
    for ds_name, ds in [('test', test)]:
        dl = PtlsDataModule(
            test_data = ColesDataset(
                    MemoryMapDataset(
                        data=ds,
                        i_filters=[
                            SeqLenFilter(min_seq_len=25),
                        ],
                    ),
                    splitter=SampleSlices(
                        split_count=5,
                        cnt_min=25,
                        cnt_max=200,
                    ),
                ),
            train_num_workers=1,
            train_batch_size=256,
        )

        module = TestModule(
            model = seq_encoder,
            metrics = {"recall_top_k" : metric}
        )
    
        predictor = pl.Trainer(
                accelerator="gpu",
                enable_model_summary=False,
                logger=False
        )

        predictor.predict(module, dl)

        ds_metrics = module.get_metrics()

        for m in ds_metrics:
            res_metrics.append([exp['name'], ds_name, m, ds_metrics[m]])

    coles_model = CoLESModule(
            seq_encoder=seq_encoder,
    )

    inference_runner = pl.Trainer(
        accelerator="gpu",
        enable_progress_bar=True,
        enable_model_summary=False,
        logger=False
    )
    
    train_dl = inference_data_loader(train, num_workers=0, batch_size=256)
    train_embeds = torch.vstack(inference_runner.predict(coles_model, train_dl))
    
    test_dl = inference_data_loader(test, num_workers=0, batch_size=256)
    test_embeds = torch.vstack(inference_runner.predict(coles_model, test_dl))

    train_df, test_df = get_train_test_age_bins_scenario(df_params, train_embeds, test_embeds)

    for task_name, clf in tasks.items():
        sc_test = 0
        sc_train = 0
        num = 0
        for i in tqdm(range(N_TRIALS)):
            embed_columns = [x for x in train_df.columns if x.startswith('embed')]
            x_train, y_train = train_df[embed_columns], train_df['target']
            x_test, y_test = test_df[embed_columns], test_df['target']
            
            clf.fit(x_train, y_train)
            sc_test += clf.score(x_test, y_test)
            #sc_train += clf.score(x_train, y_train)
            num += 1

        #res_metrics.append([exp['name'], 'train', f"acc_{task_name}", sc_train/num])
        res_metrics.append([exp['name'], 'test', f"acc_{task_name}", sc_test/num])

    report = pd.DataFrame(res_metrics, columns = ['exp_name', 'dataset', 'metric', 'value'])
    report.to_csv('../coles_report/experiments/report_trans_trx.csv')

In [39]:
r = []
for j in range(3):
    r.append(np.random.random(18) * 0.1 + 0.9)
    
pd.DataFrame(r, columns=['a' + str(i) for i in range(18)]).to_excel('rand.xlsx')

In [10]:
del train_df, test_df, train_embeds, test_embeds, train, test

In [5]:
reps = []
for i in range(1, 3):
    reps.append(pd.read_csv(f'..//coles_report/experiments/report_glove{i}.csv'))
reps = pd.concat(reps).drop(columns = ['Unnamed: 0'])

In [23]:
a = list(map(lambda x: x.split('_'), reps.exp_name.values))
reps['aggt'] = [i[-1] for i in a]
reps['mod'] = [i[-2] for i in a]
reps['cfg'] = [i[2] for i in a]

reps.sort_values(by=['aggt', 'cfg', 'mod', 'dataset', 'metric'], ascending=False)[['aggt', 'cfg', 'mod', 'dataset', 'metric', 'value']].to_excel(f'..//coles_report/experiments/report_glove.xlsx')

In [10]:
%%time

dataset = preprocessor.fit_transform(data)

CPU times: total: 14.7 s
Wall time: 15.9 s

In [11]:
import pickle

with open('preprocessor.p', 'wb') as f:
    pickle.dump(preprocessor, f)

In [12]:
dataset = sorted(dataset, key=lambda x: x[df_params['id_col']])

In [13]:
from sklearn.model_selection import train_test_split

train, test = train_test_split(dataset, test_size=0.2, random_state=42)

len(train), len(test)

(12000, 3000)

In [14]:
del dataset

## Embedding training

Model training in our framework organised via pytorch-lightning (pl) framework.
The key parts of neural networks training in pl are: 

    * model (`pytorch_lightning.LightningModule`)
    * data loader (`torch.utils.data.DataLoader`)
    * trainer (`pytorch_lightning.Trainer`)
    
For futher details check https://pytorchlightning.ai/

### Model definition

In [23]:
df_params

{'numeric_cols': ['amount'],
 'cat_cols': ['mcc_code', 'tr_type'],
 'cat_unique': [184, 77, 457],
 'date_col': 'tr_datetime',
 'id_col': 'customer_id'}

In [22]:
from functools import partial
from ptls.nn import RnnSeqEncoder, TrxEncoder
from ptls.nn.trx_encoder.trx_encoder_glove import TrxEncoderGlove
from ptls.frames.coles import CoLESModule
import ptls
import torch

def get_basic_model_encoder(df_params):
    embeddings=dict()
    for i, f in enumerate(df_params["cat_cols"] + [df_params["date_col"]]):
        embeddings[f] = {'in' : df_params["cat_unique"][i], 'out' : 16}
    
    trx_encoder_params = dict(
        embeddings_noise=0.003,
        numeric_values=dict([(fe, 'identity') for fe in df_params['numeric_cols']]),
        embeddings=embeddings
    )
    
    seq_encoder = RnnSeqEncoder(
        trx_encoder=TrxEncoder(**trx_encoder_params),
        hidden_size=256,
        type='gru',
    )
    
    return seq_encoder

def get_glove_model_encoder(agg_type):
    seq_encoder = RnnSeqEncoder(
        trx_encoder=TrxEncoderGlove(glove_embedding, agg_type=agg_type),
        hidden_size=256,
        type='gru',
    )
    return seq_encoder


#seq_encoder = get_basic_model_encoder(df_params)
seq_encoder = get_glove_model_encoder(agg_type="sum")

model = CoLESModule(
    seq_encoder=seq_encoder,
    optimizer_partial=partial(torch.optim.Adam, lr=0.001),
    lr_scheduler_partial=partial(torch.optim.lr_scheduler.StepLR, step_size=30, gamma=0.9),
)

### Data loader

In [23]:
from ptls.data_load.datasets import MemoryMapDataset
from ptls.data_load.iterable_processing import SeqLenFilter
from ptls.frames.coles import ColesDataset
from ptls.frames.coles.split_strategy import SampleSlices
from ptls.frames import PtlsDataModule

train_dl = PtlsDataModule(
    train_data=ColesDataset(
        MemoryMapDataset(
            data=train,
            i_filters=[
                SeqLenFilter(min_seq_len=25),
            ],
        ),
        splitter=SampleSlices(
            split_count=5,
            cnt_min=25,
            cnt_max=200,
        ),
    ),
    train_num_workers=1,
    train_batch_size=256,
)

### Trainer

In [24]:
import torch
import pytorch_lightning as pl

import logging

trainer = pl.Trainer(
    max_epochs=15,
    accelerator="gpu",
    #devices=1,
    enable_progress_bar=True,
)

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs

### Training

In [25]:
%%time
print(f'logger.version = {trainer.logger.version}')
trainer.fit(model, train_dl)
print(trainer.logged_metrics)

C:\Users\peter\anaconda3\envs\cv\lib\site-packages\pytorch_lightning\trainer\configuration_validator.py:108: PossibleUserWarning: You defined a `validation_step` but have no `val_dataloader`. Skipping val loop.
  rank_zero_warn(
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name               | Type            | Params
-------------------------------------------------------
0 | _loss              | ContrastiveLoss | 0
1 | _seq_encoder       | RnnSeqEncoder   | 270 K
2 | _validation_metric | BatchRecallTopK | 0
3 | _head              | Head            | 0
-------------------------------------------------------
210 K     Trainable params
60.0 K    Non-trainable params
270 K     Total params
1.083     Total estimated model params size (MB)

logger.version = 175

C:\Users\peter\anaconda3\envs\cv\lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:224: PossibleUserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 12 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
C:\Users\peter\anaconda3\envs\cv\lib\site-packages\pytorch_lightning\trainer\trainer.py:1609: PossibleUserWarning: The number of training batches (46) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.
  rank_zero_warn(

Training: 0it [00:00, ?it/s]

`Trainer.fit` stopped: `max_epochs=15` reached.

{'loss': tensor(257.4940), 'seq_len': tensor(97.3034)}
CPU times: total: 1min 58s
Wall time: 7min 6s

### Save sequence encoder for other experiments

In [53]:
torch.save(seq_encoder.state_dict(), "coles-emb.pt")

## Inference

In [26]:
# embedding inference

train_dl = inference_data_loader(train, num_workers=0, batch_size=256)
train_embeds = torch.vstack(trainer.predict(model, train_dl, ))

test_dl = inference_data_loader(test, num_workers=0, batch_size=256)
test_embeds = torch.vstack(trainer.predict(model, test_dl))

train_embeds.shape, test_embeds.shape

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
C:\Users\peter\anaconda3\envs\cv\lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:224: PossibleUserWarning: The dataloader, predict_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 12 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(

Predicting: 46it [00:00, ?it/s]

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: 46it [00:00, ?it/s]

(torch.Size([12000, 256]), torch.Size([3000, 256]))

In [20]:
def get_train_test_age_bins_scenario(df_params, train_embeds, test_embeds):
    data_path = "data/age_bins"
    
    df_target = pd.read_csv(os.path.join(data_path, 'train_target.csv'))
    df_target = df_target.set_index(df_params["id_col"])
    df_target.rename(columns={"bins": "target"}, inplace=True)
    
    train_df = pd.DataFrame(data=train_embeds, columns=[f'embed_{i}' for i in range(train_embeds.shape[1])])
    train_df[df_params["id_col"]] = [x[df_params["id_col"]] for x in train]
    train_df = train_df.merge(df_target, how='left', on=df_params["id_col"])
    
    test_df = pd.DataFrame(data=test_embeds, columns=[f'embed_{i}' for i in range(test_embeds.shape[1])])
    test_df[df_params["id_col"]] = [x[df_params["id_col"]] for x in test]
    test_df = test_df.merge(df_target, how='left', on=df_params["id_col"])
    return train_df, test_df

def get_train_test_gender_scenario(df_params, train_embeds, test_embeds):
    data_path = "data/gender"
    
    df_target = pd.read_csv(os.path.join(data_path, 'gender_train.csv'))
    df_target = df_target.set_index(df_params["id_col"])
    df_target.rename(columns={"gender": "target"}, inplace=True)
    
    train_df = pd.DataFrame(data=train_embeds, columns=[f'embed_{i}' for i in range(train_embeds.shape[1])])
    train_df[df_params["id_col"]] = [x[df_params["id_col"]] for x in train]
    train_df = train_df.merge(df_target, how='left', on=df_params["id_col"])
    
    test_df = pd.DataFrame(data=test_embeds, columns=[f'embed_{i}' for i in range(test_embeds.shape[1])])
    test_df[df_params["id_col"]] = [x[df_params["id_col"]] for x in test]
    test_df = test_df.merge(df_target, how='left', on=df_params["id_col"])
    train_df = train_df.fillna(2)
    test_df = test_df.fillna(2)
    return train_df, test_df

In [10]:
import os
import pandas as pd

data_path = 'data/rosbank'

data_train = pd.read_csv(os.path.join(data_path, 'train.csv'))
data_test = pd.read_csv(os.path.join(data_path, 'test.csv'))

df_trx = get_df_trx(data_train, data_test)
df_trx = df_trx.fillna("unknown_type")
df_target = get_df_target(data_train)

In [56]:
# join target and embeddings

#df_target = pd.read_csv(os.path.join(data_path, 'train_target.csv'))
#df_target = pd.read_csv(os.path.join(data_path, 'gender_train.csv'))
#df_target = df_target.rename(columns={"customer_id" : "client_id"})
#df_target = df_target.set_index('client_id')
#df_target.rename(columns={"bins": "target"}, inplace=True)
df_target.rename(columns={"target_flag": "target"}, inplace=True)

train_df = pd.DataFrame(data=train_embeds, columns=[f'embed_{i}' for i in range(train_embeds.shape[1])])
train_df['client_id'] = [x['client_id'] for x in train]
#train_df = train_df.merge(df_target, how='left', on='client_id')

test_df = pd.DataFrame(data=test_embeds, columns=[f'embed_{i}' for i in range(test_embeds.shape[1])])
test_df['client_id'] = [x['client_id'] for x in test]
#test_df = test_df.merge(df_target, how='left', on='client_id')

print(train_df.shape, test_df.shape)

(8173, 257) (2044, 257)

In [57]:
df_target["client_id"] = df_target.index

In [58]:
train_df = train_df.merge(df_target, how='left', on='client_id')

In [59]:
test_df = test_df.merge(df_target, how='left', on='client_id')

Obtained embeddings can be used as features for model training

For example:

In [27]:
from sklearn.ensemble import RandomForestClassifier

metrics_on_tasks = []

for exp in experiments:

    train_dl = inference_data_loader(train, num_workers=0, batch_size=256)
    train_embeds = torch.vstack(trainer.predict(model, train_dl, ))
    
    test_dl = inference_data_loader(test, num_workers=0, batch_size=256)
    test_embeds = torch.vstack(trainer.predict(model, test_dl))


    train_df, test_df = get_train_test_gender_scenario(df_params, train_embeds, test_embeds)
    
    sc = 0
    num = 0
    for i in range(10):
        embed_columns = [x for x in train_df.columns if x.startswith('embed')]
        x_train, y_train = train_df[embed_columns], train_df['target']
        x_test, y_test = test_df[embed_columns], test_df['target']
        
        clf = RandomForestClassifier()
        clf.fit(x_train, y_train)
        sc += clf.score(x_test, y_test)
        num += 1
    sc/num

0.4342

In [ ]:
#glove_cat 0.75 100 tree_binning 3t
cat 0.5846666666666667
mean 0.5629666666666667
sum 0.5711

#glove_cat 0.75 5000 tree_binning 6t
cat 0.5912666666666666
mean 0.5697333333333333
sum 0.5792666666666667

#glove_cat 0.75 15000 tree_binning 9t
cat 0.5797666666666668
mean 0.5720000000000001
sum 0.5781666666666667

###gender

#glove_cat 0.75 100 tree_binning 3t
cat 0.438
mean 0.4342
sum 0.5711

#glove_cat 0.75 5000 tree_binning 6t
cat 0.4500333333333333
mean 0.4312666666666667
sum 0.4416333333333333

#glove_cat 0.75 15000 tree_binning 9t
cat 0.4503666666666667
mean 0.433
sum 0.44053333333333333

In [ ]:
#normal
0.48356164383561645

#glove_mean 0.75 1000 100 bins
mean 0.4900195694716243
sum 0.49735812133072405
cat 0.4990215264187867

#glove_mean 0.75 5000 150 bins
mean 0.49549902152641884
sum 0.4918786692759296
cat 0.5001956947162427