In [3]:
import hydra
import yaml
from omegaconf import DictConfig
import pytorch_lightning as pl
import os
import sys
import pickle

from pytorch_lightning.callbacks import LearningRateMonitor
from pytorch_lightning.callbacks import ModelCheckpoint
from pytorch_lightning.loggers import TensorBoardLogger

with open('ptls_config.yaml', 'rb') as fl:
    conf = DictConfig(yaml.safe_load(fl))

In [3]:
with open('../data/train_trx.parquet', 'rb') as fl:
    data = pickle.load(fl)

In [2]:
dm = hydra.utils.instantiate(conf.data_module)

In [8]:
#train
if 'seed_everything' in conf:
    pl.seed_everything(conf.seed_everything)

model = hydra.utils.instantiate(conf.pl_module)
#dm = hydra.utils.instantiate(conf.data_module)

_trainer_params = conf.trainer
_trainer_params_additional = {}

_trainer_params_callbacks = []

lr_monitor = LearningRateMonitor(logging_interval='step')
_trainer_params_callbacks.append(lr_monitor)

if len(_trainer_params_callbacks) > 0:
    _trainer_params_additional['callbacks'] = _trainer_params_callbacks
    
trainer = pl.Trainer(**_trainer_params, **_trainer_params_additional)
trainer.fit(model, dm)

if 'model_path' in conf:
    torch.save(model.seq_encoder, conf.model_path)

Seed set to 42
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
C:\Users\toppc\.conda\envs\torch_cu118\Lib\site-packages\pytorch_lightning\trainer\connectors\logger_connector\logger_connector.py:76: Starting from v1.9.0, `tensorboardX` has been removed as a dependency of the `pytorch_lightning` package, due to potential conflicts with other packages in the ML ecosystem. For this reason, `logger=True` will use `CSVLogger` as the default logger, unless the `tensorboard` or `tensorboardX` packages are found. Please `pip install lightning[extra]` or one of them to enable TensorBoard support by default
You are using a CUDA device ('NVIDIA GeForce RTX 4070 Ti SUPER') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name               | Type            | Params | Mode
---------------------------------------------------------------
0 | _loss              | ContrastiveLoss | 0      | train
1 | _seq_encoder       | RnnSeqEncoder   | 3.4 M  | train
2 | _validation_metric | BatchRecallTopK | 0      | train
3 | _head              | Head            | 0      | train
---------------------------------------------------------------
3.4 M     Trainable params
0         Non-trainable params
3.4 M     Total params
13.557    Total estimated model params size (MB)
19        Modules in train mode
0         Modules in eval mode

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

Training: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

`Trainer.fit` stopped: `max_epochs=150` reached.

NameError: name 'torch' is not defined

In [15]:
#inference
import logging

import hydra
import pandas as pd
import pytorch_lightning as pl
import torch
import torch.multiprocessing
from omegaconf import DictConfig
from torch.utils.data.dataloader import DataLoader

from ptls.data_load.utils import collate_feature_dict
from ptls.frames.inference_module import InferenceModule

def save_scores(df_scores, output_conf):
    output_name = output_conf.path
    output_format = output_conf.format

    output_path = f'{output_name}.{output_format}'

    if output_format == 'pickle':
        df_scores.to_pickle(output_path)
    elif output_format == 'csv':
        df_scores.to_csv(output_path, sep=',', header=True, index=False)
    elif output_format == 'parquet':
        df_scores.to_parquet(output_path)
    else:
        print('error')


if 'seed_everything' in conf:
    pl.seed_everything(conf.seed_everything)

seq_encoder = hydra.utils.instantiate(conf.inference.seq_encoder)
if type(seq_encoder) is DictConfig and seq_encoder.get('load_from_checkpoint', False):
    pl_module = hydra.utils.instantiate(conf.pl_module)
    pl_module.load_state_dict(torch.load(seq_encoder['f'])['state_dict'])
    seq_encoder = pl_module.seq_encoder
model = InferenceModule(
    model=seq_encoder,
    pandas_output=True, model_out_name='emb',
)
model.model.is_reduce_sequence = True

dataset_inference = hydra.utils.instantiate(conf.inference.dataset)
inference_dl = DataLoader(
    dataset=dataset_inference,
    collate_fn=collate_feature_dict,
    shuffle=False,
    num_workers=conf.inference.get('num_workers', 0),
    batch_size=conf.inference.get('batch_size', 128),
)

if torch.cuda.is_available():
    accelerator = "cuda"
    devices = 1
else:
    accelerator = "cpu"
    devices = 0

df_scores = pl.Trainer(accelerator=accelerator, devices=devices, max_epochs=-1).predict(model, inference_dl)
df_scores = pd.concat(df_scores, axis=0)

save_scores(df_scores, conf.inference.output)

Seed set to 42
C:\Users\toppc\.conda\envs\torch_cu118\Lib\site-packages\hydra\_internal\instantiate\_instantiate2.py:92: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  return _target_(*args, **kwargs)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
C:\Users\toppc\.conda\envs\torch_cu118\Lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:420: Consider setting `persistent_workers=True` in 'predict_dataloader' to speed up the dataloader worker initialization.

Predicting: |          | 0/? [00:00<?, ?it/s]

In [42]:
with open('../data/embeddings/mles_embeddings.pickle', 'rb') as fl:
    embeds = pickle.load(fl)

embeds.customer_id = embeds.customer_id.astype('int64')

target = pd.read_csv('../data/gender/gender_train.csv').drop(columns=['Unnamed: 0'])
test_ids = pd.read_csv('../data/test_ids.csv')
train_ids = pd.DataFrame({'customer_id' : list(set(embeds.customer_id.values) - set(test_ids.customer_id.values))})

embeds = embeds.merge(target, on='customer_id', how='inner')

train_df = embeds.merge(train_ids, on='customer_id', how='inner').rename(columns={'gender' : 'target'})
test_df = embeds.merge(test_ids, on='customer_id', how='inner').rename(columns={'gender' : 'target'})

In [43]:
embeds = embeds.merge(target, on='customer_id', how='inner')

train_df = embeds.merge(train_ids, on='customer_id', how='inner').rename(columns={'gender' : 'target'})
test_df = embeds.merge(test_ids, on='customer_id', how='inner').rename(columns={'gender' : 'target'})

In [44]:
train_df

,customer_id,emb_0000,emb_0001,emb_0002,emb_0003,emb_0004,emb_0005,emb_0006,emb_0007,emb_0008,...,emb_1015,emb_1016,emb_1017,emb_1018,emb_1019,emb_1020,emb_1021,emb_1022,emb_1023,target
0,10058778,-0.659025,-0.999930,-0.013956,0.289240,-0.017789,-0.011142,-0.147377,-0.012317,0.063469,...,0.026012,0.952506,-0.005079,0.002005,0.544288,-0.770644,-0.131604,-0.065310,-0.014201,1
1,10230827,-0.857736,-0.999987,-0.028047,-0.023356,-0.004569,0.001457,0.122885,-0.022659,0.023860,...,0.054398,0.990353,0.011602,-0.005946,-0.085316,0.133903,-0.040571,0.070587,-0.176885,0
2,11681378,-0.794531,-0.999997,-0.127196,0.316811,-0.084344,0.016344,0.057524,-0.011266,-0.111917,...,0.036370,0.895815,0.123837,0.010396,0.252992,-0.041481,-0.195868,-0.024594,-0.076999,1
3,14123285,-0.526916,-0.999974,-0.042490,0.166428,0.034522,-0.034639,0.081142,-0.083523,0.084043,...,0.069895,0.992014,-0.005653,-0.023697,-0.021593,0.115210,-0.097603,-0.007214,-0.065185,0
4,16536678,-0.999095,-0.997538,0.004072,-0.005387,0.037502,-0.005258,-0.010248,0.116659,0.026855,...,0.083969,0.958235,0.001020,0.019991,-0.187866,0.288676,-0.169909,0.091240,0.045687,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7555,96649358,-0.275459,-0.999819,0.029100,-0.012849,-0.077690,0.003478,0.077346,0.000998,-0.024820,...,0.091327,0.972289,0.004735,-0.012025,-0.061398,0.019602,-0.084410,0.071780,-0.010938,0
7556,97619321,-0.849478,-0.999671,-0.016505,0.073108,-0.081246,0.006040,-0.096665,-0.180980,-0.125174,...,0.047542,0.944912,0.016983,-0.001256,-0.183651,0.072100,-0.070169,-0.002834,0.146061,0
7557,98165656,-0.755762,-0.999936,0.022088,0.051181,0.002524,0.005706,-0.002312,0.091716,-0.025516,...,0.075486,0.838851,0.862938,-0.018748,-0.153051,0.054464,-0.140210,0.089506,-0.155961,0
7558,98408171,-0.981090,-0.997253,0.931196,0.045892,-0.024214,0.002786,0.034886,0.050000,-0.006407,...,0.055503,0.972233,0.033353,-0.000018,-0.246751,0.063070,-0.039745,0.243949,-0.162290,0
7559,99984336,-0.622022,-0.997283,-0.023657,0.054651,0.005519,-0.002682,-0.118235,0.052870,-0.049513,...,0.028804,0.969285,0.000433,0.000719,0.783961,0.074202,-0.073425,0.065083,-0.335485,1

In [10]:
embeds

,customer_id,emb_0000,emb_0001,emb_0002,emb_0003,emb_0004,emb_0005,emb_0006,emb_0007,emb_0008,...,emb_1014,emb_1015,emb_1016,emb_1017,emb_1018,emb_1019,emb_1020,emb_1021,emb_1022,emb_1023
0,10058778,-0.659025,-0.999930,-0.013956,0.289240,-0.017789,-0.011142,-0.147377,-0.012317,0.063469,...,-0.524166,0.026012,0.952506,-0.005079,0.002005,0.544288,-0.770644,-0.131604,-0.065310,-0.014201
1,10230827,-0.857736,-0.999987,-0.028047,-0.023356,-0.004569,0.001457,0.122885,-0.022659,0.023860,...,0.095473,0.054398,0.990353,0.011602,-0.005946,-0.085316,0.133903,-0.040571,0.070587,-0.176885
2,11681378,-0.794531,-0.999997,-0.127196,0.316811,-0.084344,0.016344,0.057524,-0.011266,-0.111917,...,0.027425,0.036370,0.895815,0.123837,0.010396,0.252992,-0.041481,-0.195868,-0.024594,-0.076999
3,14123285,-0.526916,-0.999974,-0.042490,0.166428,0.034522,-0.034639,0.081142,-0.083523,0.084043,...,-0.112450,0.069895,0.992014,-0.005653,-0.023697,-0.021593,0.115210,-0.097603,-0.007214,-0.065185
4,16536678,-0.999095,-0.997538,0.004072,-0.005387,0.037502,-0.005258,-0.010248,0.116659,0.026855,...,-0.066590,0.083969,0.958235,0.001020,0.019991,-0.187866,0.288676,-0.169909,0.091240,0.045687
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499,8268076,-0.993769,-0.999987,0.135282,0.105743,0.509054,-0.001832,-0.219376,0.132463,-0.013509,...,-0.424625,0.063497,0.354904,0.194155,-0.020339,-0.181798,0.085183,-0.137621,0.076641,-0.064054
500,84382825,-0.781714,-0.985235,-0.094716,-0.006093,0.060391,-0.003308,-0.002520,-0.066364,-0.080465,...,-0.171911,0.058274,0.911063,0.176292,0.003573,-0.181102,0.033791,-0.017741,0.037581,-0.075079
501,84389511,-0.681646,-0.998819,-0.038797,0.077169,0.009626,0.004073,-0.046417,0.062952,-0.051160,...,-0.243219,0.051807,0.737632,0.003183,0.000700,0.837390,0.016546,-0.098680,-0.513867,-0.488545
502,93014616,-0.680973,-0.999853,-0.165854,0.046439,0.354506,-0.000869,-0.080001,-0.308049,-0.199264,...,-0.470654,0.053449,0.873191,0.003579,-0.004253,0.640458,0.042011,-0.052643,0.118728,0.009732
503,956512,-0.629115,-0.994082,-0.049750,0.068003,0.048843,-0.000641,0.031175,0.048292,-0.043840,...,-0.060398,0.040744,0.882613,0.005618,0.000578,0.709149,0.029097,-0.089733,0.054439,-0.409179

In [15]:
target = pd.read_csv('../data/gender/gender_train.csv').drop(columns=['Unnamed: 0'])
target

      customer_id  gender
0        10928546       1
1        69348468       1
2        61009479       0
3        74045822       0
4        27979606       1
...           ...     ...
8395     90417572       0
8396     66837341       0
8397     10758984       1
8398     11376556       0
8399     29190649       0

[8400 rows x 2 columns]

In [7]:
import pandas as pd
test_ids = pd.read_csv('../data/test_ids.csv')

In [8]:
test_ids

     customer_id
0          49793
1         104032
2         126935
3         218079
4         340557
..           ...
835     99415717
836     99590294
837     99717689
838     99882949
839     99915912

[840 rows x 1 columns]

In [1]:
#boosting validation:

import os

import luigi
import hydra

from omegaconf import DictConfig, OmegaConf
from embeddings_validation import ReportCollect
from embeddings_validation.config import Config
from embeddings_validation.tasks.fold_splitter import FoldSplitter

In [5]:
with open('ptls_embedding_validation.yaml', 'rb') as fl:
    conf = DictConfig(yaml.safe_load(fl))

conf.workers = 5
if conf.workers is None: raise AttributeError('Define the number of workers: +workers=4')
conf.total_cpu_count = 10
if conf.total_cpu_count is None: raise AttributeError('Define the number of cpu on your machine: +total_cpu_count=8')

config = Config.get_conf(conf)

if conf.get('split_only', False):
    task = FoldSplitter(
        conf=config,
    )
else:
    task = ReportCollect(
        conf=config,
        total_cpu_count=conf['total_cpu_count'],
    )
luigi.build([task], workers=conf['workers'],
                    local_scheduler=conf.get('local_scheduler', True),
                    log_level=conf.get('log_level', 'INFO'))

C:\Users\toppc\.conda\envs\torch_cu118\Lib\site-packages\luigi\parameter.py:296: UserWarning: Parameter "conf" with value "<embeddings_validation.config.Config object at 0x0000020EF6598380>" is not of type string.
  warnings.warn('Parameter "{}" with value "{}" is not of type string.'.format(param_name, param_value))
INFO: Informed scheduler that task   ReportCollect__embeddings_vali_20_0110b24ea1   has status   PENDING
INFO: Informed scheduler that task   ReportByFolds__embeddings_vali_mles_embeddings_lgbm_5d1b433d2e   has status   PENDING
INFO: Informed scheduler that task   FoldEstimator__embeddings_vali_mles_embeddings_4_020bb69f0a   has status   PENDING
INFO: Informed scheduler that task   FoldSplitter__embeddings_vali_7a864fe7f9   has status   DONE
INFO: Informed scheduler that task   FoldEstimator__embeddings_vali_mles_embeddings_3_a29dffe1a9   has status   PENDING
INFO: Informed scheduler that task   FoldEstimator__embeddings_vali_mles_embeddings_2_3609f235b2   has status   PENDING
INFO: Informed scheduler that task   FoldEstimator__embeddings_vali_mles_embeddings_1_57ba1da0cc   has status   PENDING
INFO: Informed scheduler that task   FoldEstimator__embeddings_vali_mles_embeddings_0_1f90cc901e   has status   PENDING
INFO: Done scheduling tasks
INFO: Running Worker with 10 processes
INFO: Informed scheduler that task   FoldEstimator__embeddings_vali_mles_embeddings_4_020bb69f0a   has status   FAILED
INFO: Informed scheduler that task   FoldEstimator__embeddings_vali_mles_embeddings_3_a29dffe1a9   has status   FAILED
INFO: Worker Worker(salt=590158509, workers=10, host=DESKTOP-287JIAK, username=toppc, pid=6948) was stopped. Shutting down Keep-Alive thread

KeyboardInterrupt: